/* tslint:disable */
/* eslint-disable */
/**
 * Cezzi\'s Cocktails Accounts Api
 * An API for managing user accounts in Cezzi\'s Cocktails application.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  AccountCocktailRatingsRs,
  AccountOwnedProfileRs,
  ChangeAccountOwnedEmailRq,
  ChangeAccountOwnedPasswordRq,
  ChangeAccountOwnedUsernameRq,
  CocktailRecommendationRq,
  ManageFavoriteCocktailsRq,
  ProblemDetails,
  RateCocktailRq,
  RateCocktailRs,
  UpdateAccountOwnedAccessibilitySettingsRq,
  UpdateAccountOwnedNotificationSettingsRq,
  UpdateAccountOwnedProfileRq,
  UploadProfileImageRs,
} from '../models/index';
import {
    AccountCocktailRatingsRsFromJSON,
    AccountCocktailRatingsRsToJSON,
    AccountOwnedProfileRsFromJSON,
    AccountOwnedProfileRsToJSON,
    ChangeAccountOwnedEmailRqFromJSON,
    ChangeAccountOwnedEmailRqToJSON,
    ChangeAccountOwnedPasswordRqFromJSON,
    ChangeAccountOwnedPasswordRqToJSON,
    ChangeAccountOwnedUsernameRqFromJSON,
    ChangeAccountOwnedUsernameRqToJSON,
    CocktailRecommendationRqFromJSON,
    CocktailRecommendationRqToJSON,
    ManageFavoriteCocktailsRqFromJSON,
    ManageFavoriteCocktailsRqToJSON,
    ProblemDetailsFromJSON,
    ProblemDetailsToJSON,
    RateCocktailRqFromJSON,
    RateCocktailRqToJSON,
    RateCocktailRsFromJSON,
    RateCocktailRsToJSON,
    UpdateAccountOwnedAccessibilitySettingsRqFromJSON,
    UpdateAccountOwnedAccessibilitySettingsRqToJSON,
    UpdateAccountOwnedNotificationSettingsRqFromJSON,
    UpdateAccountOwnedNotificationSettingsRqToJSON,
    UpdateAccountOwnedProfileRqFromJSON,
    UpdateAccountOwnedProfileRqToJSON,
    UploadProfileImageRsFromJSON,
    UploadProfileImageRsToJSON,
} from '../models/index';

export interface ChangeAccountOwnedEmailV1AccountsOwnedProfileEmailPutRequest {
    ChangeAccountOwnedEmailRq: ChangeAccountOwnedEmailRq;
}

export interface ChangeAccountOwnedPasswordV1AccountsOwnedProfilePasswordPutRequest {
    ChangeAccountOwnedPasswordRq: ChangeAccountOwnedPasswordRq;
}

export interface ChangeAccountOwnedUsernameV1AccountsOwnedProfileUsernamePutRequest {
    ChangeAccountOwnedUsernameRq: ChangeAccountOwnedUsernameRq;
}

export interface ManageFavoriteCocktailsV1AccountsOwnedProfileCocktailsFavoritesPutRequest {
    ManageFavoriteCocktailsRq: ManageFavoriteCocktailsRq;
}

export interface RateCocktailV1AccountsOwnedProfileCocktailsRatingsPostRequest {
    RateCocktailRq: RateCocktailRq;
}

export interface SendCocktailRecommendationV1AccountsOwnedProfileCocktailsRecommendationsPostRequest {
    CocktailRecommendationRq: CocktailRecommendationRq;
}

export interface UpdateAccountOwnedAccessibilitySettingsV1AccountsOwnedProfileAccessibilityPutRequest {
    UpdateAccountOwnedAccessibilitySettingsRq: UpdateAccountOwnedAccessibilitySettingsRq;
}

export interface UpdateAccountOwnedNotificationSettingsV1AccountsOwnedProfileNotificationsPutRequest {
    UpdateAccountOwnedNotificationSettingsRq: UpdateAccountOwnedNotificationSettingsRq;
}

export interface UpdateAccountOwnedProfileV1AccountsOwnedProfilePutRequest {
    UpdateAccountOwnedProfileRq: UpdateAccountOwnedProfileRq;
}

export interface UploadProfileImageV1AccountsOwnedProfileImagePostRequest {
    file: Blob;
}

/**
 * AccountsApi - interface
 * 
 * @export
 * @interface AccountsApiInterface
 */
export interface AccountsApiInterface {
    /**
     * Updates the account profile email address for the user represented within the authenticated bearer token
     * @summary Change Account Owned Email
     * @param {ChangeAccountOwnedEmailRq} ChangeAccountOwnedEmailRq 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof AccountsApiInterface
     */
    changeAccountOwnedEmailV1AccountsOwnedProfileEmailPutRaw(requestParameters: ChangeAccountOwnedEmailV1AccountsOwnedProfileEmailPutRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<AccountOwnedProfileRs>>;

    /**
     * Updates the account profile email address for the user represented within the authenticated bearer token
     * Change Account Owned Email
     */
    changeAccountOwnedEmailV1AccountsOwnedProfileEmailPut(requestParameters: ChangeAccountOwnedEmailV1AccountsOwnedProfileEmailPutRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<AccountOwnedProfileRs>;

    /**
     * Initiates the change password authentication flow for the user represented within the authenticated bearer token
     * @summary Change Account Owned Password
     * @param {ChangeAccountOwnedPasswordRq} ChangeAccountOwnedPasswordRq 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof AccountsApiInterface
     */
    changeAccountOwnedPasswordV1AccountsOwnedProfilePasswordPutRaw(requestParameters: ChangeAccountOwnedPasswordV1AccountsOwnedProfilePasswordPutRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<any>>;

    /**
     * Initiates the change password authentication flow for the user represented within the authenticated bearer token
     * Change Account Owned Password
     */
    changeAccountOwnedPasswordV1AccountsOwnedProfilePasswordPut(requestParameters: ChangeAccountOwnedPasswordV1AccountsOwnedProfilePasswordPutRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<any | null | undefined >;

    /**
     * Initiates the change username authentication flow for the user represented within the authenticated bearer token
     * @summary Change Account Owned Username
     * @param {ChangeAccountOwnedUsernameRq} ChangeAccountOwnedUsernameRq 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof AccountsApiInterface
     */
    changeAccountOwnedUsernameV1AccountsOwnedProfileUsernamePutRaw(requestParameters: ChangeAccountOwnedUsernameV1AccountsOwnedProfileUsernamePutRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<any>>;

    /**
     * Initiates the change username authentication flow for the user represented within the authenticated bearer token
     * Change Account Owned Username
     */
    changeAccountOwnedUsernameV1AccountsOwnedProfileUsernamePut(requestParameters: ChangeAccountOwnedUsernameV1AccountsOwnedProfileUsernamePutRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<any | null | undefined >;

    /**
     * Gets the account profile for the user represented within the authenticated bearer token
     * @summary Get Account Owned Profile
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof AccountsApiInterface
     */
    getAccountOwnedProfileV1AccountsOwnedProfileGetRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<AccountOwnedProfileRs>>;

    /**
     * Gets the account profile for the user represented within the authenticated bearer token
     * Get Account Owned Profile
     */
    getAccountOwnedProfileV1AccountsOwnedProfileGet(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<AccountOwnedProfileRs>;

    /**
     * Gets the account cocktail ratings for the account profile user represented within the authenticated bearer token
     * @summary Get Cocktail Ratings
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof AccountsApiInterface
     */
    getCocktailRatingsV1AccountsOwnedProfileCocktailsRatingsGetRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<AccountCocktailRatingsRs>>;

    /**
     * Gets the account cocktail ratings for the account profile user represented within the authenticated bearer token
     * Get Cocktail Ratings
     */
    getCocktailRatingsV1AccountsOwnedProfileCocktailsRatingsGet(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<AccountCocktailRatingsRs>;

    /**
     * Logs in the account profile for the user represented within the authenticated bearer token
     * @summary Login Account Owned Profile
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof AccountsApiInterface
     */
    loginAccountOwnedProfileV1AccountsOwnedProfilePostRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<AccountOwnedProfileRs>>;

    /**
     * Logs in the account profile for the user represented within the authenticated bearer token
     * Login Account Owned Profile
     */
    loginAccountOwnedProfileV1AccountsOwnedProfilePost(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<AccountOwnedProfileRs>;

    /**
     * Manages the account profile favorite cocktails list for the user represented within the authenticated bearer token
     * @summary Manage Favorite Cocktails
     * @param {ManageFavoriteCocktailsRq} ManageFavoriteCocktailsRq 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof AccountsApiInterface
     */
    manageFavoriteCocktailsV1AccountsOwnedProfileCocktailsFavoritesPutRaw(requestParameters: ManageFavoriteCocktailsV1AccountsOwnedProfileCocktailsFavoritesPutRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<AccountOwnedProfileRs>>;

    /**
     * Manages the account profile favorite cocktails list for the user represented within the authenticated bearer token
     * Manage Favorite Cocktails
     */
    manageFavoriteCocktailsV1AccountsOwnedProfileCocktailsFavoritesPut(requestParameters: ManageFavoriteCocktailsV1AccountsOwnedProfileCocktailsFavoritesPutRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<AccountOwnedProfileRs>;

    /**
     * Rates a cocktail for the account profile user represented within the authenticated bearer token
     * @summary Rate Cocktail
     * @param {RateCocktailRq} RateCocktailRq 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof AccountsApiInterface
     */
    rateCocktailV1AccountsOwnedProfileCocktailsRatingsPostRaw(requestParameters: RateCocktailV1AccountsOwnedProfileCocktailsRatingsPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<any>>;

    /**
     * Rates a cocktail for the account profile user represented within the authenticated bearer token
     * Rate Cocktail
     */
    rateCocktailV1AccountsOwnedProfileCocktailsRatingsPost(requestParameters: RateCocktailV1AccountsOwnedProfileCocktailsRatingsPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<any>;

    /**
     * Sends a cocktail recommendation for review
     * @summary Send Cocktail Recommendation
     * @param {CocktailRecommendationRq} CocktailRecommendationRq 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof AccountsApiInterface
     */
    sendCocktailRecommendationV1AccountsOwnedProfileCocktailsRecommendationsPostRaw(requestParameters: SendCocktailRecommendationV1AccountsOwnedProfileCocktailsRecommendationsPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<any>>;

    /**
     * Sends a cocktail recommendation for review
     * Send Cocktail Recommendation
     */
    sendCocktailRecommendationV1AccountsOwnedProfileCocktailsRecommendationsPost(requestParameters: SendCocktailRecommendationV1AccountsOwnedProfileCocktailsRecommendationsPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<any | null | undefined >;

    /**
     * Updates the account profile accessibility settings for the user represented within the authenticated bearer token
     * @summary Update Account Owned Accessibility Settings
     * @param {UpdateAccountOwnedAccessibilitySettingsRq} UpdateAccountOwnedAccessibilitySettingsRq 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof AccountsApiInterface
     */
    updateAccountOwnedAccessibilitySettingsV1AccountsOwnedProfileAccessibilityPutRaw(requestParameters: UpdateAccountOwnedAccessibilitySettingsV1AccountsOwnedProfileAccessibilityPutRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<AccountOwnedProfileRs>>;

    /**
     * Updates the account profile accessibility settings for the user represented within the authenticated bearer token
     * Update Account Owned Accessibility Settings
     */
    updateAccountOwnedAccessibilitySettingsV1AccountsOwnedProfileAccessibilityPut(requestParameters: UpdateAccountOwnedAccessibilitySettingsV1AccountsOwnedProfileAccessibilityPutRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<AccountOwnedProfileRs>;

    /**
     * Updates the account profile notifications settings for the user represented within the authenticated bearer token
     * @summary Update Account Owned Notification Settings
     * @param {UpdateAccountOwnedNotificationSettingsRq} UpdateAccountOwnedNotificationSettingsRq 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof AccountsApiInterface
     */
    updateAccountOwnedNotificationSettingsV1AccountsOwnedProfileNotificationsPutRaw(requestParameters: UpdateAccountOwnedNotificationSettingsV1AccountsOwnedProfileNotificationsPutRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<AccountOwnedProfileRs>>;

    /**
     * Updates the account profile notifications settings for the user represented within the authenticated bearer token
     * Update Account Owned Notification Settings
     */
    updateAccountOwnedNotificationSettingsV1AccountsOwnedProfileNotificationsPut(requestParameters: UpdateAccountOwnedNotificationSettingsV1AccountsOwnedProfileNotificationsPutRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<AccountOwnedProfileRs>;

    /**
     * Updates the account profile for the user represented within the authenticated bearer token
     * @summary Update Account Owned Profile
     * @param {UpdateAccountOwnedProfileRq} UpdateAccountOwnedProfileRq 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof AccountsApiInterface
     */
    updateAccountOwnedProfileV1AccountsOwnedProfilePutRaw(requestParameters: UpdateAccountOwnedProfileV1AccountsOwnedProfilePutRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<AccountOwnedProfileRs>>;

    /**
     * Updates the account profile for the user represented within the authenticated bearer token
     * Update Account Owned Profile
     */
    updateAccountOwnedProfileV1AccountsOwnedProfilePut(requestParameters: UpdateAccountOwnedProfileV1AccountsOwnedProfilePutRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<AccountOwnedProfileRs>;

    /**
     * Uploads an account profile image for the user represented within the authenticated bearer token
     * @summary Upload Profile Image
     * @param {Blob} file The profile image file to upload
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof AccountsApiInterface
     */
    uploadProfileImageV1AccountsOwnedProfileImagePostRaw(requestParameters: UploadProfileImageV1AccountsOwnedProfileImagePostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<any>>;

    /**
     * Uploads an account profile image for the user represented within the authenticated bearer token
     * Upload Profile Image
     */
    uploadProfileImageV1AccountsOwnedProfileImagePost(requestParameters: UploadProfileImageV1AccountsOwnedProfileImagePostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<any>;

}

/**
 * 
 */
export class AccountsApi extends runtime.BaseAPI implements AccountsApiInterface {

    /**
     * Updates the account profile email address for the user represented within the authenticated bearer token
     * Change Account Owned Email
     */
    async changeAccountOwnedEmailV1AccountsOwnedProfileEmailPutRaw(requestParameters: ChangeAccountOwnedEmailV1AccountsOwnedProfileEmailPutRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<AccountOwnedProfileRs>> {
        if (requestParameters['ChangeAccountOwnedEmailRq'] == null) {
            throw new runtime.RequiredError(
                'ChangeAccountOwnedEmailRq',
                'Required parameter "ChangeAccountOwnedEmailRq" was null or undefined when calling changeAccountOwnedEmailV1AccountsOwnedProfileEmailPut().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/v1/accounts/owned/profile/email`;

        const response = await this.request({
            path: urlPath,
            method: 'PUT',
            headers: headerParameters,
            query: queryParameters,
            body: ChangeAccountOwnedEmailRqToJSON(requestParameters['ChangeAccountOwnedEmailRq']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => AccountOwnedProfileRsFromJSON(jsonValue));
    }

    /**
     * Updates the account profile email address for the user represented within the authenticated bearer token
     * Change Account Owned Email
     */
    async changeAccountOwnedEmailV1AccountsOwnedProfileEmailPut(requestParameters: ChangeAccountOwnedEmailV1AccountsOwnedProfileEmailPutRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<AccountOwnedProfileRs> {
        const response = await this.changeAccountOwnedEmailV1AccountsOwnedProfileEmailPutRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Initiates the change password authentication flow for the user represented within the authenticated bearer token
     * Change Account Owned Password
     */
    async changeAccountOwnedPasswordV1AccountsOwnedProfilePasswordPutRaw(requestParameters: ChangeAccountOwnedPasswordV1AccountsOwnedProfilePasswordPutRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<any>> {
        if (requestParameters['ChangeAccountOwnedPasswordRq'] == null) {
            throw new runtime.RequiredError(
                'ChangeAccountOwnedPasswordRq',
                'Required parameter "ChangeAccountOwnedPasswordRq" was null or undefined when calling changeAccountOwnedPasswordV1AccountsOwnedProfilePasswordPut().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/v1/accounts/owned/profile/password`;

        const response = await this.request({
            path: urlPath,
            method: 'PUT',
            headers: headerParameters,
            query: queryParameters,
            body: ChangeAccountOwnedPasswordRqToJSON(requestParameters['ChangeAccountOwnedPasswordRq']),
        }, initOverrides);

        if (this.isJsonMime(response.headers.get('content-type'))) {
            return new runtime.JSONApiResponse<any>(response);
        } else {
            return new runtime.TextApiResponse(response) as any;
        }
    }

    /**
     * Initiates the change password authentication flow for the user represented within the authenticated bearer token
     * Change Account Owned Password
     */
    async changeAccountOwnedPasswordV1AccountsOwnedProfilePasswordPut(requestParameters: ChangeAccountOwnedPasswordV1AccountsOwnedProfilePasswordPutRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<any | null | undefined > {
        const response = await this.changeAccountOwnedPasswordV1AccountsOwnedProfilePasswordPutRaw(requestParameters, initOverrides);
        switch (response.raw.status) {
            case 200:
                return await response.value();
            case 204:
                return null;
            default:
                return await response.value();
        }
    }

    /**
     * Initiates the change username authentication flow for the user represented within the authenticated bearer token
     * Change Account Owned Username
     */
    async changeAccountOwnedUsernameV1AccountsOwnedProfileUsernamePutRaw(requestParameters: ChangeAccountOwnedUsernameV1AccountsOwnedProfileUsernamePutRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<any>> {
        if (requestParameters['ChangeAccountOwnedUsernameRq'] == null) {
            throw new runtime.RequiredError(
                'ChangeAccountOwnedUsernameRq',
                'Required parameter "ChangeAccountOwnedUsernameRq" was null or undefined when calling changeAccountOwnedUsernameV1AccountsOwnedProfileUsernamePut().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/v1/accounts/owned/profile/username`;

        const response = await this.request({
            path: urlPath,
            method: 'PUT',
            headers: headerParameters,
            query: queryParameters,
            body: ChangeAccountOwnedUsernameRqToJSON(requestParameters['ChangeAccountOwnedUsernameRq']),
        }, initOverrides);

        if (this.isJsonMime(response.headers.get('content-type'))) {
            return new runtime.JSONApiResponse<any>(response);
        } else {
            return new runtime.TextApiResponse(response) as any;
        }
    }

    /**
     * Initiates the change username authentication flow for the user represented within the authenticated bearer token
     * Change Account Owned Username
     */
    async changeAccountOwnedUsernameV1AccountsOwnedProfileUsernamePut(requestParameters: ChangeAccountOwnedUsernameV1AccountsOwnedProfileUsernamePutRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<any | null | undefined > {
        const response = await this.changeAccountOwnedUsernameV1AccountsOwnedProfileUsernamePutRaw(requestParameters, initOverrides);
        switch (response.raw.status) {
            case 200:
                return await response.value();
            case 204:
                return null;
            default:
                return await response.value();
        }
    }

    /**
     * Gets the account profile for the user represented within the authenticated bearer token
     * Get Account Owned Profile
     */
    async getAccountOwnedProfileV1AccountsOwnedProfileGetRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<AccountOwnedProfileRs>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/v1/accounts/owned/profile`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => AccountOwnedProfileRsFromJSON(jsonValue));
    }

    /**
     * Gets the account profile for the user represented within the authenticated bearer token
     * Get Account Owned Profile
     */
    async getAccountOwnedProfileV1AccountsOwnedProfileGet(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<AccountOwnedProfileRs> {
        const response = await this.getAccountOwnedProfileV1AccountsOwnedProfileGetRaw(initOverrides);
        return await response.value();
    }

    /**
     * Gets the account cocktail ratings for the account profile user represented within the authenticated bearer token
     * Get Cocktail Ratings
     */
    async getCocktailRatingsV1AccountsOwnedProfileCocktailsRatingsGetRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<AccountCocktailRatingsRs>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/v1/accounts/owned/profile/cocktails/ratings`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => AccountCocktailRatingsRsFromJSON(jsonValue));
    }

    /**
     * Gets the account cocktail ratings for the account profile user represented within the authenticated bearer token
     * Get Cocktail Ratings
     */
    async getCocktailRatingsV1AccountsOwnedProfileCocktailsRatingsGet(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<AccountCocktailRatingsRs> {
        const response = await this.getCocktailRatingsV1AccountsOwnedProfileCocktailsRatingsGetRaw(initOverrides);
        return await response.value();
    }

    /**
     * Logs in the account profile for the user represented within the authenticated bearer token
     * Login Account Owned Profile
     */
    async loginAccountOwnedProfileV1AccountsOwnedProfilePostRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<AccountOwnedProfileRs>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/v1/accounts/owned/profile`;

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => AccountOwnedProfileRsFromJSON(jsonValue));
    }

    /**
     * Logs in the account profile for the user represented within the authenticated bearer token
     * Login Account Owned Profile
     */
    async loginAccountOwnedProfileV1AccountsOwnedProfilePost(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<AccountOwnedProfileRs> {
        const response = await this.loginAccountOwnedProfileV1AccountsOwnedProfilePostRaw(initOverrides);
        return await response.value();
    }

    /**
     * Manages the account profile favorite cocktails list for the user represented within the authenticated bearer token
     * Manage Favorite Cocktails
     */
    async manageFavoriteCocktailsV1AccountsOwnedProfileCocktailsFavoritesPutRaw(requestParameters: ManageFavoriteCocktailsV1AccountsOwnedProfileCocktailsFavoritesPutRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<AccountOwnedProfileRs>> {
        if (requestParameters['ManageFavoriteCocktailsRq'] == null) {
            throw new runtime.RequiredError(
                'ManageFavoriteCocktailsRq',
                'Required parameter "ManageFavoriteCocktailsRq" was null or undefined when calling manageFavoriteCocktailsV1AccountsOwnedProfileCocktailsFavoritesPut().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/v1/accounts/owned/profile/cocktails/favorites`;

        const response = await this.request({
            path: urlPath,
            method: 'PUT',
            headers: headerParameters,
            query: queryParameters,
            body: ManageFavoriteCocktailsRqToJSON(requestParameters['ManageFavoriteCocktailsRq']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => AccountOwnedProfileRsFromJSON(jsonValue));
    }

    /**
     * Manages the account profile favorite cocktails list for the user represented within the authenticated bearer token
     * Manage Favorite Cocktails
     */
    async manageFavoriteCocktailsV1AccountsOwnedProfileCocktailsFavoritesPut(requestParameters: ManageFavoriteCocktailsV1AccountsOwnedProfileCocktailsFavoritesPutRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<AccountOwnedProfileRs> {
        const response = await this.manageFavoriteCocktailsV1AccountsOwnedProfileCocktailsFavoritesPutRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Rates a cocktail for the account profile user represented within the authenticated bearer token
     * Rate Cocktail
     */
    async rateCocktailV1AccountsOwnedProfileCocktailsRatingsPostRaw(requestParameters: RateCocktailV1AccountsOwnedProfileCocktailsRatingsPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<any>> {
        if (requestParameters['RateCocktailRq'] == null) {
            throw new runtime.RequiredError(
                'RateCocktailRq',
                'Required parameter "RateCocktailRq" was null or undefined when calling rateCocktailV1AccountsOwnedProfileCocktailsRatingsPost().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/v1/accounts/owned/profile/cocktails/ratings`;

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: RateCocktailRqToJSON(requestParameters['RateCocktailRq']),
        }, initOverrides);

        if (this.isJsonMime(response.headers.get('content-type'))) {
            return new runtime.JSONApiResponse<any>(response);
        } else {
            return new runtime.TextApiResponse(response) as any;
        }
    }

    /**
     * Rates a cocktail for the account profile user represented within the authenticated bearer token
     * Rate Cocktail
     */
    async rateCocktailV1AccountsOwnedProfileCocktailsRatingsPost(requestParameters: RateCocktailV1AccountsOwnedProfileCocktailsRatingsPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<any> {
        const response = await this.rateCocktailV1AccountsOwnedProfileCocktailsRatingsPostRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Sends a cocktail recommendation for review
     * Send Cocktail Recommendation
     */
    async sendCocktailRecommendationV1AccountsOwnedProfileCocktailsRecommendationsPostRaw(requestParameters: SendCocktailRecommendationV1AccountsOwnedProfileCocktailsRecommendationsPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<any>> {
        if (requestParameters['CocktailRecommendationRq'] == null) {
            throw new runtime.RequiredError(
                'CocktailRecommendationRq',
                'Required parameter "CocktailRecommendationRq" was null or undefined when calling sendCocktailRecommendationV1AccountsOwnedProfileCocktailsRecommendationsPost().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/v1/accounts/owned/profile/cocktails/recommendations`;

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: CocktailRecommendationRqToJSON(requestParameters['CocktailRecommendationRq']),
        }, initOverrides);

        if (this.isJsonMime(response.headers.get('content-type'))) {
            return new runtime.JSONApiResponse<any>(response);
        } else {
            return new runtime.TextApiResponse(response) as any;
        }
    }

    /**
     * Sends a cocktail recommendation for review
     * Send Cocktail Recommendation
     */
    async sendCocktailRecommendationV1AccountsOwnedProfileCocktailsRecommendationsPost(requestParameters: SendCocktailRecommendationV1AccountsOwnedProfileCocktailsRecommendationsPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<any | null | undefined > {
        const response = await this.sendCocktailRecommendationV1AccountsOwnedProfileCocktailsRecommendationsPostRaw(requestParameters, initOverrides);
        switch (response.raw.status) {
            case 200:
                return await response.value();
            case 202:
                return null;
            default:
                return await response.value();
        }
    }

    /**
     * Updates the account profile accessibility settings for the user represented within the authenticated bearer token
     * Update Account Owned Accessibility Settings
     */
    async updateAccountOwnedAccessibilitySettingsV1AccountsOwnedProfileAccessibilityPutRaw(requestParameters: UpdateAccountOwnedAccessibilitySettingsV1AccountsOwnedProfileAccessibilityPutRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<AccountOwnedProfileRs>> {
        if (requestParameters['UpdateAccountOwnedAccessibilitySettingsRq'] == null) {
            throw new runtime.RequiredError(
                'UpdateAccountOwnedAccessibilitySettingsRq',
                'Required parameter "UpdateAccountOwnedAccessibilitySettingsRq" was null or undefined when calling updateAccountOwnedAccessibilitySettingsV1AccountsOwnedProfileAccessibilityPut().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/v1/accounts/owned/profile/accessibility`;

        const response = await this.request({
            path: urlPath,
            method: 'PUT',
            headers: headerParameters,
            query: queryParameters,
            body: UpdateAccountOwnedAccessibilitySettingsRqToJSON(requestParameters['UpdateAccountOwnedAccessibilitySettingsRq']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => AccountOwnedProfileRsFromJSON(jsonValue));
    }

    /**
     * Updates the account profile accessibility settings for the user represented within the authenticated bearer token
     * Update Account Owned Accessibility Settings
     */
    async updateAccountOwnedAccessibilitySettingsV1AccountsOwnedProfileAccessibilityPut(requestParameters: UpdateAccountOwnedAccessibilitySettingsV1AccountsOwnedProfileAccessibilityPutRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<AccountOwnedProfileRs> {
        const response = await this.updateAccountOwnedAccessibilitySettingsV1AccountsOwnedProfileAccessibilityPutRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Updates the account profile notifications settings for the user represented within the authenticated bearer token
     * Update Account Owned Notification Settings
     */
    async updateAccountOwnedNotificationSettingsV1AccountsOwnedProfileNotificationsPutRaw(requestParameters: UpdateAccountOwnedNotificationSettingsV1AccountsOwnedProfileNotificationsPutRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<AccountOwnedProfileRs>> {
        if (requestParameters['UpdateAccountOwnedNotificationSettingsRq'] == null) {
            throw new runtime.RequiredError(
                'UpdateAccountOwnedNotificationSettingsRq',
                'Required parameter "UpdateAccountOwnedNotificationSettingsRq" was null or undefined when calling updateAccountOwnedNotificationSettingsV1AccountsOwnedProfileNotificationsPut().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/v1/accounts/owned/profile/notifications`;

        const response = await this.request({
            path: urlPath,
            method: 'PUT',
            headers: headerParameters,
            query: queryParameters,
            body: UpdateAccountOwnedNotificationSettingsRqToJSON(requestParameters['UpdateAccountOwnedNotificationSettingsRq']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => AccountOwnedProfileRsFromJSON(jsonValue));
    }

    /**
     * Updates the account profile notifications settings for the user represented within the authenticated bearer token
     * Update Account Owned Notification Settings
     */
    async updateAccountOwnedNotificationSettingsV1AccountsOwnedProfileNotificationsPut(requestParameters: UpdateAccountOwnedNotificationSettingsV1AccountsOwnedProfileNotificationsPutRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<AccountOwnedProfileRs> {
        const response = await this.updateAccountOwnedNotificationSettingsV1AccountsOwnedProfileNotificationsPutRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Updates the account profile for the user represented within the authenticated bearer token
     * Update Account Owned Profile
     */
    async updateAccountOwnedProfileV1AccountsOwnedProfilePutRaw(requestParameters: UpdateAccountOwnedProfileV1AccountsOwnedProfilePutRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<AccountOwnedProfileRs>> {
        if (requestParameters['UpdateAccountOwnedProfileRq'] == null) {
            throw new runtime.RequiredError(
                'UpdateAccountOwnedProfileRq',
                'Required parameter "UpdateAccountOwnedProfileRq" was null or undefined when calling updateAccountOwnedProfileV1AccountsOwnedProfilePut().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/v1/accounts/owned/profile`;

        const response = await this.request({
            path: urlPath,
            method: 'PUT',
            headers: headerParameters,
            query: queryParameters,
            body: UpdateAccountOwnedProfileRqToJSON(requestParameters['UpdateAccountOwnedProfileRq']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => AccountOwnedProfileRsFromJSON(jsonValue));
    }

    /**
     * Updates the account profile for the user represented within the authenticated bearer token
     * Update Account Owned Profile
     */
    async updateAccountOwnedProfileV1AccountsOwnedProfilePut(requestParameters: UpdateAccountOwnedProfileV1AccountsOwnedProfilePutRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<AccountOwnedProfileRs> {
        const response = await this.updateAccountOwnedProfileV1AccountsOwnedProfilePutRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Uploads an account profile image for the user represented within the authenticated bearer token
     * Upload Profile Image
     */
    async uploadProfileImageV1AccountsOwnedProfileImagePostRaw(requestParameters: UploadProfileImageV1AccountsOwnedProfileImagePostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<any>> {
        if (requestParameters['file'] == null) {
            throw new runtime.RequiredError(
                'file',
                'Required parameter "file" was null or undefined when calling uploadProfileImageV1AccountsOwnedProfileImagePost().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const consumes: runtime.Consume[] = [
            { contentType: 'multipart/form-data' },
        ];
        // @ts-ignore: canConsumeForm may be unused
        const canConsumeForm = runtime.canConsumeForm(consumes);

        let formParams: { append(param: string, value: any): any };
        let useForm = false;
        // use FormData to transmit files using content-type "multipart/form-data"
        useForm = canConsumeForm;
        if (useForm) {
            formParams = new FormData();
        } else {
            formParams = new URLSearchParams();
        }

        if (requestParameters['file'] != null) {
            formParams.append('file', requestParameters['file'] as any);
        }


        let urlPath = `/v1/accounts/owned/profile/image`;

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: formParams,
        }, initOverrides);

        if (this.isJsonMime(response.headers.get('content-type'))) {
            return new runtime.JSONApiResponse<any>(response);
        } else {
            return new runtime.TextApiResponse(response) as any;
        }
    }

    /**
     * Uploads an account profile image for the user represented within the authenticated bearer token
     * Upload Profile Image
     */
    async uploadProfileImageV1AccountsOwnedProfileImagePost(requestParameters: UploadProfileImageV1AccountsOwnedProfileImagePostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<any> {
        const response = await this.uploadProfileImageV1AccountsOwnedProfileImagePostRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
