/* tslint:disable */
/* eslint-disable */
/**
 * Cezzi\'s Cocktails AI Search API
 * An AI-powered cocktail search API using semantic search and embeddings.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  CocktailEmbeddingRq,
  ProblemDetails,
} from '../models/index';
import {
    CocktailEmbeddingRqFromJSON,
    CocktailEmbeddingRqToJSON,
    ProblemDetailsFromJSON,
    ProblemDetailsToJSON,
} from '../models/index';

export interface PutV1CocktailsEmbeddingsRequest {
    X_Key: string;
    CocktailEmbeddingRq: CocktailEmbeddingRq;
}

/**
 * EmbeddingsApi - interface
 * 
 * @export
 * @interface EmbeddingsApiInterface
 */
export interface EmbeddingsApiInterface {
    /**
     * Performs a semantic search for cocktails based on a free text query.
     * @summary Embed
     * @param {string} X_Key The API gateway subscription key
     * @param {CocktailEmbeddingRq} CocktailEmbeddingRq 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof EmbeddingsApiInterface
     */
    putV1CocktailsEmbeddingsRaw(requestParameters: PutV1CocktailsEmbeddingsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>>;

    /**
     * Performs a semantic search for cocktails based on a free text query.
     * Embed
     */
    putV1CocktailsEmbeddings(requestParameters: PutV1CocktailsEmbeddingsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void>;

}

/**
 * 
 */
export class EmbeddingsApi extends runtime.BaseAPI implements EmbeddingsApiInterface {

    /**
     * Performs a semantic search for cocktails based on a free text query.
     * Embed
     */
    async putV1CocktailsEmbeddingsRaw(requestParameters: PutV1CocktailsEmbeddingsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        if (requestParameters['X_Key'] == null) {
            throw new runtime.RequiredError(
                'X_Key',
                'Required parameter "X_Key" was null or undefined when calling putV1CocktailsEmbeddings().'
            );
        }

        if (requestParameters['CocktailEmbeddingRq'] == null) {
            throw new runtime.RequiredError(
                'CocktailEmbeddingRq',
                'Required parameter "CocktailEmbeddingRq" was null or undefined when calling putV1CocktailsEmbeddings().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (requestParameters['X_Key'] != null) {
            headerParameters['X-Key'] = String(requestParameters['X_Key']);
        }

        if (this.configuration && this.configuration.accessToken) {
            // oauth required
            headerParameters["Authorization"] = await this.configuration.accessToken("auth0", ["write:embeddings"]);
        }


        let urlPath = `/v1/cocktails/embeddings`;

        const response = await this.request({
            path: urlPath,
            method: 'PUT',
            headers: headerParameters,
            query: queryParameters,
            body: CocktailEmbeddingRqToJSON(requestParameters['CocktailEmbeddingRq']),
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Performs a semantic search for cocktails based on a free text query.
     * Embed
     */
    async putV1CocktailsEmbeddings(requestParameters: PutV1CocktailsEmbeddingsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.putV1CocktailsEmbeddingsRaw(requestParameters, initOverrides);
    }

}
