/* tslint:disable */
/* eslint-disable */
/**
 * Cezzi\'s Cocktails Accounts Api
 * An API for managing user accounts in Cezzi\'s Cocktails application.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * An owned account profile address.
 * @export
 * @interface AccountAddressModel
 */
export interface AccountAddressModel {
    /**
     * The primary street address.
     * @type {string}
     * @memberof AccountAddressModel
     */
    addressLine1: string;
    /**
     * The secondary street address building sub divider
     * @type {string}
     * @memberof AccountAddressModel
     */
    addressLine2: string;
    /**
     * The city the address is within
     * @type {string}
     * @memberof AccountAddressModel
     */
    city: string;
    /**
     * The state or province
     * @type {string}
     * @memberof AccountAddressModel
     */
    region: string;
    /**
     * The state or province divider such as county
     * @type {string}
     * @memberof AccountAddressModel
     */
    subRegion: string;
    /**
     * The postal or zip code
     * @type {string}
     * @memberof AccountAddressModel
     */
    postalCode: string;
    /**
     * The country
     * @type {string}
     * @memberof AccountAddressModel
     */
    country: string;
}

/**
 * Check if a given object implements the AccountAddressModel interface.
 */
export function instanceOfAccountAddressModel(value: object): value is AccountAddressModel {
    if (!('addressLine1' in value) || value['addressLine1'] === undefined) return false;
    if (!('addressLine2' in value) || value['addressLine2'] === undefined) return false;
    if (!('city' in value) || value['city'] === undefined) return false;
    if (!('region' in value) || value['region'] === undefined) return false;
    if (!('subRegion' in value) || value['subRegion'] === undefined) return false;
    if (!('postalCode' in value) || value['postalCode'] === undefined) return false;
    if (!('country' in value) || value['country'] === undefined) return false;
    return true;
}

export function AccountAddressModelFromJSON(json: any): AccountAddressModel {
    return AccountAddressModelFromJSONTyped(json, false);
}

export function AccountAddressModelFromJSONTyped(json: any, ignoreDiscriminator: boolean): AccountAddressModel {
    if (json == null) {
        return json;
    }
    return {
        
        'addressLine1': json['addressLine1'],
        'addressLine2': json['addressLine2'],
        'city': json['city'],
        'region': json['region'],
        'subRegion': json['subRegion'],
        'postalCode': json['postalCode'],
        'country': json['country'],
    };
}

export function AccountAddressModelToJSON(json: any): AccountAddressModel {
    return AccountAddressModelToJSONTyped(json, false);
}

export function AccountAddressModelToJSONTyped(value?: AccountAddressModel | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'addressLine1': value['addressLine1'],
        'addressLine2': value['addressLine2'],
        'city': value['city'],
        'region': value['region'],
        'subRegion': value['subRegion'],
        'postalCode': value['postalCode'],
        'country': value['country'],
    };
}

