/* tslint:disable */
/* eslint-disable */
/**
 * Cezzi\'s Cocktails Accounts Api
 * An API for managing user accounts in Cezzi\'s Cocktails application.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { AccountAccessibilitySettingsModel } from './accountAccessibilitySettingsModel';
import {
    AccountAccessibilitySettingsModelFromJSON,
    AccountAccessibilitySettingsModelFromJSONTyped,
    AccountAccessibilitySettingsModelToJSON,
    AccountAccessibilitySettingsModelToJSONTyped,
} from './accountAccessibilitySettingsModel';
import type { AccountNotificationSettingsModel } from './accountNotificationSettingsModel';
import {
    AccountNotificationSettingsModelFromJSON,
    AccountNotificationSettingsModelFromJSONTyped,
    AccountNotificationSettingsModelToJSON,
    AccountNotificationSettingsModelToJSONTyped,
} from './accountNotificationSettingsModel';
import type { AccountAddressModel } from './accountAddressModel';
import {
    AccountAddressModelFromJSON,
    AccountAddressModelFromJSONTyped,
    AccountAddressModelToJSON,
    AccountAddressModelToJSONTyped,
} from './accountAddressModel';

/**
 * The owned account profile response.
 * @export
 * @interface AccountOwnedProfileRs
 */
export interface AccountOwnedProfileRs {
    /**
     * The federated subject identifier for the account
     * @type {string}
     * @memberof AccountOwnedProfileRs
     */
    subjectId: string;
    /**
     * The login email address for the account
     * @type {string}
     * @memberof AccountOwnedProfileRs
     */
    loginEmail: string;
    /**
     * The email address for the account
     * @type {string}
     * @memberof AccountOwnedProfileRs
     */
    email: string;
    /**
     * The given name on the account
     * @type {string}
     * @memberof AccountOwnedProfileRs
     */
    givenName?: string | null;
    /**
     * The family name on the account
     * @type {string}
     * @memberof AccountOwnedProfileRs
     */
    familyName?: string | null;
    /**
     * The avatar image uri for the account
     * @type {string}
     * @memberof AccountOwnedProfileRs
     */
    avatarUri?: string | null;
    /**
     * The optional primary address listed with the account
     * @type {AccountAddressModel}
     * @memberof AccountOwnedProfileRs
     */
    primaryAddress?: AccountAddressModel | null;
    /**
     * The display name for the account visible to other users
     * @type {string}
     * @memberof AccountOwnedProfileRs
     */
    displayName?: string | null;
    /**
     * The accessibility settings for the account
     * @type {AccountAccessibilitySettingsModel}
     * @memberof AccountOwnedProfileRs
     */
    accessibility?: AccountAccessibilitySettingsModel | null;
    /**
     * The list of favorite cocktails
     * @type {Array<string>}
     * @memberof AccountOwnedProfileRs
     */
    favoriteCocktails?: Array<string> | null;
    /**
     * The notification settings for the account
     * @type {AccountNotificationSettingsModel}
     * @memberof AccountOwnedProfileRs
     */
    notifications?: AccountNotificationSettingsModel | null;
}

/**
 * Check if a given object implements the AccountOwnedProfileRs interface.
 */
export function instanceOfAccountOwnedProfileRs(value: object): value is AccountOwnedProfileRs {
    if (!('subjectId' in value) || value['subjectId'] === undefined) return false;
    if (!('loginEmail' in value) || value['loginEmail'] === undefined) return false;
    if (!('email' in value) || value['email'] === undefined) return false;
    return true;
}

export function AccountOwnedProfileRsFromJSON(json: any): AccountOwnedProfileRs {
    return AccountOwnedProfileRsFromJSONTyped(json, false);
}

export function AccountOwnedProfileRsFromJSONTyped(json: any, ignoreDiscriminator: boolean): AccountOwnedProfileRs {
    if (json == null) {
        return json;
    }
    return {
        
        'subjectId': json['subjectId'],
        'loginEmail': json['loginEmail'],
        'email': json['email'],
        'givenName': json['givenName'] == null ? undefined : json['givenName'],
        'familyName': json['familyName'] == null ? undefined : json['familyName'],
        'avatarUri': json['avatarUri'] == null ? undefined : json['avatarUri'],
        'primaryAddress': json['primaryAddress'] == null ? undefined : AccountAddressModelFromJSON(json['primaryAddress']),
        'displayName': json['displayName'] == null ? undefined : json['displayName'],
        'accessibility': json['accessibility'] == null ? undefined : AccountAccessibilitySettingsModelFromJSON(json['accessibility']),
        'favoriteCocktails': json['favoriteCocktails'] == null ? undefined : json['favoriteCocktails'],
        'notifications': json['notifications'] == null ? undefined : AccountNotificationSettingsModelFromJSON(json['notifications']),
    };
}

export function AccountOwnedProfileRsToJSON(json: any): AccountOwnedProfileRs {
    return AccountOwnedProfileRsToJSONTyped(json, false);
}

export function AccountOwnedProfileRsToJSONTyped(value?: AccountOwnedProfileRs | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'subjectId': value['subjectId'],
        'loginEmail': value['loginEmail'],
        'email': value['email'],
        'givenName': value['givenName'],
        'familyName': value['familyName'],
        'avatarUri': value['avatarUri'],
        'primaryAddress': AccountAddressModelToJSON(value['primaryAddress']),
        'displayName': value['displayName'],
        'accessibility': AccountAccessibilitySettingsModelToJSON(value['accessibility']),
        'favoriteCocktails': value['favoriteCocktails'],
        'notifications': AccountNotificationSettingsModelToJSON(value['notifications']),
    };
}

