/* tslint:disable */
/* eslint-disable */
/**
 * Cezzi\'s Cocktails Accounts Api
 * An API for managing user accounts in Cezzi\'s Cocktails application.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { AccountAccessibilitySettingsModel } from './accountAccessibilitySettingsModel';
import {
    AccountAccessibilitySettingsModelFromJSON,
    AccountAccessibilitySettingsModelFromJSONTyped,
    AccountAccessibilitySettingsModelToJSON,
    AccountAccessibilitySettingsModelToJSONTyped,
} from './accountAccessibilitySettingsModel';
import type { AccountNotificationSettingsModel } from './accountNotificationSettingsModel';
import {
    AccountNotificationSettingsModelFromJSON,
    AccountNotificationSettingsModelFromJSONTyped,
    AccountNotificationSettingsModelToJSON,
    AccountNotificationSettingsModelToJSONTyped,
} from './accountNotificationSettingsModel';
import type { AccountAddressModel } from './accountAddressModel';
import {
    AccountAddressModelFromJSON,
    AccountAddressModelFromJSONTyped,
    AccountAddressModelToJSON,
    AccountAddressModelToJSONTyped,
} from './accountAddressModel';

/**
 * The owned account profile response.
 * @export
 * @interface AccountOwnedProfileRs
 */
export interface AccountOwnedProfileRs {
    /**
     * The federated subject identifier for the account
     * @type {string}
     * @memberof AccountOwnedProfileRs
     */
    subject_id: string;
    /**
     * The login email address for the account
     * @type {string}
     * @memberof AccountOwnedProfileRs
     */
    login_email: string;
    /**
     * The email address for the account
     * @type {string}
     * @memberof AccountOwnedProfileRs
     */
    email: string;
    /**
     * The given name on the account
     * @type {string}
     * @memberof AccountOwnedProfileRs
     */
    given_name?: string | null;
    /**
     * The family name on the account
     * @type {string}
     * @memberof AccountOwnedProfileRs
     */
    family_name?: string | null;
    /**
     * The avatar image uri for the account
     * @type {string}
     * @memberof AccountOwnedProfileRs
     */
    avatar_uri?: string | null;
    /**
     * The optional primary address listed with the account
     * @type {AccountAddressModel}
     * @memberof AccountOwnedProfileRs
     */
    primary_address?: AccountAddressModel | null;
    /**
     * The display name for the account visible to other users
     * @type {string}
     * @memberof AccountOwnedProfileRs
     */
    display_name?: string | null;
    /**
     * The accessibility settings for the account
     * @type {AccountAccessibilitySettingsModel}
     * @memberof AccountOwnedProfileRs
     */
    accessibility?: AccountAccessibilitySettingsModel | null;
    /**
     * The list of favorite cocktails
     * @type {Array<string>}
     * @memberof AccountOwnedProfileRs
     */
    favorite_cocktails?: Array<string> | null;
    /**
     * The notification settings for the account
     * @type {AccountNotificationSettingsModel}
     * @memberof AccountOwnedProfileRs
     */
    notifications?: AccountNotificationSettingsModel | null;
}

/**
 * Check if a given object implements the AccountOwnedProfileRs interface.
 */
export function instanceOfAccountOwnedProfileRs(value: object): value is AccountOwnedProfileRs {
    if (!('subject_id' in value) || value['subject_id'] === undefined) return false;
    if (!('login_email' in value) || value['login_email'] === undefined) return false;
    if (!('email' in value) || value['email'] === undefined) return false;
    return true;
}

export function AccountOwnedProfileRsFromJSON(json: any): AccountOwnedProfileRs {
    return AccountOwnedProfileRsFromJSONTyped(json, false);
}

export function AccountOwnedProfileRsFromJSONTyped(json: any, ignoreDiscriminator: boolean): AccountOwnedProfileRs {
    if (json == null) {
        return json;
    }
    return {
        
        'subject_id': json['subject_id'],
        'login_email': json['login_email'],
        'email': json['email'],
        'given_name': json['given_name'] == null ? undefined : json['given_name'],
        'family_name': json['family_name'] == null ? undefined : json['family_name'],
        'avatar_uri': json['avatar_uri'] == null ? undefined : json['avatar_uri'],
        'primary_address': json['primary_address'] == null ? undefined : AccountAddressModelFromJSON(json['primary_address']),
        'display_name': json['display_name'] == null ? undefined : json['display_name'],
        'accessibility': json['accessibility'] == null ? undefined : AccountAccessibilitySettingsModelFromJSON(json['accessibility']),
        'favorite_cocktails': json['favorite_cocktails'] == null ? undefined : json['favorite_cocktails'],
        'notifications': json['notifications'] == null ? undefined : AccountNotificationSettingsModelFromJSON(json['notifications']),
    };
}

export function AccountOwnedProfileRsToJSON(json: any): AccountOwnedProfileRs {
    return AccountOwnedProfileRsToJSONTyped(json, false);
}

export function AccountOwnedProfileRsToJSONTyped(value?: AccountOwnedProfileRs | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'subject_id': value['subject_id'],
        'login_email': value['login_email'],
        'email': value['email'],
        'given_name': value['given_name'],
        'family_name': value['family_name'],
        'avatar_uri': value['avatar_uri'],
        'primary_address': AccountAddressModelToJSON(value['primary_address']),
        'display_name': value['display_name'],
        'accessibility': AccountAccessibilitySettingsModelToJSON(value['accessibility']),
        'favorite_cocktails': value['favorite_cocktails'],
        'notifications': AccountNotificationSettingsModelToJSON(value['notifications']),
    };
}

