/* tslint:disable */
/* eslint-disable */
/**
 * Cezzi\'s Cocktails Accounts Api
 * An API for managing user accounts in Cezzi\'s Cocktails application.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * A cocktail reference with user supplied rating.
 * @export
 * @interface AccountCocktailRatingsModel
 */
export interface AccountCocktailRatingsModel {
    /**
     * The cocktail identifier
     * @type {string}
     * @memberof AccountCocktailRatingsModel
     */
    cocktail_id: string;
    /**
     * The rating for the cocktail (1-5)
     * @type {number}
     * @memberof AccountCocktailRatingsModel
     */
    stars: number;
}

/**
 * Check if a given object implements the AccountCocktailRatingsModel interface.
 */
export function instanceOfAccountCocktailRatingsModel(value: object): value is AccountCocktailRatingsModel {
    if (!('cocktail_id' in value) || value['cocktail_id'] === undefined) return false;
    if (!('stars' in value) || value['stars'] === undefined) return false;
    return true;
}

export function AccountCocktailRatingsModelFromJSON(json: any): AccountCocktailRatingsModel {
    return AccountCocktailRatingsModelFromJSONTyped(json, false);
}

export function AccountCocktailRatingsModelFromJSONTyped(json: any, ignoreDiscriminator: boolean): AccountCocktailRatingsModel {
    if (json == null) {
        return json;
    }
    return {
        
        'cocktail_id': json['cocktail_id'],
        'stars': json['stars'],
    };
}

export function AccountCocktailRatingsModelToJSON(json: any): AccountCocktailRatingsModel {
    return AccountCocktailRatingsModelToJSONTyped(json, false);
}

export function AccountCocktailRatingsModelToJSONTyped(value?: AccountCocktailRatingsModel | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'cocktail_id': value['cocktail_id'],
        'stars': value['stars'],
    };
}

