/* tslint:disable */
/* eslint-disable */
/**
 * Cezzi\'s Cocktails Accounts Api
 * An API for managing user accounts in Cezzi\'s Cocktails application.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { AccountCocktailRatingsModel } from './accountCocktailRatingsModel';
import {
    AccountCocktailRatingsModelFromJSON,
    AccountCocktailRatingsModelFromJSONTyped,
    AccountCocktailRatingsModelToJSON,
    AccountCocktailRatingsModelToJSONTyped,
} from './accountCocktailRatingsModel';

/**
 * The cocktail ratings associated with an account.
 * @export
 * @interface AccountCocktailRatingsRs
 */
export interface AccountCocktailRatingsRs {
    /**
     * The cocktail ratings
     * @type {Array<AccountCocktailRatingsModel>}
     * @memberof AccountCocktailRatingsRs
     */
    ratings: Array<AccountCocktailRatingsModel>;
}

/**
 * Check if a given object implements the AccountCocktailRatingsRs interface.
 */
export function instanceOfAccountCocktailRatingsRs(value: object): value is AccountCocktailRatingsRs {
    if (!('ratings' in value) || value['ratings'] === undefined) return false;
    return true;
}

export function AccountCocktailRatingsRsFromJSON(json: any): AccountCocktailRatingsRs {
    return AccountCocktailRatingsRsFromJSONTyped(json, false);
}

export function AccountCocktailRatingsRsFromJSONTyped(json: any, ignoreDiscriminator: boolean): AccountCocktailRatingsRs {
    if (json == null) {
        return json;
    }
    return {
        
        'ratings': ((json['ratings'] as Array<any>).map(AccountCocktailRatingsModelFromJSON)),
    };
}

export function AccountCocktailRatingsRsToJSON(json: any): AccountCocktailRatingsRs {
    return AccountCocktailRatingsRsToJSONTyped(json, false);
}

export function AccountCocktailRatingsRsToJSONTyped(value?: AccountCocktailRatingsRs | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'ratings': ((value['ratings'] as Array<any>).map(AccountCocktailRatingsModelToJSON)),
    };
}

