/* tslint:disable */
/* eslint-disable */
/**
 * Cezzi\'s Cocktails Accounts Api
 * An API for managing user accounts in Cezzi\'s Cocktails application.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { CocktailUpdatedNotificationModel } from './cocktailUpdatedNotificationModel';
import {
    CocktailUpdatedNotificationModelFromJSON,
    CocktailUpdatedNotificationModelFromJSONTyped,
    CocktailUpdatedNotificationModelToJSON,
    CocktailUpdatedNotificationModelToJSONTyped,
} from './cocktailUpdatedNotificationModel';

/**
 * The owned account profile notification settings.
 * @export
 * @interface AccountNotificationSettingsModel
 */
export interface AccountNotificationSettingsModel {
    /**
     * 
     * @type {CocktailUpdatedNotificationModel}
     * @memberof AccountNotificationSettingsModel
     */
    on_new_cocktail_additions: CocktailUpdatedNotificationModel;
}



/**
 * Check if a given object implements the AccountNotificationSettingsModel interface.
 */
export function instanceOfAccountNotificationSettingsModel(value: object): value is AccountNotificationSettingsModel {
    if (!('on_new_cocktail_additions' in value) || value['on_new_cocktail_additions'] === undefined) return false;
    return true;
}

export function AccountNotificationSettingsModelFromJSON(json: any): AccountNotificationSettingsModel {
    return AccountNotificationSettingsModelFromJSONTyped(json, false);
}

export function AccountNotificationSettingsModelFromJSONTyped(json: any, ignoreDiscriminator: boolean): AccountNotificationSettingsModel {
    if (json == null) {
        return json;
    }
    return {
        
        'on_new_cocktail_additions': CocktailUpdatedNotificationModelFromJSON(json['on_new_cocktail_additions']),
    };
}

export function AccountNotificationSettingsModelToJSON(json: any): AccountNotificationSettingsModel {
    return AccountNotificationSettingsModelToJSONTyped(json, false);
}

export function AccountNotificationSettingsModelToJSONTyped(value?: AccountNotificationSettingsModel | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'on_new_cocktail_additions': CocktailUpdatedNotificationModelToJSON(value['on_new_cocktail_additions']),
    };
}

