/* tslint:disable */
/* eslint-disable */
/**
 * Cezzi\'s Cocktails Accounts Api
 * An API for managing user accounts in Cezzi\'s Cocktails application.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { DisplayThemeModel } from './displayThemeModel';
import {
    DisplayThemeModelFromJSON,
    DisplayThemeModelFromJSONTyped,
    DisplayThemeModelToJSON,
    DisplayThemeModelToJSONTyped,
} from './displayThemeModel';

/**
 * The owned account profile accessibility settings.
 * @export
 * @interface AccountAccessibilitySettingsModel
 */
export interface AccountAccessibilitySettingsModel {
    /**
     * 
     * @type {DisplayThemeModel}
     * @memberof AccountAccessibilitySettingsModel
     */
    theme: DisplayThemeModel;
}



/**
 * Check if a given object implements the AccountAccessibilitySettingsModel interface.
 */
export function instanceOfAccountAccessibilitySettingsModel(value: object): value is AccountAccessibilitySettingsModel {
    if (!('theme' in value) || value['theme'] === undefined) return false;
    return true;
}

export function AccountAccessibilitySettingsModelFromJSON(json: any): AccountAccessibilitySettingsModel {
    return AccountAccessibilitySettingsModelFromJSONTyped(json, false);
}

export function AccountAccessibilitySettingsModelFromJSONTyped(json: any, ignoreDiscriminator: boolean): AccountAccessibilitySettingsModel {
    if (json == null) {
        return json;
    }
    return {
        
        'theme': DisplayThemeModelFromJSON(json['theme']),
    };
}

export function AccountAccessibilitySettingsModelToJSON(json: any): AccountAccessibilitySettingsModel {
    return AccountAccessibilitySettingsModelToJSONTyped(json, false);
}

export function AccountAccessibilitySettingsModelToJSONTyped(value?: AccountAccessibilitySettingsModel | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'theme': DisplayThemeModelToJSON(value['theme']),
    };
}

