/* tslint:disable */
/* eslint-disable */
/**
 * Cezzi\'s Cocktails Accounts Api
 * An API for managing user accounts in Cezzi\'s Cocktails application.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * The cocktail user ratings.
 * @export
 * @interface AccountCocktailRatingModel
 */
export interface AccountCocktailRatingModel {
    /**
     * The number of one star ratings
     * @type {number}
     * @memberof AccountCocktailRatingModel
     */
    one_stars: number;
    /**
     * The number of two star ratings
     * @type {number}
     * @memberof AccountCocktailRatingModel
     */
    two_stars: number;
    /**
     * The number of three star ratings
     * @type {number}
     * @memberof AccountCocktailRatingModel
     */
    three_stars: number;
    /**
     * The number of four star ratings
     * @type {number}
     * @memberof AccountCocktailRatingModel
     */
    four_stars: number;
    /**
     * The number of five star ratings
     * @type {number}
     * @memberof AccountCocktailRatingModel
     */
    five_stars: number;
    /**
     * The total number of stars given
     * @type {number}
     * @memberof AccountCocktailRatingModel
     */
    total_stars: number;
    /**
     * The actual overall rating
     * @type {string}
     * @memberof AccountCocktailRatingModel
     */
    rating: string;
    /**
     * The total number of ratings given
     * @type {number}
     * @memberof AccountCocktailRatingModel
     */
    rating_count: number;
}

/**
 * Check if a given object implements the AccountCocktailRatingModel interface.
 */
export function instanceOfAccountCocktailRatingModel(value: object): value is AccountCocktailRatingModel {
    if (!('one_stars' in value) || value['one_stars'] === undefined) return false;
    if (!('two_stars' in value) || value['two_stars'] === undefined) return false;
    if (!('three_stars' in value) || value['three_stars'] === undefined) return false;
    if (!('four_stars' in value) || value['four_stars'] === undefined) return false;
    if (!('five_stars' in value) || value['five_stars'] === undefined) return false;
    if (!('total_stars' in value) || value['total_stars'] === undefined) return false;
    if (!('rating' in value) || value['rating'] === undefined) return false;
    if (!('rating_count' in value) || value['rating_count'] === undefined) return false;
    return true;
}

export function AccountCocktailRatingModelFromJSON(json: any): AccountCocktailRatingModel {
    return AccountCocktailRatingModelFromJSONTyped(json, false);
}

export function AccountCocktailRatingModelFromJSONTyped(json: any, ignoreDiscriminator: boolean): AccountCocktailRatingModel {
    if (json == null) {
        return json;
    }
    return {
        
        'one_stars': json['one_stars'],
        'two_stars': json['two_stars'],
        'three_stars': json['three_stars'],
        'four_stars': json['four_stars'],
        'five_stars': json['five_stars'],
        'total_stars': json['total_stars'],
        'rating': json['rating'],
        'rating_count': json['rating_count'],
    };
}

export function AccountCocktailRatingModelToJSON(json: any): AccountCocktailRatingModel {
    return AccountCocktailRatingModelToJSONTyped(json, false);
}

export function AccountCocktailRatingModelToJSONTyped(value?: AccountCocktailRatingModel | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'one_stars': value['one_stars'],
        'two_stars': value['two_stars'],
        'three_stars': value['three_stars'],
        'four_stars': value['four_stars'],
        'five_stars': value['five_stars'],
        'total_stars': value['total_stars'],
        'rating': value['rating'],
        'rating_count': value['rating_count'],
    };
}

