/* tslint:disable */
/* eslint-disable */
/**
 * Cezzi\'s Cocktails Accounts Api
 * An API for managing user accounts in Cezzi\'s Cocktails application.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * The account owned profile change password request information.
 * @export
 * @interface ChangeAccountOwnedPasswordRq
 */
export interface ChangeAccountOwnedPasswordRq {
    /**
     * The email address for the account
     * @type {string}
     * @memberof ChangeAccountOwnedPasswordRq
     */
    email: string;
}

/**
 * Check if a given object implements the ChangeAccountOwnedPasswordRq interface.
 */
export function instanceOfChangeAccountOwnedPasswordRq(value: object): value is ChangeAccountOwnedPasswordRq {
    if (!('email' in value) || value['email'] === undefined) return false;
    return true;
}

export function ChangeAccountOwnedPasswordRqFromJSON(json: any): ChangeAccountOwnedPasswordRq {
    return ChangeAccountOwnedPasswordRqFromJSONTyped(json, false);
}

export function ChangeAccountOwnedPasswordRqFromJSONTyped(json: any, ignoreDiscriminator: boolean): ChangeAccountOwnedPasswordRq {
    if (json == null) {
        return json;
    }
    return {
        
        'email': json['email'],
    };
}

export function ChangeAccountOwnedPasswordRqToJSON(json: any): ChangeAccountOwnedPasswordRq {
    return ChangeAccountOwnedPasswordRqToJSONTyped(json, false);
}

export function ChangeAccountOwnedPasswordRqToJSONTyped(value?: ChangeAccountOwnedPasswordRq | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'email': value['email'],
    };
}

