/* tslint:disable */
/* eslint-disable */
/**
 * Cezzi\'s Cocktails Accounts Api
 * An API for managing user accounts in Cezzi\'s Cocktails application.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * The account owned profile upload email request information.
 * @export
 * @interface ChangeAccountOwnedEmailRq
 */
export interface ChangeAccountOwnedEmailRq {
    /**
     * The email address for the account
     * @type {string}
     * @memberof ChangeAccountOwnedEmailRq
     */
    email: string;
}

/**
 * Check if a given object implements the ChangeAccountOwnedEmailRq interface.
 */
export function instanceOfChangeAccountOwnedEmailRq(value: object): value is ChangeAccountOwnedEmailRq {
    if (!('email' in value) || value['email'] === undefined) return false;
    return true;
}

export function ChangeAccountOwnedEmailRqFromJSON(json: any): ChangeAccountOwnedEmailRq {
    return ChangeAccountOwnedEmailRqFromJSONTyped(json, false);
}

export function ChangeAccountOwnedEmailRqFromJSONTyped(json: any, ignoreDiscriminator: boolean): ChangeAccountOwnedEmailRq {
    if (json == null) {
        return json;
    }
    return {
        
        'email': json['email'],
    };
}

export function ChangeAccountOwnedEmailRqToJSON(json: any): ChangeAccountOwnedEmailRq {
    return ChangeAccountOwnedEmailRqToJSONTyped(json, false);
}

export function ChangeAccountOwnedEmailRqToJSONTyped(value?: ChangeAccountOwnedEmailRq | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'email': value['email'],
    };
}

