/* tslint:disable */
/* eslint-disable */
/**
 * Cezzi\'s Cocktails Accounts Api
 * An API for managing user accounts in Cezzi\'s Cocktails application.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { CocktailFavoritingActionModel } from './cocktailFavoritingActionModel';
import {
    CocktailFavoritingActionModelFromJSON,
    CocktailFavoritingActionModelFromJSONTyped,
    CocktailFavoritingActionModelToJSON,
    CocktailFavoritingActionModelToJSONTyped,
} from './cocktailFavoritingActionModel';

/**
 * A cocktail reference with management action within an owned account favorites list.
 * @export
 * @interface CocktailFavoriteActionModel
 */
export interface CocktailFavoriteActionModel {
    /**
     * The cocktail identifier
     * @type {string}
     * @memberof CocktailFavoriteActionModel
     */
    cocktail_id: string;
    /**
     * 
     * @type {CocktailFavoritingActionModel}
     * @memberof CocktailFavoriteActionModel
     */
    action: CocktailFavoritingActionModel;
}



/**
 * Check if a given object implements the CocktailFavoriteActionModel interface.
 */
export function instanceOfCocktailFavoriteActionModel(value: object): value is CocktailFavoriteActionModel {
    if (!('cocktail_id' in value) || value['cocktail_id'] === undefined) return false;
    if (!('action' in value) || value['action'] === undefined) return false;
    return true;
}

export function CocktailFavoriteActionModelFromJSON(json: any): CocktailFavoriteActionModel {
    return CocktailFavoriteActionModelFromJSONTyped(json, false);
}

export function CocktailFavoriteActionModelFromJSONTyped(json: any, ignoreDiscriminator: boolean): CocktailFavoriteActionModel {
    if (json == null) {
        return json;
    }
    return {
        
        'cocktail_id': json['cocktail_id'],
        'action': CocktailFavoritingActionModelFromJSON(json['action']),
    };
}

export function CocktailFavoriteActionModelToJSON(json: any): CocktailFavoriteActionModel {
    return CocktailFavoriteActionModelToJSONTyped(json, false);
}

export function CocktailFavoriteActionModelToJSONTyped(value?: CocktailFavoriteActionModel | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'cocktail_id': value['cocktail_id'],
        'action': CocktailFavoritingActionModelToJSON(value['action']),
    };
}

