/* tslint:disable */
/* eslint-disable */
/**
 * Cezzi\'s Cocktails Accounts Api
 * An API for managing user accounts in Cezzi\'s Cocktails application.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * An action that can be taken on a cocktail in an owned account's favorites list.
 * @export
 */
export const CocktailFavoritingActionModel = {
    Add: 'add',
    Remove: 'remove'
} as const;
export type CocktailFavoritingActionModel = typeof CocktailFavoritingActionModel[keyof typeof CocktailFavoritingActionModel];


export function instanceOfCocktailFavoritingActionModel(value: any): boolean {
    for (const key in CocktailFavoritingActionModel) {
        if (Object.prototype.hasOwnProperty.call(CocktailFavoritingActionModel, key)) {
            if (CocktailFavoritingActionModel[key as keyof typeof CocktailFavoritingActionModel] === value) {
                return true;
            }
        }
    }
    return false;
}

export function CocktailFavoritingActionModelFromJSON(json: any): CocktailFavoritingActionModel {
    return CocktailFavoritingActionModelFromJSONTyped(json, false);
}

export function CocktailFavoritingActionModelFromJSONTyped(json: any, ignoreDiscriminator: boolean): CocktailFavoritingActionModel {
    return json as CocktailFavoritingActionModel;
}

export function CocktailFavoritingActionModelToJSON(value?: CocktailFavoritingActionModel | null): any {
    return value as any;
}

export function CocktailFavoritingActionModelToJSONTyped(value: any, ignoreDiscriminator: boolean): CocktailFavoritingActionModel {
    return value as CocktailFavoritingActionModel;
}

