/* tslint:disable */
/* eslint-disable */
/**
 * Cezzi\'s Cocktails Accounts Api
 * An API for managing user accounts in Cezzi\'s Cocktails application.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { CocktailRecommendationModel } from './cocktailRecommendationModel';
import {
    CocktailRecommendationModelFromJSON,
    CocktailRecommendationModelFromJSONTyped,
    CocktailRecommendationModelToJSON,
    CocktailRecommendationModelToJSONTyped,
} from './cocktailRecommendationModel';

/**
 * The cocktail recommendation request.
 * @export
 * @interface CocktailRecommendationRq
 */
export interface CocktailRecommendationRq {
    /**
     * 
     * @type {CocktailRecommendationModel}
     * @memberof CocktailRecommendationRq
     */
    recommendation: CocktailRecommendationModel;
    /**
     * The google recaptcha verification code returned after being valid
     * @type {string}
     * @memberof CocktailRecommendationRq
     */
    verificationCode: string;
}

/**
 * Check if a given object implements the CocktailRecommendationRq interface.
 */
export function instanceOfCocktailRecommendationRq(value: object): value is CocktailRecommendationRq {
    if (!('recommendation' in value) || value['recommendation'] === undefined) return false;
    if (!('verificationCode' in value) || value['verificationCode'] === undefined) return false;
    return true;
}

export function CocktailRecommendationRqFromJSON(json: any): CocktailRecommendationRq {
    return CocktailRecommendationRqFromJSONTyped(json, false);
}

export function CocktailRecommendationRqFromJSONTyped(json: any, ignoreDiscriminator: boolean): CocktailRecommendationRq {
    if (json == null) {
        return json;
    }
    return {
        
        'recommendation': CocktailRecommendationModelFromJSON(json['recommendation']),
        'verificationCode': json['verificationCode'],
    };
}

export function CocktailRecommendationRqToJSON(json: any): CocktailRecommendationRq {
    return CocktailRecommendationRqToJSONTyped(json, false);
}

export function CocktailRecommendationRqToJSONTyped(value?: CocktailRecommendationRq | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'recommendation': CocktailRecommendationModelToJSON(value['recommendation']),
        'verificationCode': value['verificationCode'],
    };
}

