/* tslint:disable */
/* eslint-disable */
/**
 * Cezzi\'s Cocktails Accounts Api
 * An API for managing user accounts in Cezzi\'s Cocktails application.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * Notification frequency for cocktail updates.
 * @export
 * @enum {string}
 */
export enum CocktailUpdatedNotificationModel {
    Never = 'never',
    Always = 'always'
}


export function instanceOfCocktailUpdatedNotificationModel(value: any): boolean {
    for (const key in CocktailUpdatedNotificationModel) {
        if (Object.prototype.hasOwnProperty.call(CocktailUpdatedNotificationModel, key)) {
            if (CocktailUpdatedNotificationModel[key as keyof typeof CocktailUpdatedNotificationModel] === value) {
                return true;
            }
        }
    }
    return false;
}

export function CocktailUpdatedNotificationModelFromJSON(json: any): CocktailUpdatedNotificationModel {
    return CocktailUpdatedNotificationModelFromJSONTyped(json, false);
}

export function CocktailUpdatedNotificationModelFromJSONTyped(json: any, ignoreDiscriminator: boolean): CocktailUpdatedNotificationModel {
    return json as CocktailUpdatedNotificationModel;
}

export function CocktailUpdatedNotificationModelToJSON(value?: CocktailUpdatedNotificationModel | null): any {
    return value as any;
}

export function CocktailUpdatedNotificationModelToJSONTyped(value: any, ignoreDiscriminator: boolean): CocktailUpdatedNotificationModel {
    return value as CocktailUpdatedNotificationModel;
}

