/* tslint:disable */
/* eslint-disable */
/**
 * Cezzi\'s Cocktails Accounts Api
 * An API for managing user accounts in Cezzi\'s Cocktails application.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * The cocktail recommendation model.
 * @export
 * @interface CocktailRecommendationModel
 */
export interface CocktailRecommendationModel {
    /**
     * The name of the cocktail or variation
     * @type {string}
     * @memberof CocktailRecommendationModel
     */
    name: string;
    /**
     * The ingredients description of the cocktail or variation
     * @type {string}
     * @memberof CocktailRecommendationModel
     */
    ingredients: string;
    /**
     * The directions description of the cocktail or variation
     * @type {string}
     * @memberof CocktailRecommendationModel
     */
    directions: string;
}

/**
 * Check if a given object implements the CocktailRecommendationModel interface.
 */
export function instanceOfCocktailRecommendationModel(value: object): value is CocktailRecommendationModel {
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('ingredients' in value) || value['ingredients'] === undefined) return false;
    if (!('directions' in value) || value['directions'] === undefined) return false;
    return true;
}

export function CocktailRecommendationModelFromJSON(json: any): CocktailRecommendationModel {
    return CocktailRecommendationModelFromJSONTyped(json, false);
}

export function CocktailRecommendationModelFromJSONTyped(json: any, ignoreDiscriminator: boolean): CocktailRecommendationModel {
    if (json == null) {
        return json;
    }
    return {
        
        'name': json['name'],
        'ingredients': json['ingredients'],
        'directions': json['directions'],
    };
}

export function CocktailRecommendationModelToJSON(json: any): CocktailRecommendationModel {
    return CocktailRecommendationModelToJSONTyped(json, false);
}

export function CocktailRecommendationModelToJSONTyped(value?: CocktailRecommendationModel | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'name': value['name'],
        'ingredients': value['ingredients'],
        'directions': value['directions'],
    };
}

