/* tslint:disable */
/* eslint-disable */
/**
 * Cezzi\'s Cocktails Accounts Api
 * An API for managing user accounts in Cezzi\'s Cocktails application.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * The display themes available for profile accessibility settings.
 * @export
 * @enum {string}
 */
export enum DisplayThemeModel {
    Light = 'light',
    Dark = 'dark'
}


export function instanceOfDisplayThemeModel(value: any): boolean {
    for (const key in DisplayThemeModel) {
        if (Object.prototype.hasOwnProperty.call(DisplayThemeModel, key)) {
            if (DisplayThemeModel[key as keyof typeof DisplayThemeModel] === value) {
                return true;
            }
        }
    }
    return false;
}

export function DisplayThemeModelFromJSON(json: any): DisplayThemeModel {
    return DisplayThemeModelFromJSONTyped(json, false);
}

export function DisplayThemeModelFromJSONTyped(json: any, ignoreDiscriminator: boolean): DisplayThemeModel {
    return json as DisplayThemeModel;
}

export function DisplayThemeModelToJSON(value?: DisplayThemeModel | null): any {
    return value as any;
}

export function DisplayThemeModelToJSONTyped(value: any, ignoreDiscriminator: boolean): DisplayThemeModel {
    return value as DisplayThemeModel;
}

