/* tslint:disable */
/* eslint-disable */
/**
 * Cezzi\'s Cocktails Accounts Api
 * An API for managing user accounts in Cezzi\'s Cocktails application.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { CocktailFavoriteActionModel } from './cocktailFavoriteActionModel';
import {
    CocktailFavoriteActionModelFromJSON,
    CocktailFavoriteActionModelFromJSONTyped,
    CocktailFavoriteActionModelToJSON,
    CocktailFavoriteActionModelToJSONTyped,
} from './cocktailFavoriteActionModel';

/**
 * The request to manage an owned account's favorite cocktails.
 * @export
 * @interface ManageFavoriteCocktailsRq
 */
export interface ManageFavoriteCocktailsRq {
    /**
     * The list of cocktail actions to perform
     * @type {Array<CocktailFavoriteActionModel>}
     * @memberof ManageFavoriteCocktailsRq
     */
    cocktailActions: Array<CocktailFavoriteActionModel>;
}

/**
 * Check if a given object implements the ManageFavoriteCocktailsRq interface.
 */
export function instanceOfManageFavoriteCocktailsRq(value: object): value is ManageFavoriteCocktailsRq {
    if (!('cocktailActions' in value) || value['cocktailActions'] === undefined) return false;
    return true;
}

export function ManageFavoriteCocktailsRqFromJSON(json: any): ManageFavoriteCocktailsRq {
    return ManageFavoriteCocktailsRqFromJSONTyped(json, false);
}

export function ManageFavoriteCocktailsRqFromJSONTyped(json: any, ignoreDiscriminator: boolean): ManageFavoriteCocktailsRq {
    if (json == null) {
        return json;
    }
    return {
        
        'cocktailActions': ((json['cocktailActions'] as Array<any>).map(CocktailFavoriteActionModelFromJSON)),
    };
}

export function ManageFavoriteCocktailsRqToJSON(json: any): ManageFavoriteCocktailsRq {
    return ManageFavoriteCocktailsRqToJSONTyped(json, false);
}

export function ManageFavoriteCocktailsRqToJSONTyped(value?: ManageFavoriteCocktailsRq | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'cocktailActions': ((value['cocktailActions'] as Array<any>).map(CocktailFavoriteActionModelToJSON)),
    };
}

