/* tslint:disable */
/* eslint-disable */
/**
 * Cezzi\'s Cocktails Accounts Api
 * An API for managing user accounts in Cezzi\'s Cocktails application.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { AccountCocktailRatingsModel } from './accountCocktailRatingsModel';
import {
    AccountCocktailRatingsModelFromJSON,
    AccountCocktailRatingsModelFromJSONTyped,
    AccountCocktailRatingsModelToJSON,
    AccountCocktailRatingsModelToJSONTyped,
} from './accountCocktailRatingsModel';
import type { AccountCocktailRatingModel } from './accountCocktailRatingModel';
import {
    AccountCocktailRatingModelFromJSON,
    AccountCocktailRatingModelFromJSONTyped,
    AccountCocktailRatingModelToJSON,
    AccountCocktailRatingModelToJSONTyped,
} from './accountCocktailRatingModel';

/**
 * The cocktail rating response from an account supplied cocktail rating.
 * @export
 * @interface RateCocktailRs
 */
export interface RateCocktailRs {
    /**
     * The cocktail ratings
     * @type {Array<AccountCocktailRatingsModel>}
     * @memberof RateCocktailRs
     */
    ratings: Array<AccountCocktailRatingsModel>;
    /**
     * The cocktail identifier
     * @type {string}
     * @memberof RateCocktailRs
     */
    cocktail_id: string;
    /**
     * 
     * @type {AccountCocktailRatingModel}
     * @memberof RateCocktailRs
     */
    cocktail_rating: AccountCocktailRatingModel;
}

/**
 * Check if a given object implements the RateCocktailRs interface.
 */
export function instanceOfRateCocktailRs(value: object): value is RateCocktailRs {
    if (!('ratings' in value) || value['ratings'] === undefined) return false;
    if (!('cocktail_id' in value) || value['cocktail_id'] === undefined) return false;
    if (!('cocktail_rating' in value) || value['cocktail_rating'] === undefined) return false;
    return true;
}

export function RateCocktailRsFromJSON(json: any): RateCocktailRs {
    return RateCocktailRsFromJSONTyped(json, false);
}

export function RateCocktailRsFromJSONTyped(json: any, ignoreDiscriminator: boolean): RateCocktailRs {
    if (json == null) {
        return json;
    }
    return {
        
        'ratings': ((json['ratings'] as Array<any>).map(AccountCocktailRatingsModelFromJSON)),
        'cocktail_id': json['cocktail_id'],
        'cocktail_rating': AccountCocktailRatingModelFromJSON(json['cocktail_rating']),
    };
}

export function RateCocktailRsToJSON(json: any): RateCocktailRs {
    return RateCocktailRsToJSONTyped(json, false);
}

export function RateCocktailRsToJSONTyped(value?: RateCocktailRs | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'ratings': ((value['ratings'] as Array<any>).map(AccountCocktailRatingsModelToJSON)),
        'cocktail_id': value['cocktail_id'],
        'cocktail_rating': AccountCocktailRatingModelToJSON(value['cocktail_rating']),
    };
}

