/* tslint:disable */
/* eslint-disable */
/**
 * Cezzi\'s Cocktails Accounts Api
 * An API for managing user accounts in Cezzi\'s Cocktails application.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { AccountCocktailRatingModel } from './accountCocktailRatingModel';
import {
    AccountCocktailRatingModelFromJSON,
    AccountCocktailRatingModelFromJSONTyped,
    AccountCocktailRatingModelToJSON,
    AccountCocktailRatingModelToJSONTyped,
} from './accountCocktailRatingModel';

/**
 * A cocktail reference with user supplied rating.
 * @export
 * @interface RateCocktailRq
 */
export interface RateCocktailRq {
    /**
     * The cocktail identifier
     * @type {string}
     * @memberof RateCocktailRq
     */
    cocktailId: string;
    /**
     * The rating for the cocktail (1-5)
     * @type {number}
     * @memberof RateCocktailRq
     */
    stars: number;
    /**
     * 
     * @type {AccountCocktailRatingModel}
     * @memberof RateCocktailRq
     */
    currentRatings: AccountCocktailRatingModel;
}

/**
 * Check if a given object implements the RateCocktailRq interface.
 */
export function instanceOfRateCocktailRq(value: object): value is RateCocktailRq {
    if (!('cocktailId' in value) || value['cocktailId'] === undefined) return false;
    if (!('stars' in value) || value['stars'] === undefined) return false;
    if (!('currentRatings' in value) || value['currentRatings'] === undefined) return false;
    return true;
}

export function RateCocktailRqFromJSON(json: any): RateCocktailRq {
    return RateCocktailRqFromJSONTyped(json, false);
}

export function RateCocktailRqFromJSONTyped(json: any, ignoreDiscriminator: boolean): RateCocktailRq {
    if (json == null) {
        return json;
    }
    return {
        
        'cocktailId': json['cocktailId'],
        'stars': json['stars'],
        'currentRatings': AccountCocktailRatingModelFromJSON(json['currentRatings']),
    };
}

export function RateCocktailRqToJSON(json: any): RateCocktailRq {
    return RateCocktailRqToJSONTyped(json, false);
}

export function RateCocktailRqToJSONTyped(value?: RateCocktailRq | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'cocktailId': value['cocktailId'],
        'stars': value['stars'],
        'currentRatings': AccountCocktailRatingModelToJSON(value['currentRatings']),
    };
}

