/* tslint:disable */
/* eslint-disable */
/**
 * Cezzi\'s Cocktails Accounts Api
 * An API for managing user accounts in Cezzi\'s Cocktails application.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { DisplayThemeModel } from './displayThemeModel';
import {
    DisplayThemeModelFromJSON,
    DisplayThemeModelFromJSONTyped,
    DisplayThemeModelToJSON,
    DisplayThemeModelToJSONTyped,
} from './displayThemeModel';

/**
 * The account owned profile accessibility settings.
 * @export
 * @interface UpdateAccountOwnedAccessibilitySettingsRq
 */
export interface UpdateAccountOwnedAccessibilitySettingsRq {
    /**
     * 
     * @type {DisplayThemeModel}
     * @memberof UpdateAccountOwnedAccessibilitySettingsRq
     */
    theme: DisplayThemeModel;
}



/**
 * Check if a given object implements the UpdateAccountOwnedAccessibilitySettingsRq interface.
 */
export function instanceOfUpdateAccountOwnedAccessibilitySettingsRq(value: object): value is UpdateAccountOwnedAccessibilitySettingsRq {
    if (!('theme' in value) || value['theme'] === undefined) return false;
    return true;
}

export function UpdateAccountOwnedAccessibilitySettingsRqFromJSON(json: any): UpdateAccountOwnedAccessibilitySettingsRq {
    return UpdateAccountOwnedAccessibilitySettingsRqFromJSONTyped(json, false);
}

export function UpdateAccountOwnedAccessibilitySettingsRqFromJSONTyped(json: any, ignoreDiscriminator: boolean): UpdateAccountOwnedAccessibilitySettingsRq {
    if (json == null) {
        return json;
    }
    return {
        
        'theme': DisplayThemeModelFromJSON(json['theme']),
    };
}

export function UpdateAccountOwnedAccessibilitySettingsRqToJSON(json: any): UpdateAccountOwnedAccessibilitySettingsRq {
    return UpdateAccountOwnedAccessibilitySettingsRqToJSONTyped(json, false);
}

export function UpdateAccountOwnedAccessibilitySettingsRqToJSONTyped(value?: UpdateAccountOwnedAccessibilitySettingsRq | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'theme': DisplayThemeModelToJSON(value['theme']),
    };
}

