/* tslint:disable */
/* eslint-disable */
/**
 * Cezzi\'s Cocktails Accounts Api
 * An API for managing user accounts in Cezzi\'s Cocktails application.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { AccountAddressModel } from './accountAddressModel';
import {
    AccountAddressModelFromJSON,
    AccountAddressModelFromJSONTyped,
    AccountAddressModelToJSON,
    AccountAddressModelToJSONTyped,
} from './accountAddressModel';

/**
 * The account owned profile upload request information.
 * @export
 * @interface UpdateAccountOwnedProfileRq
 */
export interface UpdateAccountOwnedProfileRq {
    /**
     * The given name on the account
     * @type {string}
     * @memberof UpdateAccountOwnedProfileRq
     */
    given_name: string;
    /**
     * The family name on the account
     * @type {string}
     * @memberof UpdateAccountOwnedProfileRq
     */
    family_name: string;
    /**
     * The display for the account visible to other users
     * @type {string}
     * @memberof UpdateAccountOwnedProfileRq
     */
    display_name: string;
    /**
     * The optional primary address listed with the account
     * @type {AccountAddressModel}
     * @memberof UpdateAccountOwnedProfileRq
     */
    primary_address?: AccountAddressModel | null;
}

/**
 * Check if a given object implements the UpdateAccountOwnedProfileRq interface.
 */
export function instanceOfUpdateAccountOwnedProfileRq(value: object): value is UpdateAccountOwnedProfileRq {
    if (!('given_name' in value) || value['given_name'] === undefined) return false;
    if (!('family_name' in value) || value['family_name'] === undefined) return false;
    if (!('display_name' in value) || value['display_name'] === undefined) return false;
    return true;
}

export function UpdateAccountOwnedProfileRqFromJSON(json: any): UpdateAccountOwnedProfileRq {
    return UpdateAccountOwnedProfileRqFromJSONTyped(json, false);
}

export function UpdateAccountOwnedProfileRqFromJSONTyped(json: any, ignoreDiscriminator: boolean): UpdateAccountOwnedProfileRq {
    if (json == null) {
        return json;
    }
    return {
        
        'given_name': json['given_name'],
        'family_name': json['family_name'],
        'display_name': json['display_name'],
        'primary_address': json['primary_address'] == null ? undefined : AccountAddressModelFromJSON(json['primary_address']),
    };
}

export function UpdateAccountOwnedProfileRqToJSON(json: any): UpdateAccountOwnedProfileRq {
    return UpdateAccountOwnedProfileRqToJSONTyped(json, false);
}

export function UpdateAccountOwnedProfileRqToJSONTyped(value?: UpdateAccountOwnedProfileRq | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'given_name': value['given_name'],
        'family_name': value['family_name'],
        'display_name': value['display_name'],
        'primary_address': AccountAddressModelToJSON(value['primary_address']),
    };
}

