/* tslint:disable */
/* eslint-disable */
/**
 * Cezzi\'s Cocktails Accounts Api
 * An API for managing user accounts in Cezzi\'s Cocktails application.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { CocktailUpdatedNotificationModel } from './cocktailUpdatedNotificationModel';
import {
    CocktailUpdatedNotificationModelFromJSON,
    CocktailUpdatedNotificationModelFromJSONTyped,
    CocktailUpdatedNotificationModelToJSON,
    CocktailUpdatedNotificationModelToJSONTyped,
} from './cocktailUpdatedNotificationModel';

/**
 * The account owned profile notification settings.
 * @export
 * @interface UpdateAccountOwnedNotificationSettingsRq
 */
export interface UpdateAccountOwnedNotificationSettingsRq {
    /**
     * 
     * @type {CocktailUpdatedNotificationModel}
     * @memberof UpdateAccountOwnedNotificationSettingsRq
     */
    onNewCocktailAdditions: CocktailUpdatedNotificationModel;
}



/**
 * Check if a given object implements the UpdateAccountOwnedNotificationSettingsRq interface.
 */
export function instanceOfUpdateAccountOwnedNotificationSettingsRq(value: object): value is UpdateAccountOwnedNotificationSettingsRq {
    if (!('onNewCocktailAdditions' in value) || value['onNewCocktailAdditions'] === undefined) return false;
    return true;
}

export function UpdateAccountOwnedNotificationSettingsRqFromJSON(json: any): UpdateAccountOwnedNotificationSettingsRq {
    return UpdateAccountOwnedNotificationSettingsRqFromJSONTyped(json, false);
}

export function UpdateAccountOwnedNotificationSettingsRqFromJSONTyped(json: any, ignoreDiscriminator: boolean): UpdateAccountOwnedNotificationSettingsRq {
    if (json == null) {
        return json;
    }
    return {
        
        'onNewCocktailAdditions': CocktailUpdatedNotificationModelFromJSON(json['onNewCocktailAdditions']),
    };
}

export function UpdateAccountOwnedNotificationSettingsRqToJSON(json: any): UpdateAccountOwnedNotificationSettingsRq {
    return UpdateAccountOwnedNotificationSettingsRqToJSONTyped(json, false);
}

export function UpdateAccountOwnedNotificationSettingsRqToJSONTyped(value?: UpdateAccountOwnedNotificationSettingsRq | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'onNewCocktailAdditions': CocktailUpdatedNotificationModelToJSON(value['onNewCocktailAdditions']),
    };
}

