/* tslint:disable */
/* eslint-disable */
/**
 * Cezzi\'s Cocktails Accounts Api
 * An API for managing user accounts in Cezzi\'s Cocktails application.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { AccountAddressModel } from './accountAddressModel';
import {
    AccountAddressModelFromJSON,
    AccountAddressModelFromJSONTyped,
    AccountAddressModelToJSON,
    AccountAddressModelToJSONTyped,
} from './accountAddressModel';

/**
 * The account owned profile upload request information.
 * @export
 * @interface UpdateAccountOwnedProfileRq
 */
export interface UpdateAccountOwnedProfileRq {
    /**
     * The given name on the account
     * @type {string}
     * @memberof UpdateAccountOwnedProfileRq
     */
    givenName: string;
    /**
     * The family name on the account
     * @type {string}
     * @memberof UpdateAccountOwnedProfileRq
     */
    familyName: string;
    /**
     * The display for the account visible to other users
     * @type {string}
     * @memberof UpdateAccountOwnedProfileRq
     */
    displayName: string;
    /**
     * The optional primary address listed with the account
     * @type {AccountAddressModel}
     * @memberof UpdateAccountOwnedProfileRq
     */
    primaryAddress?: AccountAddressModel | null;
}

/**
 * Check if a given object implements the UpdateAccountOwnedProfileRq interface.
 */
export function instanceOfUpdateAccountOwnedProfileRq(value: object): value is UpdateAccountOwnedProfileRq {
    if (!('givenName' in value) || value['givenName'] === undefined) return false;
    if (!('familyName' in value) || value['familyName'] === undefined) return false;
    if (!('displayName' in value) || value['displayName'] === undefined) return false;
    return true;
}

export function UpdateAccountOwnedProfileRqFromJSON(json: any): UpdateAccountOwnedProfileRq {
    return UpdateAccountOwnedProfileRqFromJSONTyped(json, false);
}

export function UpdateAccountOwnedProfileRqFromJSONTyped(json: any, ignoreDiscriminator: boolean): UpdateAccountOwnedProfileRq {
    if (json == null) {
        return json;
    }
    return {
        
        'givenName': json['givenName'],
        'familyName': json['familyName'],
        'displayName': json['displayName'],
        'primaryAddress': json['primaryAddress'] == null ? undefined : AccountAddressModelFromJSON(json['primaryAddress']),
    };
}

export function UpdateAccountOwnedProfileRqToJSON(json: any): UpdateAccountOwnedProfileRq {
    return UpdateAccountOwnedProfileRqToJSONTyped(json, false);
}

export function UpdateAccountOwnedProfileRqToJSONTyped(value?: UpdateAccountOwnedProfileRq | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'givenName': value['givenName'],
        'familyName': value['familyName'],
        'displayName': value['displayName'],
        'primaryAddress': AccountAddressModelToJSON(value['primaryAddress']),
    };
}

