/* tslint:disable */
/* eslint-disable */
/**
 * Cezzi\'s Cocktails Accounts Api
 * An API for managing user accounts in Cezzi\'s Cocktails application.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * The profile image upload response.
 * @export
 * @interface UploadProfileImageRs
 */
export interface UploadProfileImageRs {
    /**
     * The uri for the image that was uploaded
     * @type {string}
     * @memberof UploadProfileImageRs
     */
    imageUri: string;
}

/**
 * Check if a given object implements the UploadProfileImageRs interface.
 */
export function instanceOfUploadProfileImageRs(value: object): value is UploadProfileImageRs {
    if (!('imageUri' in value) || value['imageUri'] === undefined) return false;
    return true;
}

export function UploadProfileImageRsFromJSON(json: any): UploadProfileImageRs {
    return UploadProfileImageRsFromJSONTyped(json, false);
}

export function UploadProfileImageRsFromJSONTyped(json: any, ignoreDiscriminator: boolean): UploadProfileImageRs {
    if (json == null) {
        return json;
    }
    return {
        
        'imageUri': json['imageUri'],
    };
}

export function UploadProfileImageRsToJSON(json: any): UploadProfileImageRs {
    return UploadProfileImageRsToJSONTyped(json, false);
}

export function UploadProfileImageRsToJSONTyped(value?: UploadProfileImageRs | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'imageUri': value['imageUri'],
    };
}

