
// ------------------------------------------------------------
// Cocktail
// ------------------------------------------------------------

GET {{host}}/api/v1/cocktails/gibson
Accept: application/json
X-Key: {{apimkey}}

###

GET {{host}}/api/v1/cocktails/pegu-club
Accept: application/json
X-Key: {{apimkey}}

###

GET {{host}}/api/v1/cocktails/absinthe-frappe
Accept: application/json
X-Key: {{apimkey}}

###

// ------------------------------------------------------------
// Cocktail/Ingredients Seed
// ------------------------------------------------------------

PUT {{host}}/api/v1/cocktails
Accept: application/json
X-Key: {{apimkey}}

###

PUT {{host}}/api/v1/cocktails/ingredients
Accept: application/json
X-Key: {{apimkey}}

###

// ------------------------------------------------------------
// Cocktails List
// ------------------------------------------------------------


GET {{host}}/api/v1/cocktails?freeText=las
X-Key: {{apimkey}}

###

GET {{host}}/api/v1/cocktails/list?skip=0&take=12
X-Key: {{apimkey}}

###


GET {{host}}/api/v1/cocktails/list?skip=0&take=2&inc=mainImages
X-Key: {{apimkey}}

###

PUT {{host}}/api/v1/cocktails/list
X-Key: {{apimkey}}

###



// ------------------------------------------------------------
// Cocktails Sitemap
// ------------------------------------------------------------


GET {{host}}/api/v1/cocktails/sitemap
X-Key: {{apimkey}}

###

// ------------------------------------------------------------
// Cocktails IndexNow
// ------------------------------------------------------------


GET {{host}}/api/v1/cocktails/indexnow
X-Key: {{apimkey}}

###

// ------------------------------------------------------------
// Cocktails Search Filters
// ------------------------------------------------------------


GET {{host}}/api/v1/cocktails/ingredients/filters
Accept: application/json
X-Key: {{apimkey}}


###


// ------------------------------------------------------------
// BING Index Now
// ------------------------------------------------------------

POST https://www.bing.com/indexnow HTTP/1.1
Content-Type: application/json; charset=utf-8

{
  "host": "www.cezzis.com",
  "key": "1d67a02bdad24c059d0d79f8c6011631",
  "keyLocation": "https://www.cezzis.com/1d67a02bdad24c059d0d79f8c6011631.txt",
  "urlList": [
    "https://www.cezzis.com/cocktails/absinthe-frappe",
    "https://www.cezzis.com/cocktails/adonis",
    "https://www.cezzis.com/cocktails/airmail",
    "https://www.cezzis.com/cocktails/americano",
    "https://www.cezzis.com/cocktails/aperol-spritz",
    "https://www.cezzis.com/cocktails/aviation",
    "https://www.cezzis.com/cocktails/bamboo",
    "https://www.cezzis.com/cocktails/bees-knees",
    "https://www.cezzis.com/cocktails/bicicletta",
    "https://www.cezzis.com/cocktails/bijou",
    "https://www.cezzis.com/cocktails/black-velvet",
    "https://www.cezzis.com/cocktails/blood-and-sand",
    "https://www.cezzis.com/cocktails/bloody-mary",
    "https://www.cezzis.com/cocktails/boulevardier",
    "https://www.cezzis.com/cocktails/brooklyn",
    "https://www.cezzis.com/cocktails/brown-derby",
    "https://www.cezzis.com/cocktails/caipirinha",
    "https://www.cezzis.com/cocktails/champagne-cocktail",
    "https://www.cezzis.com/cocktails/charles-Dickenss-punch",
    "https://www.cezzis.com/cocktails/clover-club",
    "https://www.cezzis.com/cocktails/corpse-reviver-no-2",
    "https://www.cezzis.com/cocktails/daiquiri",
    "https://www.cezzis.com/cocktails/daniel-websters-punch",
    "https://www.cezzis.com/cocktails/dark-n-stormy",
    "https://www.cezzis.com/cocktails/de-la-louisiane",
    "https://www.cezzis.com/cocktails/death-in-the-afternoon",
    "https://www.cezzis.com/cocktails/florodora",
    "https://www.cezzis.com/cocktails/french-75",
    "https://www.cezzis.com/cocktails/garibaldi",
    "https://www.cezzis.com/cocktails/gibson",
    "https://www.cezzis.com/cocktails/gimlet",
    "https://www.cezzis.com/cocktails/gin-and-tonic",
    "https://www.cezzis.com/cocktails/gin-daisy",
    "https://www.cezzis.com/cocktails/gin-fizz",
    "https://www.cezzis.com/cocktails/gin-rickey",
    "https://www.cezzis.com/cocktails/gin-sour",
    "https://www.cezzis.com/cocktails/hemingway-daiquiri",
    "https://www.cezzis.com/cocktails/improved-whiskey-cocktail",
    "https://www.cezzis.com/cocktails/jungle-bird",
    "https://www.cezzis.com/cocktails/last-word",
    "https://www.cezzis.com/cocktails/mai-tai",
    "https://www.cezzis.com/cocktails/manhattan",
    "https://www.cezzis.com/cocktails/margarita",
    "https://www.cezzis.com/cocktails/martinez",
    "https://www.cezzis.com/cocktails/martini",
    "https://www.cezzis.com/cocktails/mexican-firing-squad",
    "https://www.cezzis.com/cocktails/michelada",
    "https://www.cezzis.com/cocktails/millionaire-cocktail",
    "https://www.cezzis.com/cocktails/mint-julep",
    "https://www.cezzis.com/cocktails/mojito",
    "https://www.cezzis.com/cocktails/moscow-mule",
    "https://www.cezzis.com/cocktails/negroni",
    "https://www.cezzis.com/cocktails/negroni-sbagliato",
    "https://www.cezzis.com/cocktails/new-york-sour",
    "https://www.cezzis.com/cocktails/old-pal",
    "https://www.cezzis.com/cocktails/old-fashioned",
    "https://www.cezzis.com/cocktails/pain-killer",
    "https://www.cezzis.com/cocktails/paloma",
    "https://www.cezzis.com/cocktails/pegu-club",
    "https://www.cezzis.com/cocktails/philadelphia-fish-house-punch",
    "https://www.cezzis.com/cocktails/pimms-cup",
    "https://www.cezzis.com/cocktails/pina-colada",
    "https://www.cezzis.com/cocktails/pisco-sour",
    "https://www.cezzis.com/cocktails/planters-punch",
    "https://www.cezzis.com/cocktails/queens-park-swizzle",
    "https://www.cezzis.com/cocktails/ramos-gin-fizz",
    "https://www.cezzis.com/cocktails/remember-the-maine",
    "https://www.cezzis.com/cocktails/rob-roy",
    "https://www.cezzis.com/cocktails/sazerac",
    "https://www.cezzis.com/cocktails/scorpion-bowl",
    "https://www.cezzis.com/cocktails/sherry-cobbler",
    "https://www.cezzis.com/cocktails/sherry-flip",
    "https://www.cezzis.com/cocktails/sidecar",
    "https://www.cezzis.com/cocktails/singapore-sling",
    "https://www.cezzis.com/cocktails/sloe-gin-fizz",
    "https://www.cezzis.com/cocktails/southside",
    "https://www.cezzis.com/cocktails/stone-fence",
    "https://www.cezzis.com/cocktails/ti-punch",
    "https://www.cezzis.com/cocktails/tom-collins",
    "https://www.cezzis.com/cocktails/tuxedo",
    "https://www.cezzis.com/cocktails/vesper",
    "https://www.cezzis.com/cocktails/vieux-carre",
    "https://www.cezzis.com/cocktails/whiskey-smash",
    "https://www.cezzis.com/cocktails/whiskey-sour",
    "https://www.cezzis.com/cocktails/zombie"
  ]
}


###