
// ------------------------------------------------------------
// Cocktail
// ------------------------------------------------------------

GET {{host}}/api/v1/cocktails/list/gibson
Accept: application/json
X-Key: {{apimkey}}

###

GET {{host}}/api/v1/cocktails/list/pegu-club
Accept: application/json
X-Key: {{apimkey}}

###


// ------------------------------------------------------------
// Cocktails List
// ------------------------------------------------------------


GET {{host}}/api/v1/cocktails/list
X-Key: {{apimkey}}

###

GET {{host}}/api/v1/cocktails/list?skip=0&take=12
X-Key: {{apimkey}}

###


GET {{host}}/api/v1/cocktails/list?skip=0&take=2&inc=mainImages
X-Key: {{apimkey}}

###


// ------------------------------------------------------------
// Cocktails Search
// ------------------------------------------------------------


GET {{host}}/api/v1/cocktails/search
X-Key: {{apimkey}}

###


GET {{host}}/api/v1/cocktails/search?skip=0&take=12
X-Key: {{apimkey}}

###


GET {{host}}/api/v1/cocktails/search?skip=0&take=2&inc=mainImages
X-Key: {{apimkey}}

###


// ------------------------------------------------------------
// Cocktails Sitemap
// ------------------------------------------------------------


GET {{host}}/api/v1/cocktails/sitemap
X-Key: {{apimkey}}

###

// ------------------------------------------------------------
// Cocktails Search Filters
// ------------------------------------------------------------


GET {{host}}/api/v1/cocktails/search/filters
Accept: application/json
X-Key: {{apimkey}}

###

// ------------------------------------------------------------
// Cocktails Recommendations
// ------------------------------------------------------------



POST {{host}}/api/v1/cocktails/recommendations
Content-Type: application/json
X-Key: {{apimkey}}

{
  "recommendation": {
    "name": "Rons test cocktail",
    "ingredients": "test ingredients",
    "directions": "test directions"
  },
  "verificationCode": "d"
}

###
