

GET {{host}}/api/v1/accounts/owned/profile
X-Key: {{apimkey}}


###


// ------------------------------------------------------------
// Account cocktails recommendations
// ------------------------------------------------------------


POST {{host}}/api/v1/owned/profile/cocktails/recommendations
Content-Type: application/json
X-Key: {{apimkey}}

{
  "recommendation": {
    "name": "Rons test cocktail",
    "ingredients": "test ingredients",
    "directions": "test directions"
  },
  "verificationCode": "d"
}

###
