/* tslint:disable */
/* eslint-disable */
/**
 * Cezzi\'s Cocktails AI Search API
 * An AI-powered cocktail search API using semantic search and embeddings.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * The application types for cocktail ingredients.
 * @export
 * @enum {string}
 */
export enum CocktailSearchIngredientApplicationTypeModel {
    Base = 'base',
    Additional = 'additional',
    Garnishment = 'garnishment',
    Muddle = 'muddle'
}


export function instanceOfCocktailSearchIngredientApplicationTypeModel(value: any): boolean {
    for (const key in CocktailSearchIngredientApplicationTypeModel) {
        if (Object.prototype.hasOwnProperty.call(CocktailSearchIngredientApplicationTypeModel, key)) {
            if (CocktailSearchIngredientApplicationTypeModel[key as keyof typeof CocktailSearchIngredientApplicationTypeModel] === value) {
                return true;
            }
        }
    }
    return false;
}

export function CocktailSearchIngredientApplicationTypeModelFromJSON(json: any): CocktailSearchIngredientApplicationTypeModel {
    return CocktailSearchIngredientApplicationTypeModelFromJSONTyped(json, false);
}

export function CocktailSearchIngredientApplicationTypeModelFromJSONTyped(json: any, ignoreDiscriminator: boolean): CocktailSearchIngredientApplicationTypeModel {
    return json as CocktailSearchIngredientApplicationTypeModel;
}

export function CocktailSearchIngredientApplicationTypeModelToJSON(value?: CocktailSearchIngredientApplicationTypeModel | null): any {
    return value as any;
}

export function CocktailSearchIngredientApplicationTypeModelToJSONTyped(value: any, ignoreDiscriminator: boolean): CocktailSearchIngredientApplicationTypeModel {
    return value as CocktailSearchIngredientApplicationTypeModel;
}

