/* tslint:disable */
/* eslint-disable */
/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * 
 * @export
 */
export const CocktailDataIncludeModel = {
    MainImages: 'mainImages',
    SearchTiles: 'searchTiles',
    DescriptiveTitle: 'descriptiveTitle'
} as const;
export type CocktailDataIncludeModel = typeof CocktailDataIncludeModel[keyof typeof CocktailDataIncludeModel];


export function instanceOfCocktailDataIncludeModel(value: any): boolean {
    for (const key in CocktailDataIncludeModel) {
        if (Object.prototype.hasOwnProperty.call(CocktailDataIncludeModel, key)) {
            if (CocktailDataIncludeModel[key as keyof typeof CocktailDataIncludeModel] === value) {
                return true;
            }
        }
    }
    return false;
}

export function CocktailDataIncludeModelFromJSON(json: any): CocktailDataIncludeModel {
    return CocktailDataIncludeModelFromJSONTyped(json, false);
}

export function CocktailDataIncludeModelFromJSONTyped(json: any, ignoreDiscriminator: boolean): CocktailDataIncludeModel {
    return json as CocktailDataIncludeModel;
}

export function CocktailDataIncludeModelToJSON(value?: CocktailDataIncludeModel | null): any {
    return value as any;
}

export function CocktailDataIncludeModelToJSONTyped(value: any, ignoreDiscriminator: boolean): CocktailDataIncludeModel {
    return value as CocktailDataIncludeModel;
}

