/* tslint:disable */
/* eslint-disable */
/**
 * Cezzi\'s Cocktails AI Search API
 * An AI-powered cocktail search API using semantic search and embeddings.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { CocktailModelOutput } from './cocktailModelOutput';
import {
    CocktailModelOutputFromJSON,
    CocktailModelOutputFromJSONTyped,
    CocktailModelOutputToJSON,
    CocktailModelOutputToJSONTyped,
} from './cocktailModelOutput';

/**
 * 
 * @export
 * @interface CocktailsSearchRs
 */
export interface CocktailsSearchRs {
    /**
     * List of cocktails returned from the search
     * @type {Array<CocktailModelOutput>}
     * @memberof CocktailsSearchRs
     */
    items: Array<CocktailModelOutput>;
}

/**
 * Check if a given object implements the CocktailsSearchRs interface.
 */
export function instanceOfCocktailsSearchRs(value: object): value is CocktailsSearchRs {
    if (!('items' in value) || value['items'] === undefined) return false;
    return true;
}

export function CocktailsSearchRsFromJSON(json: any): CocktailsSearchRs {
    return CocktailsSearchRsFromJSONTyped(json, false);
}

export function CocktailsSearchRsFromJSONTyped(json: any, ignoreDiscriminator: boolean): CocktailsSearchRs {
    if (json == null) {
        return json;
    }
    return {
        
        'items': ((json['items'] as Array<any>).map(CocktailModelOutputFromJSON)),
    };
}

export function CocktailsSearchRsToJSON(json: any): CocktailsSearchRs {
    return CocktailsSearchRsToJSONTyped(json, false);
}

export function CocktailsSearchRsToJSONTyped(value?: CocktailsSearchRs | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'items': ((value['items'] as Array<any>).map(CocktailModelOutputToJSON)),
    };
}

