/* tslint:disable */
/* eslint-disable */
/**
 * Cezzi\'s Cocktails AI Search API
 * An AI-powered cocktail search API using semantic search and embeddings.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { CocktailDescriptionChunk } from './cocktailDescriptionChunk';
import {
    CocktailDescriptionChunkFromJSON,
    CocktailDescriptionChunkFromJSONTyped,
    CocktailDescriptionChunkToJSON,
    CocktailDescriptionChunkToJSONTyped,
} from './cocktailDescriptionChunk';
import type { CocktailEmbeddingModel } from './cocktailEmbeddingModel';
import {
    CocktailEmbeddingModelFromJSON,
    CocktailEmbeddingModelFromJSONTyped,
    CocktailEmbeddingModelToJSON,
    CocktailEmbeddingModelToJSONTyped,
} from './cocktailEmbeddingModel';
import type { CocktailSearchKeywords } from './cocktailSearchKeywords';
import {
    CocktailSearchKeywordsFromJSON,
    CocktailSearchKeywordsFromJSONTyped,
    CocktailSearchKeywordsToJSON,
    CocktailSearchKeywordsToJSONTyped,
} from './cocktailSearchKeywords';

/**
 * Request model for embedding cocktail description chunks into the vector database.
 * @export
 * @interface CocktailEmbeddingRq
 */
export interface CocktailEmbeddingRq {
    /**
     * List of text chunks to be embedded
     * @type {Array<CocktailDescriptionChunk>}
     * @memberof CocktailEmbeddingRq
     */
    contentChunks: Array<CocktailDescriptionChunk>;
    /**
     * 
     * @type {CocktailEmbeddingModel}
     * @memberof CocktailEmbeddingRq
     */
    cocktailEmbeddingModel: CocktailEmbeddingModel;
    /**
     * 
     * @type {CocktailSearchKeywords}
     * @memberof CocktailEmbeddingRq
     */
    cocktailKeywords?: CocktailSearchKeywords;
}

/**
 * Check if a given object implements the CocktailEmbeddingRq interface.
 */
export function instanceOfCocktailEmbeddingRq(value: object): value is CocktailEmbeddingRq {
    if (!('contentChunks' in value) || value['contentChunks'] === undefined) return false;
    if (!('cocktailEmbeddingModel' in value) || value['cocktailEmbeddingModel'] === undefined) return false;
    return true;
}

export function CocktailEmbeddingRqFromJSON(json: any): CocktailEmbeddingRq {
    return CocktailEmbeddingRqFromJSONTyped(json, false);
}

export function CocktailEmbeddingRqFromJSONTyped(json: any, ignoreDiscriminator: boolean): CocktailEmbeddingRq {
    if (json == null) {
        return json;
    }
    return {
        
        'contentChunks': ((json['contentChunks'] as Array<any>).map(CocktailDescriptionChunkFromJSON)),
        'cocktailEmbeddingModel': CocktailEmbeddingModelFromJSON(json['cocktailEmbeddingModel']),
        'cocktailKeywords': json['cocktailKeywords'] == null ? undefined : CocktailSearchKeywordsFromJSON(json['cocktailKeywords']),
    };
}

export function CocktailEmbeddingRqToJSON(json: any): CocktailEmbeddingRq {
    return CocktailEmbeddingRqToJSONTyped(json, false);
}

export function CocktailEmbeddingRqToJSONTyped(value?: CocktailEmbeddingRq | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'contentChunks': ((value['contentChunks'] as Array<any>).map(CocktailDescriptionChunkToJSON)),
        'cocktailEmbeddingModel': CocktailEmbeddingModelToJSON(value['cocktailEmbeddingModel']),
        'cocktailKeywords': CocktailSearchKeywordsToJSON(value['cocktailKeywords']),
    };
}

