/* tslint:disable */
/* eslint-disable */
/**
 * Cezzi\'s Cocktails AI Search API
 * An AI-powered cocktail search API using semantic search and embeddings.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * The types of cocktail data to include in the search results.
 * @export
 * @enum {string}
 */
export enum CocktailSearchDataIncludeModel {
    MainImages = 'mainImages',
    SearchTiles = 'searchTiles',
    DescriptiveTitle = 'descriptiveTitle'
}


export function instanceOfCocktailSearchDataIncludeModel(value: any): boolean {
    for (const key in CocktailSearchDataIncludeModel) {
        if (Object.prototype.hasOwnProperty.call(CocktailSearchDataIncludeModel, key)) {
            if (CocktailSearchDataIncludeModel[key as keyof typeof CocktailSearchDataIncludeModel] === value) {
                return true;
            }
        }
    }
    return false;
}

export function CocktailSearchDataIncludeModelFromJSON(json: any): CocktailSearchDataIncludeModel {
    return CocktailSearchDataIncludeModelFromJSONTyped(json, false);
}

export function CocktailSearchDataIncludeModelFromJSONTyped(json: any, ignoreDiscriminator: boolean): CocktailSearchDataIncludeModel {
    return json as CocktailSearchDataIncludeModel;
}

export function CocktailSearchDataIncludeModelToJSON(value?: CocktailSearchDataIncludeModel | null): any {
    return value as any;
}

export function CocktailSearchDataIncludeModelToJSONTyped(value: any, ignoreDiscriminator: boolean): CocktailSearchDataIncludeModel {
    return value as CocktailSearchDataIncludeModel;
}

