/* tslint:disable */
/* eslint-disable */
/**
 * Cezzi\'s Cocktails AI Search API
 * An AI-powered cocktail search API using semantic search and embeddings.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * The types of ingredients used in cocktails.
 * @export
 * @enum {string}
 */
export enum CocktailSearchIngredientTypeModel {
    Herb = 'herb',
    Fruit = 'fruit',
    Juice = 'juice',
    Bitters = 'bitters',
    Syrup = 'syrup',
    Protein = 'protein',
    Flowers = 'flowers',
    Sauce = 'sauce',
    Vegetable = 'vegetable',
    Dilution = 'dilution',
    Beer = 'beer',
    Spirit = 'spirit',
    Liqueur = 'liqueur',
    Wine = 'wine',
    Champagne = 'champagne'
}


export function instanceOfCocktailSearchIngredientTypeModel(value: any): boolean {
    for (const key in CocktailSearchIngredientTypeModel) {
        if (Object.prototype.hasOwnProperty.call(CocktailSearchIngredientTypeModel, key)) {
            if (CocktailSearchIngredientTypeModel[key as keyof typeof CocktailSearchIngredientTypeModel] === value) {
                return true;
            }
        }
    }
    return false;
}

export function CocktailSearchIngredientTypeModelFromJSON(json: any): CocktailSearchIngredientTypeModel {
    return CocktailSearchIngredientTypeModelFromJSONTyped(json, false);
}

export function CocktailSearchIngredientTypeModelFromJSONTyped(json: any, ignoreDiscriminator: boolean): CocktailSearchIngredientTypeModel {
    return json as CocktailSearchIngredientTypeModel;
}

export function CocktailSearchIngredientTypeModelToJSON(value?: CocktailSearchIngredientTypeModel | null): any {
    return value as any;
}

export function CocktailSearchIngredientTypeModelToJSONTyped(value: any, ignoreDiscriminator: boolean): CocktailSearchIngredientTypeModel {
    return value as CocktailSearchIngredientTypeModel;
}

