/* tslint:disable */
/* eslint-disable */
/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CocktailVectorSearchResult
 */
export interface CocktailVectorSearchResult {
    /**
     * Score of the search result
     * @type {number}
     * @memberof CocktailVectorSearchResult
     */
    score: number;
}

/**
 * Check if a given object implements the CocktailVectorSearchResult interface.
 */
export function instanceOfCocktailVectorSearchResult(value: object): value is CocktailVectorSearchResult {
    if (!('score' in value) || value['score'] === undefined) return false;
    return true;
}

export function CocktailVectorSearchResultFromJSON(json: any): CocktailVectorSearchResult {
    return CocktailVectorSearchResultFromJSONTyped(json, false);
}

export function CocktailVectorSearchResultFromJSONTyped(json: any, ignoreDiscriminator: boolean): CocktailVectorSearchResult {
    if (json == null) {
        return json;
    }
    return {
        
        'score': json['score'],
    };
}

export function CocktailVectorSearchResultToJSON(json: any): CocktailVectorSearchResult {
    return CocktailVectorSearchResultToJSONTyped(json, false);
}

export function CocktailVectorSearchResultToJSONTyped(value?: CocktailVectorSearchResult | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'score': value['score'],
    };
}

