/* tslint:disable */
/* eslint-disable */
/**
 * Cezzi\'s Cocktails AI Search API
 * An AI-powered cocktail search API using semantic search and embeddings.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { CocktailDescriptionChunk } from './cocktailDescriptionChunk';
import {
    CocktailDescriptionChunkFromJSON,
    CocktailDescriptionChunkFromJSONTyped,
    CocktailDescriptionChunkToJSON,
    CocktailDescriptionChunkToJSONTyped,
} from './cocktailDescriptionChunk';
import type { CocktailEmbeddingModel } from './cocktailEmbeddingModel';
import {
    CocktailEmbeddingModelFromJSON,
    CocktailEmbeddingModelFromJSONTyped,
    CocktailEmbeddingModelToJSON,
    CocktailEmbeddingModelToJSONTyped,
} from './cocktailEmbeddingModel';
import type { CocktailKeywords } from './cocktailKeywords';
import {
    CocktailKeywordsFromJSON,
    CocktailKeywordsFromJSONTyped,
    CocktailKeywordsToJSON,
    CocktailKeywordsToJSONTyped,
} from './cocktailKeywords';

/**
 * Request model for embedding cocktail description chunks into the vector database.
 * @export
 * @interface CocktailEmbeddingRq
 */
export interface CocktailEmbeddingRq {
    /**
     * List of text chunks to be embedded
     * @type {Array<CocktailDescriptionChunk>}
     * @memberof CocktailEmbeddingRq
     */
    content_chunks: Array<CocktailDescriptionChunk>;
    /**
     * 
     * @type {CocktailEmbeddingModel}
     * @memberof CocktailEmbeddingRq
     */
    cocktail_embedding_model: CocktailEmbeddingModel;
    /**
     * 
     * @type {CocktailKeywords}
     * @memberof CocktailEmbeddingRq
     */
    cocktail_keywords?: CocktailKeywords;
}

/**
 * Check if a given object implements the CocktailEmbeddingRq interface.
 */
export function instanceOfCocktailEmbeddingRq(value: object): value is CocktailEmbeddingRq {
    if (!('content_chunks' in value) || value['content_chunks'] === undefined) return false;
    if (!('cocktail_embedding_model' in value) || value['cocktail_embedding_model'] === undefined) return false;
    return true;
}

export function CocktailEmbeddingRqFromJSON(json: any): CocktailEmbeddingRq {
    return CocktailEmbeddingRqFromJSONTyped(json, false);
}

export function CocktailEmbeddingRqFromJSONTyped(json: any, ignoreDiscriminator: boolean): CocktailEmbeddingRq {
    if (json == null) {
        return json;
    }
    return {
        
        'content_chunks': ((json['content_chunks'] as Array<any>).map(CocktailDescriptionChunkFromJSON)),
        'cocktail_embedding_model': CocktailEmbeddingModelFromJSON(json['cocktail_embedding_model']),
        'cocktail_keywords': json['cocktail_keywords'] == null ? undefined : CocktailKeywordsFromJSON(json['cocktail_keywords']),
    };
}

export function CocktailEmbeddingRqToJSON(json: any): CocktailEmbeddingRq {
    return CocktailEmbeddingRqToJSONTyped(json, false);
}

export function CocktailEmbeddingRqToJSONTyped(value?: CocktailEmbeddingRq | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'content_chunks': ((value['content_chunks'] as Array<any>).map(CocktailDescriptionChunkToJSON)),
        'cocktail_embedding_model': CocktailEmbeddingModelToJSON(value['cocktail_embedding_model']),
        'cocktail_keywords': CocktailKeywordsToJSON(value['cocktail_keywords']),
    };
}

