/* tslint:disable */
/* eslint-disable */
/**
 * Cezzi\'s Cocktails AI Search API
 * An AI-powered cocktail search API using semantic search and embeddings.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * The requirement types for cocktail ingredients.
 * @export
 * @enum {string}
 */
export enum CocktailSearchIngredientRequirementTypeModel {
    None = 'none',
    Optional = 'optional',
    Required = 'required'
}


export function instanceOfCocktailSearchIngredientRequirementTypeModel(value: any): boolean {
    for (const key in CocktailSearchIngredientRequirementTypeModel) {
        if (Object.prototype.hasOwnProperty.call(CocktailSearchIngredientRequirementTypeModel, key)) {
            if (CocktailSearchIngredientRequirementTypeModel[key as keyof typeof CocktailSearchIngredientRequirementTypeModel] === value) {
                return true;
            }
        }
    }
    return false;
}

export function CocktailSearchIngredientRequirementTypeModelFromJSON(json: any): CocktailSearchIngredientRequirementTypeModel {
    return CocktailSearchIngredientRequirementTypeModelFromJSONTyped(json, false);
}

export function CocktailSearchIngredientRequirementTypeModelFromJSONTyped(json: any, ignoreDiscriminator: boolean): CocktailSearchIngredientRequirementTypeModel {
    return json as CocktailSearchIngredientRequirementTypeModel;
}

export function CocktailSearchIngredientRequirementTypeModelToJSON(value?: CocktailSearchIngredientRequirementTypeModel | null): any {
    return value as any;
}

export function CocktailSearchIngredientRequirementTypeModelToJSONTyped(value: any, ignoreDiscriminator: boolean): CocktailSearchIngredientRequirementTypeModel {
    return value as CocktailSearchIngredientRequirementTypeModel;
}

