/* tslint:disable */
/* eslint-disable */
/**
 * Cezzi\'s Cocktails AI Search API
 * An AI-powered cocktail search API using semantic search and embeddings.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * The preparation types for cocktail ingredients.
 * @export
 * @enum {string}
 */
export enum CocktailSearchPreparationTypeModel {
    None = 'none',
    Chilled = 'chilled',
    FreshlySqueezed = 'freshlySqueezed',
    PeeledAndJuiced = 'peeledAndJuiced',
    FreshlyGrated = 'freshlyGrated',
    Quartered = 'quartered',
    FreshPressed = 'freshPressed'
}


export function instanceOfCocktailSearchPreparationTypeModel(value: any): boolean {
    for (const key in CocktailSearchPreparationTypeModel) {
        if (Object.prototype.hasOwnProperty.call(CocktailSearchPreparationTypeModel, key)) {
            if (CocktailSearchPreparationTypeModel[key as keyof typeof CocktailSearchPreparationTypeModel] === value) {
                return true;
            }
        }
    }
    return false;
}

export function CocktailSearchPreparationTypeModelFromJSON(json: any): CocktailSearchPreparationTypeModel {
    return CocktailSearchPreparationTypeModelFromJSONTyped(json, false);
}

export function CocktailSearchPreparationTypeModelFromJSONTyped(json: any, ignoreDiscriminator: boolean): CocktailSearchPreparationTypeModel {
    return json as CocktailSearchPreparationTypeModel;
}

export function CocktailSearchPreparationTypeModelToJSON(value?: CocktailSearchPreparationTypeModel | null): any {
    return value as any;
}

export function CocktailSearchPreparationTypeModelToJSONTyped(value: any, ignoreDiscriminator: boolean): CocktailSearchPreparationTypeModel {
    return value as CocktailSearchPreparationTypeModel;
}

