/* tslint:disable */
/* eslint-disable */
/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { CocktailVectorSearchResult } from './cocktailVectorSearchResult';
import {
    CocktailVectorSearchResultFromJSON,
    CocktailVectorSearchResultFromJSONTyped,
    CocktailVectorSearchResultToJSON,
    CocktailVectorSearchResultToJSONTyped,
} from './cocktailVectorSearchResult';

/**
 * 
 * @export
 * @interface CocktailSearchStatistics
 */
export interface CocktailSearchStatistics {
    /**
     * Total score of the search result
     * @type {number}
     * @memberof CocktailSearchStatistics
     */
    total_score: number;
    /**
     * List of hit results with their scores
     * @type {Array<CocktailVectorSearchResult>}
     * @memberof CocktailSearchStatistics
     */
    hit_results?: Array<CocktailVectorSearchResult>;
}

/**
 * Check if a given object implements the CocktailSearchStatistics interface.
 */
export function instanceOfCocktailSearchStatistics(value: object): value is CocktailSearchStatistics {
    if (!('total_score' in value) || value['total_score'] === undefined) return false;
    return true;
}

export function CocktailSearchStatisticsFromJSON(json: any): CocktailSearchStatistics {
    return CocktailSearchStatisticsFromJSONTyped(json, false);
}

export function CocktailSearchStatisticsFromJSONTyped(json: any, ignoreDiscriminator: boolean): CocktailSearchStatistics {
    if (json == null) {
        return json;
    }
    return {
        
        'total_score': json['total_score'],
        'hit_results': json['hit_results'] == null ? undefined : ((json['hit_results'] as Array<any>).map(CocktailVectorSearchResultFromJSON)),
    };
}

export function CocktailSearchStatisticsToJSON(json: any): CocktailSearchStatistics {
    return CocktailSearchStatisticsToJSONTyped(json, false);
}

export function CocktailSearchStatisticsToJSONTyped(value?: CocktailSearchStatistics | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'total_score': value['total_score'],
        'hit_results': value['hit_results'] == null ? undefined : ((value['hit_results'] as Array<any>).map(CocktailVectorSearchResultToJSON)),
    };
}

