/* tslint:disable */
/* eslint-disable */
/**
 * Cezzi\'s Cocktails AI Search API
 * An AI-powered cocktail search API using semantic search and embeddings.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { GlasswareTypeModel } from './glasswareTypeModel';
import {
    GlasswareTypeModelFromJSON,
    GlasswareTypeModelFromJSONTyped,
    GlasswareTypeModelToJSON,
    GlasswareTypeModelToJSONTyped,
} from './glasswareTypeModel';
import type { CocktailSearchStatistics } from './cocktailSearchStatistics';
import {
    CocktailSearchStatisticsFromJSON,
    CocktailSearchStatisticsFromJSONTyped,
    CocktailSearchStatisticsToJSON,
    CocktailSearchStatisticsToJSONTyped,
} from './cocktailSearchStatistics';
import type { IngredientModel } from './ingredientModel';
import {
    IngredientModelFromJSON,
    IngredientModelFromJSONTyped,
    IngredientModelToJSON,
    IngredientModelToJSONTyped,
} from './ingredientModel';

/**
 * 
 * @export
 * @interface CocktailModelOutput
 */
export interface CocktailModelOutput {
    /**
     * Unique identifier for the cocktail
     * @type {string}
     * @memberof CocktailModelOutput
     */
    id: string;
    /**
     * Title of the cocktail
     * @type {string}
     * @memberof CocktailModelOutput
     */
    title: string;
    /**
     * Descriptive title of the cocktail
     * @type {string}
     * @memberof CocktailModelOutput
     */
    descriptiveTitle: string;
    /**
     * Rating of the cocktail
     * @type {number}
     * @memberof CocktailModelOutput
     */
    rating: number;
    /**
     * List of ingredients in the cocktail
     * @type {Array<IngredientModel>}
     * @memberof CocktailModelOutput
     */
    ingredients: Array<IngredientModel>;
    /**
     * Indicates if the cocktail is an IBA official cocktail
     * @type {boolean}
     * @memberof CocktailModelOutput
     */
    isIba: boolean;
    /**
     * Number of servings
     * @type {number}
     * @memberof CocktailModelOutput
     */
    serves: number;
    /**
     * Preparation time in minutes
     * @type {number}
     * @memberof CocktailModelOutput
     */
    prepTimeMinutes: number;
    /**
     * Search tiles associated with the cocktail
     * @type {Array<string>}
     * @memberof CocktailModelOutput
     */
    searchTiles: Array<string>;
    /**
     * List of glassware types used for the cocktail
     * @type {Array<GlasswareTypeModel>}
     * @memberof CocktailModelOutput
     */
    glassware: Array<GlasswareTypeModel>;
    /**
     * 
     * @type {CocktailSearchStatistics}
     * @memberof CocktailModelOutput
     */
    search_statistics?: CocktailSearchStatistics;
}

/**
 * Check if a given object implements the CocktailModelOutput interface.
 */
export function instanceOfCocktailModelOutput(value: object): value is CocktailModelOutput {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('title' in value) || value['title'] === undefined) return false;
    if (!('descriptiveTitle' in value) || value['descriptiveTitle'] === undefined) return false;
    if (!('rating' in value) || value['rating'] === undefined) return false;
    if (!('ingredients' in value) || value['ingredients'] === undefined) return false;
    if (!('isIba' in value) || value['isIba'] === undefined) return false;
    if (!('serves' in value) || value['serves'] === undefined) return false;
    if (!('prepTimeMinutes' in value) || value['prepTimeMinutes'] === undefined) return false;
    if (!('searchTiles' in value) || value['searchTiles'] === undefined) return false;
    if (!('glassware' in value) || value['glassware'] === undefined) return false;
    return true;
}

export function CocktailModelOutputFromJSON(json: any): CocktailModelOutput {
    return CocktailModelOutputFromJSONTyped(json, false);
}

export function CocktailModelOutputFromJSONTyped(json: any, ignoreDiscriminator: boolean): CocktailModelOutput {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'title': json['title'],
        'descriptiveTitle': json['descriptiveTitle'],
        'rating': json['rating'],
        'ingredients': ((json['ingredients'] as Array<any>).map(IngredientModelFromJSON)),
        'isIba': json['isIba'],
        'serves': json['serves'],
        'prepTimeMinutes': json['prepTimeMinutes'],
        'searchTiles': json['searchTiles'],
        'glassware': ((json['glassware'] as Array<any>).map(GlasswareTypeModelFromJSON)),
        'search_statistics': json['search_statistics'] == null ? undefined : CocktailSearchStatisticsFromJSON(json['search_statistics']),
    };
}

export function CocktailModelOutputToJSON(json: any): CocktailModelOutput {
    return CocktailModelOutputToJSONTyped(json, false);
}

export function CocktailModelOutputToJSONTyped(value?: CocktailModelOutput | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'title': value['title'],
        'descriptiveTitle': value['descriptiveTitle'],
        'rating': value['rating'],
        'ingredients': ((value['ingredients'] as Array<any>).map(IngredientModelToJSON)),
        'isIba': value['isIba'],
        'serves': value['serves'],
        'prepTimeMinutes': value['prepTimeMinutes'],
        'searchTiles': value['searchTiles'],
        'glassware': ((value['glassware'] as Array<any>).map(GlasswareTypeModelToJSON)),
        'search_statistics': CocktailSearchStatisticsToJSON(value['search_statistics']),
    };
}

