/* tslint:disable */
/* eslint-disable */
/**
 * Cezzi\'s Cocktails AI Search API
 * An AI-powered cocktail search API using semantic search and embeddings.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Keyword metadata for Qdrant payload filtering. Not returned in search responses.
 * @export
 * @interface CocktailKeywords
 */
export interface CocktailKeywords {
    /**
     * Base spirit keywords (e.g. gin, rum, bourbon)
     * @type {Array<string>}
     * @memberof CocktailKeywords
     */
    keywordsBaseSpirit?: Array<string>;
    /**
     * Spirit subtype keywords (e.g. aged-rum, islay-scotch)
     * @type {Array<string>}
     * @memberof CocktailKeywords
     */
    keywordsSpiritSubtype?: Array<string>;
    /**
     * Flavor profile keywords (e.g. bitter, sweet, citrus)
     * @type {Array<string>}
     * @memberof CocktailKeywords
     */
    keywordsFlavorProfile?: Array<string>;
    /**
     * Cocktail family keywords (e.g. sour, tiki, negroni)
     * @type {Array<string>}
     * @memberof CocktailKeywords
     */
    keywordsCocktailFamily?: Array<string>;
    /**
     * Technique keywords (e.g. shaken, stirred, built)
     * @type {Array<string>}
     * @memberof CocktailKeywords
     */
    keywordsTechnique?: Array<string>;
    /**
     * Strength keyword (light, medium, strong)
     * @type {string}
     * @memberof CocktailKeywords
     */
    keywordsStrength?: string;
    /**
     * Temperature keyword (cold, frozen, warm)
     * @type {string}
     * @memberof CocktailKeywords
     */
    keywordsTemperature?: string;
    /**
     * Season keywords (e.g. summer, winter, all-season)
     * @type {Array<string>}
     * @memberof CocktailKeywords
     */
    keywordsSeason?: Array<string>;
    /**
     * Occasion keywords (e.g. aperitif, party, brunch)
     * @type {Array<string>}
     * @memberof CocktailKeywords
     */
    keywordsOccasion?: Array<string>;
    /**
     * Mood keywords (e.g. sophisticated, fun, refreshing)
     * @type {Array<string>}
     * @memberof CocktailKeywords
     */
    keywordsMood?: Array<string>;
    /**
     * Additional search terms
     * @type {Array<string>}
     * @memberof CocktailKeywords
     */
    keywordsSearchTerms?: Array<string>;
}

/**
 * Check if a given object implements the CocktailKeywords interface.
 */
export function instanceOfCocktailKeywords(value: object): value is CocktailKeywords {
    return true;
}

export function CocktailKeywordsFromJSON(json: any): CocktailKeywords {
    return CocktailKeywordsFromJSONTyped(json, false);
}

export function CocktailKeywordsFromJSONTyped(json: any, ignoreDiscriminator: boolean): CocktailKeywords {
    if (json == null) {
        return json;
    }
    return {
        
        'keywordsBaseSpirit': json['keywordsBaseSpirit'] == null ? undefined : json['keywordsBaseSpirit'],
        'keywordsSpiritSubtype': json['keywordsSpiritSubtype'] == null ? undefined : json['keywordsSpiritSubtype'],
        'keywordsFlavorProfile': json['keywordsFlavorProfile'] == null ? undefined : json['keywordsFlavorProfile'],
        'keywordsCocktailFamily': json['keywordsCocktailFamily'] == null ? undefined : json['keywordsCocktailFamily'],
        'keywordsTechnique': json['keywordsTechnique'] == null ? undefined : json['keywordsTechnique'],
        'keywordsStrength': json['keywordsStrength'] == null ? undefined : json['keywordsStrength'],
        'keywordsTemperature': json['keywordsTemperature'] == null ? undefined : json['keywordsTemperature'],
        'keywordsSeason': json['keywordsSeason'] == null ? undefined : json['keywordsSeason'],
        'keywordsOccasion': json['keywordsOccasion'] == null ? undefined : json['keywordsOccasion'],
        'keywordsMood': json['keywordsMood'] == null ? undefined : json['keywordsMood'],
        'keywordsSearchTerms': json['keywordsSearchTerms'] == null ? undefined : json['keywordsSearchTerms'],
    };
}

export function CocktailKeywordsToJSON(json: any): CocktailKeywords {
    return CocktailKeywordsToJSONTyped(json, false);
}

export function CocktailKeywordsToJSONTyped(value?: CocktailKeywords | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'keywordsBaseSpirit': value['keywordsBaseSpirit'],
        'keywordsSpiritSubtype': value['keywordsSpiritSubtype'],
        'keywordsFlavorProfile': value['keywordsFlavorProfile'],
        'keywordsCocktailFamily': value['keywordsCocktailFamily'],
        'keywordsTechnique': value['keywordsTechnique'],
        'keywordsStrength': value['keywordsStrength'],
        'keywordsTemperature': value['keywordsTemperature'],
        'keywordsSeason': value['keywordsSeason'],
        'keywordsOccasion': value['keywordsOccasion'],
        'keywordsMood': value['keywordsMood'],
        'keywordsSearchTerms': value['keywordsSearchTerms'],
    };
}

