/* tslint:disable */
/* eslint-disable */
/**
 * Cezzi\'s Cocktails AI Search API
 * An AI-powered cocktail search API using semantic search and embeddings.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * The unit of measurment types for cocktail ingredients.
 * @export
 * @enum {string}
 */
export enum CocktailSearchUofMTypeModel {
    None = 'none',
    Ounces = 'ounces',
    Dashes = 'dashes',
    Tablespoon = 'tablespoon',
    Topoff = 'topoff',
    Item = 'item',
    Teaspoon = 'teaspoon',
    ToTaste = 'toTaste',
    Barspoon = 'barspoon',
    Cups = 'cups',
    Splash = 'splash',
    Discretion = 'discretion'
}


export function instanceOfCocktailSearchUofMTypeModel(value: any): boolean {
    for (const key in CocktailSearchUofMTypeModel) {
        if (Object.prototype.hasOwnProperty.call(CocktailSearchUofMTypeModel, key)) {
            if (CocktailSearchUofMTypeModel[key as keyof typeof CocktailSearchUofMTypeModel] === value) {
                return true;
            }
        }
    }
    return false;
}

export function CocktailSearchUofMTypeModelFromJSON(json: any): CocktailSearchUofMTypeModel {
    return CocktailSearchUofMTypeModelFromJSONTyped(json, false);
}

export function CocktailSearchUofMTypeModelFromJSONTyped(json: any, ignoreDiscriminator: boolean): CocktailSearchUofMTypeModel {
    return json as CocktailSearchUofMTypeModel;
}

export function CocktailSearchUofMTypeModelToJSON(value?: CocktailSearchUofMTypeModel | null): any {
    return value as any;
}

export function CocktailSearchUofMTypeModelToJSONTyped(value: any, ignoreDiscriminator: boolean): CocktailSearchUofMTypeModel {
    return value as CocktailSearchUofMTypeModel;
}

