/* tslint:disable */
/* eslint-disable */
/**
 * Cezzi\'s Cocktails AI Search API
 * An AI-powered cocktail search API using semantic search and embeddings.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { CocktailSearchIngredientModel } from './cocktailSearchIngredientModel';
import {
    CocktailSearchIngredientModelFromJSON,
    CocktailSearchIngredientModelFromJSONTyped,
    CocktailSearchIngredientModelToJSON,
    CocktailSearchIngredientModelToJSONTyped,
} from './cocktailSearchIngredientModel';
import type { CocktailSearchGlasswareTypeModel } from './cocktailSearchGlasswareTypeModel';
import {
    CocktailSearchGlasswareTypeModelFromJSON,
    CocktailSearchGlasswareTypeModelFromJSONTyped,
    CocktailSearchGlasswareTypeModelToJSON,
    CocktailSearchGlasswareTypeModelToJSONTyped,
} from './cocktailSearchGlasswareTypeModel';

/**
 * Model representing the cocktail embedding data structure used for vector search and storage.
 * @export
 * @interface CocktailEmbeddingModel
 */
export interface CocktailEmbeddingModel {
    /**
     * Unique identifier for the cocktail
     * @type {string}
     * @memberof CocktailEmbeddingModel
     */
    id: string;
    /**
     * Title of the cocktail
     * @type {string}
     * @memberof CocktailEmbeddingModel
     */
    title: string;
    /**
     * Descriptive title of the cocktail
     * @type {string}
     * @memberof CocktailEmbeddingModel
     */
    descriptiveTitle: string;
    /**
     * Rating of the cocktail
     * @type {number}
     * @memberof CocktailEmbeddingModel
     */
    rating: number;
    /**
     * List of ingredients in the cocktail
     * @type {Array<CocktailSearchIngredientModel>}
     * @memberof CocktailEmbeddingModel
     */
    ingredients: Array<CocktailSearchIngredientModel>;
    /**
     * Indicates if the cocktail is an IBA official cocktail
     * @type {boolean}
     * @memberof CocktailEmbeddingModel
     */
    isIba: boolean;
    /**
     * Number of servings
     * @type {number}
     * @memberof CocktailEmbeddingModel
     */
    serves: number;
    /**
     * Preparation time in minutes
     * @type {number}
     * @memberof CocktailEmbeddingModel
     */
    prepTimeMinutes: number;
    /**
     * Search tiles associated with the cocktail
     * @type {Array<string>}
     * @memberof CocktailEmbeddingModel
     */
    searchTiles: Array<string>;
    /**
     * List of glassware types used for the cocktail
     * @type {Array<CocktailSearchGlasswareTypeModel>}
     * @memberof CocktailEmbeddingModel
     */
    glassware: Array<CocktailSearchGlasswareTypeModel>;
}

/**
 * Check if a given object implements the CocktailEmbeddingModel interface.
 */
export function instanceOfCocktailEmbeddingModel(value: object): value is CocktailEmbeddingModel {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('title' in value) || value['title'] === undefined) return false;
    if (!('descriptiveTitle' in value) || value['descriptiveTitle'] === undefined) return false;
    if (!('rating' in value) || value['rating'] === undefined) return false;
    if (!('ingredients' in value) || value['ingredients'] === undefined) return false;
    if (!('isIba' in value) || value['isIba'] === undefined) return false;
    if (!('serves' in value) || value['serves'] === undefined) return false;
    if (!('prepTimeMinutes' in value) || value['prepTimeMinutes'] === undefined) return false;
    if (!('searchTiles' in value) || value['searchTiles'] === undefined) return false;
    if (!('glassware' in value) || value['glassware'] === undefined) return false;
    return true;
}

export function CocktailEmbeddingModelFromJSON(json: any): CocktailEmbeddingModel {
    return CocktailEmbeddingModelFromJSONTyped(json, false);
}

export function CocktailEmbeddingModelFromJSONTyped(json: any, ignoreDiscriminator: boolean): CocktailEmbeddingModel {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'title': json['title'],
        'descriptiveTitle': json['descriptiveTitle'],
        'rating': json['rating'],
        'ingredients': ((json['ingredients'] as Array<any>).map(CocktailSearchIngredientModelFromJSON)),
        'isIba': json['isIba'],
        'serves': json['serves'],
        'prepTimeMinutes': json['prepTimeMinutes'],
        'searchTiles': json['searchTiles'],
        'glassware': ((json['glassware'] as Array<any>).map(CocktailSearchGlasswareTypeModelFromJSON)),
    };
}

export function CocktailEmbeddingModelToJSON(json: any): CocktailEmbeddingModel {
    return CocktailEmbeddingModelToJSONTyped(json, false);
}

export function CocktailEmbeddingModelToJSONTyped(value?: CocktailEmbeddingModel | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'title': value['title'],
        'descriptiveTitle': value['descriptiveTitle'],
        'rating': value['rating'],
        'ingredients': ((value['ingredients'] as Array<any>).map(CocktailSearchIngredientModelToJSON)),
        'isIba': value['isIba'],
        'serves': value['serves'],
        'prepTimeMinutes': value['prepTimeMinutes'],
        'searchTiles': value['searchTiles'],
        'glassware': ((value['glassware'] as Array<any>).map(CocktailSearchGlasswareTypeModelToJSON)),
    };
}

