/* tslint:disable */
/* eslint-disable */
/**
 * Cezzi\'s Cocktails AI Search API
 * An AI-powered cocktail search API using semantic search and embeddings.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { CocktailSearchIngredientRequirementTypeModel } from './cocktailSearchIngredientRequirementTypeModel';
import {
    CocktailSearchIngredientRequirementTypeModelFromJSON,
    CocktailSearchIngredientRequirementTypeModelFromJSONTyped,
    CocktailSearchIngredientRequirementTypeModelToJSON,
    CocktailSearchIngredientRequirementTypeModelToJSONTyped,
} from './cocktailSearchIngredientRequirementTypeModel';
import type { CocktailSearchUofMTypeModel } from './cocktailSearchUofMTypeModel';
import {
    CocktailSearchUofMTypeModelFromJSON,
    CocktailSearchUofMTypeModelFromJSONTyped,
    CocktailSearchUofMTypeModelToJSON,
    CocktailSearchUofMTypeModelToJSONTyped,
} from './cocktailSearchUofMTypeModel';
import type { CocktailSearchIngredientTypeModel } from './cocktailSearchIngredientTypeModel';
import {
    CocktailSearchIngredientTypeModelFromJSON,
    CocktailSearchIngredientTypeModelFromJSONTyped,
    CocktailSearchIngredientTypeModelToJSON,
    CocktailSearchIngredientTypeModelToJSONTyped,
} from './cocktailSearchIngredientTypeModel';
import type { CocktailSearchIngredientApplicationTypeModel } from './cocktailSearchIngredientApplicationTypeModel';
import {
    CocktailSearchIngredientApplicationTypeModelFromJSON,
    CocktailSearchIngredientApplicationTypeModelFromJSONTyped,
    CocktailSearchIngredientApplicationTypeModelToJSON,
    CocktailSearchIngredientApplicationTypeModelToJSONTyped,
} from './cocktailSearchIngredientApplicationTypeModel';
import type { CocktailSearchPreparationTypeModel } from './cocktailSearchPreparationTypeModel';
import {
    CocktailSearchPreparationTypeModelFromJSON,
    CocktailSearchPreparationTypeModelFromJSONTyped,
    CocktailSearchPreparationTypeModelToJSON,
    CocktailSearchPreparationTypeModelToJSONTyped,
} from './cocktailSearchPreparationTypeModel';

/**
 * Model representing an ingredient used in a cocktail, including its name, unit of measure, requirement type, preparation, and suggestions.
 * @export
 * @interface CocktailSearchIngredientModel
 */
export interface CocktailSearchIngredientModel {
    /**
     * Name of the ingredient
     * @type {string}
     * @memberof CocktailSearchIngredientModel
     */
    name: string;
    /**
     * 
     * @type {CocktailSearchUofMTypeModel}
     * @memberof CocktailSearchIngredientModel
     */
    uoM: CocktailSearchUofMTypeModel;
    /**
     * 
     * @type {CocktailSearchIngredientRequirementTypeModel}
     * @memberof CocktailSearchIngredientModel
     */
    requirement: CocktailSearchIngredientRequirementTypeModel;
    /**
     * Display string for the ingredient
     * @type {string}
     * @memberof CocktailSearchIngredientModel
     */
    display: string;
    /**
     * Quantity of the ingredient
     * @type {number}
     * @memberof CocktailSearchIngredientModel
     */
    units: number;
    /**
     * 
     * @type {CocktailSearchPreparationTypeModel}
     * @memberof CocktailSearchIngredientModel
     */
    preparation: CocktailSearchPreparationTypeModel;
    /**
     * Suggestions for the ingredient
     * @type {string}
     * @memberof CocktailSearchIngredientModel
     */
    suggestions: string;
    /**
     * List of ingredient types
     * @type {Array<CocktailSearchIngredientTypeModel>}
     * @memberof CocktailSearchIngredientModel
     */
    types: Array<CocktailSearchIngredientTypeModel>;
    /**
     * List of ingredient applications
     * @type {Array<CocktailSearchIngredientApplicationTypeModel>}
     * @memberof CocktailSearchIngredientModel
     */
    applications: Array<CocktailSearchIngredientApplicationTypeModel>;
}



/**
 * Check if a given object implements the CocktailSearchIngredientModel interface.
 */
export function instanceOfCocktailSearchIngredientModel(value: object): value is CocktailSearchIngredientModel {
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('uoM' in value) || value['uoM'] === undefined) return false;
    if (!('requirement' in value) || value['requirement'] === undefined) return false;
    if (!('display' in value) || value['display'] === undefined) return false;
    if (!('units' in value) || value['units'] === undefined) return false;
    if (!('preparation' in value) || value['preparation'] === undefined) return false;
    if (!('suggestions' in value) || value['suggestions'] === undefined) return false;
    if (!('types' in value) || value['types'] === undefined) return false;
    if (!('applications' in value) || value['applications'] === undefined) return false;
    return true;
}

export function CocktailSearchIngredientModelFromJSON(json: any): CocktailSearchIngredientModel {
    return CocktailSearchIngredientModelFromJSONTyped(json, false);
}

export function CocktailSearchIngredientModelFromJSONTyped(json: any, ignoreDiscriminator: boolean): CocktailSearchIngredientModel {
    if (json == null) {
        return json;
    }
    return {
        
        'name': json['name'],
        'uoM': CocktailSearchUofMTypeModelFromJSON(json['uoM']),
        'requirement': CocktailSearchIngredientRequirementTypeModelFromJSON(json['requirement']),
        'display': json['display'],
        'units': json['units'],
        'preparation': CocktailSearchPreparationTypeModelFromJSON(json['preparation']),
        'suggestions': json['suggestions'],
        'types': ((json['types'] as Array<any>).map(CocktailSearchIngredientTypeModelFromJSON)),
        'applications': ((json['applications'] as Array<any>).map(CocktailSearchIngredientApplicationTypeModelFromJSON)),
    };
}

export function CocktailSearchIngredientModelToJSON(json: any): CocktailSearchIngredientModel {
    return CocktailSearchIngredientModelToJSONTyped(json, false);
}

export function CocktailSearchIngredientModelToJSONTyped(value?: CocktailSearchIngredientModel | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'name': value['name'],
        'uoM': CocktailSearchUofMTypeModelToJSON(value['uoM']),
        'requirement': CocktailSearchIngredientRequirementTypeModelToJSON(value['requirement']),
        'display': value['display'],
        'units': value['units'],
        'preparation': CocktailSearchPreparationTypeModelToJSON(value['preparation']),
        'suggestions': value['suggestions'],
        'types': ((value['types'] as Array<any>).map(CocktailSearchIngredientTypeModelToJSON)),
        'applications': ((value['applications'] as Array<any>).map(CocktailSearchIngredientApplicationTypeModelToJSON)),
    };
}

