/* tslint:disable */
/* eslint-disable */
/**
 * Cezzi\'s Cocktails AI Search API
 * An AI-powered cocktail search API using semantic search and embeddings.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { CocktailVectorSearchResult } from './cocktailVectorSearchResult';
import {
    CocktailVectorSearchResultFromJSON,
    CocktailVectorSearchResultFromJSONTyped,
    CocktailVectorSearchResultToJSON,
    CocktailVectorSearchResultToJSONTyped,
} from './cocktailVectorSearchResult';

/**
 * Model representing the search statistics for a cocktail search operation, including score metrics and hit details.
 * @export
 * @interface CocktailSearchStatistics
 */
export interface CocktailSearchStatistics {
    /**
     * Sum of all hit scores
     * @type {number}
     * @memberof CocktailSearchStatistics
     */
    totalScore: number;
    /**
     * Highest individual chunk score
     * @type {number}
     * @memberof CocktailSearchStatistics
     */
    maxScore?: number;
    /**
     * Average score across all hits
     * @type {number}
     * @memberof CocktailSearchStatistics
     */
    avgScore?: number;
    /**
     * Weighted score combining avg with hit count boost
     * @type {number}
     * @memberof CocktailSearchStatistics
     */
    weightedScore?: number;
    /**
     * Number of matching chunks
     * @type {number}
     * @memberof CocktailSearchStatistics
     */
    hitCount?: number;
    /**
     * List of hit results with their scores
     * @type {Array<CocktailVectorSearchResult>}
     * @memberof CocktailSearchStatistics
     */
    hitResults?: Array<CocktailVectorSearchResult>;
}

/**
 * Check if a given object implements the CocktailSearchStatistics interface.
 */
export function instanceOfCocktailSearchStatistics(value: object): value is CocktailSearchStatistics {
    if (!('totalScore' in value) || value['totalScore'] === undefined) return false;
    return true;
}

export function CocktailSearchStatisticsFromJSON(json: any): CocktailSearchStatistics {
    return CocktailSearchStatisticsFromJSONTyped(json, false);
}

export function CocktailSearchStatisticsFromJSONTyped(json: any, ignoreDiscriminator: boolean): CocktailSearchStatistics {
    if (json == null) {
        return json;
    }
    return {
        
        'totalScore': json['totalScore'],
        'maxScore': json['maxScore'] == null ? undefined : json['maxScore'],
        'avgScore': json['avgScore'] == null ? undefined : json['avgScore'],
        'weightedScore': json['weightedScore'] == null ? undefined : json['weightedScore'],
        'hitCount': json['hitCount'] == null ? undefined : json['hitCount'],
        'hitResults': json['hitResults'] == null ? undefined : ((json['hitResults'] as Array<any>).map(CocktailVectorSearchResultFromJSON)),
    };
}

export function CocktailSearchStatisticsToJSON(json: any): CocktailSearchStatistics {
    return CocktailSearchStatisticsToJSONTyped(json, false);
}

export function CocktailSearchStatisticsToJSONTyped(value?: CocktailSearchStatistics | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'totalScore': value['totalScore'],
        'maxScore': value['maxScore'],
        'avgScore': value['avgScore'],
        'weightedScore': value['weightedScore'],
        'hitCount': value['hitCount'],
        'hitResults': value['hitResults'] == null ? undefined : ((value['hitResults'] as Array<any>).map(CocktailVectorSearchResultToJSON)),
    };
}

