/* tslint:disable */
/* eslint-disable */
/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CocktailDescriptionChunk
 */
export interface CocktailDescriptionChunk {
    /**
     * Category of the description chunk
     * @type {string}
     * @memberof CocktailDescriptionChunk
     */
    category: string;
    /**
     * Textual content of the description chunk
     * @type {string}
     * @memberof CocktailDescriptionChunk
     */
    content: string;
}

/**
 * Check if a given object implements the CocktailDescriptionChunk interface.
 */
export function instanceOfCocktailDescriptionChunk(value: object): value is CocktailDescriptionChunk {
    if (!('category' in value) || value['category'] === undefined) return false;
    if (!('content' in value) || value['content'] === undefined) return false;
    return true;
}

export function CocktailDescriptionChunkFromJSON(json: any): CocktailDescriptionChunk {
    return CocktailDescriptionChunkFromJSONTyped(json, false);
}

export function CocktailDescriptionChunkFromJSONTyped(json: any, ignoreDiscriminator: boolean): CocktailDescriptionChunk {
    if (json == null) {
        return json;
    }
    return {
        
        'category': json['category'],
        'content': json['content'],
    };
}

export function CocktailDescriptionChunkToJSON(json: any): CocktailDescriptionChunk {
    return CocktailDescriptionChunkToJSONTyped(json, false);
}

export function CocktailDescriptionChunkToJSONTyped(value?: CocktailDescriptionChunk | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'category': value['category'],
        'content': value['content'],
    };
}

