/* tslint:disable */
/* eslint-disable */
/**
 * Cezzi\'s Cocktails AI Search API
 * An AI-powered cocktail search API using semantic search and embeddings.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * 
 * @export
 * @enum {string}
 */
export enum IngredientApplicationTypeModel {
    Base = 'base',
    Additional = 'additional',
    Garnishment = 'garnishment',
    Muddle = 'muddle'
}


export function instanceOfIngredientApplicationTypeModel(value: any): boolean {
    for (const key in IngredientApplicationTypeModel) {
        if (Object.prototype.hasOwnProperty.call(IngredientApplicationTypeModel, key)) {
            if (IngredientApplicationTypeModel[key as keyof typeof IngredientApplicationTypeModel] === value) {
                return true;
            }
        }
    }
    return false;
}

export function IngredientApplicationTypeModelFromJSON(json: any): IngredientApplicationTypeModel {
    return IngredientApplicationTypeModelFromJSONTyped(json, false);
}

export function IngredientApplicationTypeModelFromJSONTyped(json: any, ignoreDiscriminator: boolean): IngredientApplicationTypeModel {
    return json as IngredientApplicationTypeModel;
}

export function IngredientApplicationTypeModelToJSON(value?: IngredientApplicationTypeModel | null): any {
    return value as any;
}

export function IngredientApplicationTypeModelToJSONTyped(value: any, ignoreDiscriminator: boolean): IngredientApplicationTypeModel {
    return value as IngredientApplicationTypeModel;
}

