/* tslint:disable */
/* eslint-disable */
/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { IngredientTypeModel } from './ingredientTypeModel';
import {
    IngredientTypeModelFromJSON,
    IngredientTypeModelFromJSONTyped,
    IngredientTypeModelToJSON,
    IngredientTypeModelToJSONTyped,
} from './ingredientTypeModel';
import type { IngredientRequirementTypeModel } from './ingredientRequirementTypeModel';
import {
    IngredientRequirementTypeModelFromJSON,
    IngredientRequirementTypeModelFromJSONTyped,
    IngredientRequirementTypeModelToJSON,
    IngredientRequirementTypeModelToJSONTyped,
} from './ingredientRequirementTypeModel';
import type { PreparationTypeModel } from './preparationTypeModel';
import {
    PreparationTypeModelFromJSON,
    PreparationTypeModelFromJSONTyped,
    PreparationTypeModelToJSON,
    PreparationTypeModelToJSONTyped,
} from './preparationTypeModel';
import type { UofMTypeModel } from './uofMTypeModel';
import {
    UofMTypeModelFromJSON,
    UofMTypeModelFromJSONTyped,
    UofMTypeModelToJSON,
    UofMTypeModelToJSONTyped,
} from './uofMTypeModel';
import type { IngredientApplicationTypeModel } from './ingredientApplicationTypeModel';
import {
    IngredientApplicationTypeModelFromJSON,
    IngredientApplicationTypeModelFromJSONTyped,
    IngredientApplicationTypeModelToJSON,
    IngredientApplicationTypeModelToJSONTyped,
} from './ingredientApplicationTypeModel';

/**
 * 
 * @export
 * @interface IngredientModel
 */
export interface IngredientModel {
    /**
     * Name of the ingredient
     * @type {string}
     * @memberof IngredientModel
     */
    name: string;
    /**
     * Unit of Measure for the ingredient
     * @type {UofMTypeModel}
     * @memberof IngredientModel
     */
    uoM: UofMTypeModel;
    /**
     * Requirement type for the ingredient
     * @type {IngredientRequirementTypeModel}
     * @memberof IngredientModel
     */
    requirement: IngredientRequirementTypeModel;
    /**
     * Display string for the ingredient
     * @type {string}
     * @memberof IngredientModel
     */
    display: string;
    /**
     * Quantity of the ingredient
     * @type {number}
     * @memberof IngredientModel
     */
    units: number;
    /**
     * Preparation type for the ingredient
     * @type {PreparationTypeModel}
     * @memberof IngredientModel
     */
    preparation: PreparationTypeModel;
    /**
     * Suggestions for the ingredient
     * @type {string}
     * @memberof IngredientModel
     */
    suggestions: string;
    /**
     * List of ingredient types
     * @type {Array<IngredientTypeModel>}
     * @memberof IngredientModel
     */
    types: Array<IngredientTypeModel>;
    /**
     * List of ingredient applications
     * @type {Array<IngredientApplicationTypeModel>}
     * @memberof IngredientModel
     */
    applications: Array<IngredientApplicationTypeModel>;
}



/**
 * Check if a given object implements the IngredientModel interface.
 */
export function instanceOfIngredientModel(value: object): value is IngredientModel {
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('uoM' in value) || value['uoM'] === undefined) return false;
    if (!('requirement' in value) || value['requirement'] === undefined) return false;
    if (!('display' in value) || value['display'] === undefined) return false;
    if (!('units' in value) || value['units'] === undefined) return false;
    if (!('preparation' in value) || value['preparation'] === undefined) return false;
    if (!('suggestions' in value) || value['suggestions'] === undefined) return false;
    if (!('types' in value) || value['types'] === undefined) return false;
    if (!('applications' in value) || value['applications'] === undefined) return false;
    return true;
}

export function IngredientModelFromJSON(json: any): IngredientModel {
    return IngredientModelFromJSONTyped(json, false);
}

export function IngredientModelFromJSONTyped(json: any, ignoreDiscriminator: boolean): IngredientModel {
    if (json == null) {
        return json;
    }
    return {
        
        'name': json['name'],
        'uoM': UofMTypeModelFromJSON(json['uoM']),
        'requirement': IngredientRequirementTypeModelFromJSON(json['requirement']),
        'display': json['display'],
        'units': json['units'],
        'preparation': PreparationTypeModelFromJSON(json['preparation']),
        'suggestions': json['suggestions'],
        'types': ((json['types'] as Array<any>).map(IngredientTypeModelFromJSON)),
        'applications': ((json['applications'] as Array<any>).map(IngredientApplicationTypeModelFromJSON)),
    };
}

export function IngredientModelToJSON(json: any): IngredientModel {
    return IngredientModelToJSONTyped(json, false);
}

export function IngredientModelToJSONTyped(value?: IngredientModel | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'name': value['name'],
        'uoM': UofMTypeModelToJSON(value['uoM']),
        'requirement': IngredientRequirementTypeModelToJSON(value['requirement']),
        'display': value['display'],
        'units': value['units'],
        'preparation': PreparationTypeModelToJSON(value['preparation']),
        'suggestions': value['suggestions'],
        'types': ((value['types'] as Array<any>).map(IngredientTypeModelToJSON)),
        'applications': ((value['applications'] as Array<any>).map(IngredientApplicationTypeModelToJSON)),
    };
}

