/* tslint:disable */
/* eslint-disable */
/**
 * Cocktails Api
 * Cocktails Api
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * The keywords associated with the cocktail recipe
 * @export
 * @interface CocktailKeywordsModel
 */
export interface CocktailKeywordsModel {
    /**
     * Base spirit keywords
     * @type {Array<string>}
     * @memberof CocktailKeywordsModel
     */
    keywordsBaseSpirit: Array<string>;
    /**
     * Spirit subtype keywords
     * @type {Array<string>}
     * @memberof CocktailKeywordsModel
     */
    keywordsSpiritSubtype: Array<string>;
    /**
     * Flavor profile keywords
     * @type {Array<string>}
     * @memberof CocktailKeywordsModel
     */
    keywordsFlavorProfile: Array<string>;
    /**
     * Cocktail family keywords
     * @type {Array<string>}
     * @memberof CocktailKeywordsModel
     */
    keywordsCocktailFamily: Array<string>;
    /**
     * Technique keywords
     * @type {Array<string>}
     * @memberof CocktailKeywordsModel
     */
    keywordsTechnique: Array<string>;
    /**
     * Strength keyword
     * @type {string}
     * @memberof CocktailKeywordsModel
     */
    keywordsStrength: string;
    /**
     * Temperature keyword
     * @type {string}
     * @memberof CocktailKeywordsModel
     */
    keywordsTemperature: string;
    /**
     * Season keywords
     * @type {Array<string>}
     * @memberof CocktailKeywordsModel
     */
    keywordsSeason: Array<string>;
    /**
     * Occasion keywords
     * @type {Array<string>}
     * @memberof CocktailKeywordsModel
     */
    keywordsOccasion: Array<string>;
    /**
     * Mood keywords
     * @type {Array<string>}
     * @memberof CocktailKeywordsModel
     */
    keywordsMood: Array<string>;
    /**
     * Search terms keywords
     * @type {Array<string>}
     * @memberof CocktailKeywordsModel
     */
    keywordsSearchTerms: Array<string>;
}

/**
 * Check if a given object implements the CocktailKeywordsModel interface.
 */
export function instanceOfCocktailKeywordsModel(value: object): value is CocktailKeywordsModel {
    if (!('keywordsBaseSpirit' in value) || value['keywordsBaseSpirit'] === undefined) return false;
    if (!('keywordsSpiritSubtype' in value) || value['keywordsSpiritSubtype'] === undefined) return false;
    if (!('keywordsFlavorProfile' in value) || value['keywordsFlavorProfile'] === undefined) return false;
    if (!('keywordsCocktailFamily' in value) || value['keywordsCocktailFamily'] === undefined) return false;
    if (!('keywordsTechnique' in value) || value['keywordsTechnique'] === undefined) return false;
    if (!('keywordsStrength' in value) || value['keywordsStrength'] === undefined) return false;
    if (!('keywordsTemperature' in value) || value['keywordsTemperature'] === undefined) return false;
    if (!('keywordsSeason' in value) || value['keywordsSeason'] === undefined) return false;
    if (!('keywordsOccasion' in value) || value['keywordsOccasion'] === undefined) return false;
    if (!('keywordsMood' in value) || value['keywordsMood'] === undefined) return false;
    if (!('keywordsSearchTerms' in value) || value['keywordsSearchTerms'] === undefined) return false;
    return true;
}

export function CocktailKeywordsModelFromJSON(json: any): CocktailKeywordsModel {
    return CocktailKeywordsModelFromJSONTyped(json, false);
}

export function CocktailKeywordsModelFromJSONTyped(json: any, ignoreDiscriminator: boolean): CocktailKeywordsModel {
    if (json == null) {
        return json;
    }
    return {
        
        'keywordsBaseSpirit': json['keywordsBaseSpirit'],
        'keywordsSpiritSubtype': json['keywordsSpiritSubtype'],
        'keywordsFlavorProfile': json['keywordsFlavorProfile'],
        'keywordsCocktailFamily': json['keywordsCocktailFamily'],
        'keywordsTechnique': json['keywordsTechnique'],
        'keywordsStrength': json['keywordsStrength'],
        'keywordsTemperature': json['keywordsTemperature'],
        'keywordsSeason': json['keywordsSeason'],
        'keywordsOccasion': json['keywordsOccasion'],
        'keywordsMood': json['keywordsMood'],
        'keywordsSearchTerms': json['keywordsSearchTerms'],
    };
}

export function CocktailKeywordsModelToJSON(json: any): CocktailKeywordsModel {
    return CocktailKeywordsModelToJSONTyped(json, false);
}

export function CocktailKeywordsModelToJSONTyped(value?: CocktailKeywordsModel | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'keywordsBaseSpirit': value['keywordsBaseSpirit'],
        'keywordsSpiritSubtype': value['keywordsSpiritSubtype'],
        'keywordsFlavorProfile': value['keywordsFlavorProfile'],
        'keywordsCocktailFamily': value['keywordsCocktailFamily'],
        'keywordsTechnique': value['keywordsTechnique'],
        'keywordsStrength': value['keywordsStrength'],
        'keywordsTemperature': value['keywordsTemperature'],
        'keywordsSeason': value['keywordsSeason'],
        'keywordsOccasion': value['keywordsOccasion'],
        'keywordsMood': value['keywordsMood'],
        'keywordsSearchTerms': value['keywordsSearchTerms'],
    };
}

