/* tslint:disable */
/* eslint-disable */
/**
 * Cocktails Api
 * Cocktails Api
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { IngredientFilterModel } from './ingredientFilterModel';
import {
    IngredientFilterModelFromJSON,
    IngredientFilterModelFromJSONTyped,
    IngredientFilterModelToJSON,
    IngredientFilterModelToJSONTyped,
} from './ingredientFilterModel';

/**
 * 
 * @export
 * @interface CocktailIngredientFiltersRs
 */
export interface CocktailIngredientFiltersRs {
    /**
     * The cocktail ingredient filters for searching against recommended glassware
     * @type {Array<IngredientFilterModel>}
     * @memberof CocktailIngredientFiltersRs
     */
    glassware: Array<IngredientFilterModel>;
    /**
     * The cocktail ingredient filters for searching against spirits
     * @type {Array<any>}
     * @memberof CocktailIngredientFiltersRs
     */
    spirits: Array<any>;
    /**
     * The cocktail ingredient filters for searching against liqueurs
     * @type {Array<any>}
     * @memberof CocktailIngredientFiltersRs
     */
    liqueurs: Array<any>;
    /**
     * The cocktail ingredient filters for searching against friuts
     * @type {Array<any>}
     * @memberof CocktailIngredientFiltersRs
     */
    fruits: Array<any>;
    /**
     * The cocktail ingredient filters for searching against vegetables
     * @type {Array<any>}
     * @memberof CocktailIngredientFiltersRs
     */
    vegetables: Array<any>;
    /**
     * The cocktail ingredient filters for searching against herbs and flowers
     * @type {Array<any>}
     * @memberof CocktailIngredientFiltersRs
     */
    herbsAndFlowers: Array<any>;
    /**
     * The cocktail ingredient filters for searching against syrups and sauces
     * @type {Array<any>}
     * @memberof CocktailIngredientFiltersRs
     */
    syrupsAndSauces: Array<any>;
    /**
     * The cocktail ingredient filters for searching against bitters
     * @type {Array<any>}
     * @memberof CocktailIngredientFiltersRs
     */
    bitters: Array<any>;
    /**
     * The cocktail ingredient filters for searching against proteins
     * @type {Array<any>}
     * @memberof CocktailIngredientFiltersRs
     */
    proteins: Array<any>;
    /**
     * The cocktail ingredient filters for searching against juices
     * @type {Array<any>}
     * @memberof CocktailIngredientFiltersRs
     */
    juices: Array<any>;
    /**
     * The cocktail ingredient filters for searching against dilutions
     * @type {Array<any>}
     * @memberof CocktailIngredientFiltersRs
     */
    dilutions: Array<any>;
    /**
     * The cocktail ingredient filters for searching against beers, wines and champagnes
     * @type {Array<any>}
     * @memberof CocktailIngredientFiltersRs
     */
    beerWineChampagne: Array<any>;
    /**
     * The cocktail ingredient filters for searching against eras when cocktails were established
     * @type {Array<any>}
     * @memberof CocktailIngredientFiltersRs
     */
    eras: Array<any>;
}

/**
 * Check if a given object implements the CocktailIngredientFiltersRs interface.
 */
export function instanceOfCocktailIngredientFiltersRs(value: object): value is CocktailIngredientFiltersRs {
    if (!('glassware' in value) || value['glassware'] === undefined) return false;
    if (!('spirits' in value) || value['spirits'] === undefined) return false;
    if (!('liqueurs' in value) || value['liqueurs'] === undefined) return false;
    if (!('fruits' in value) || value['fruits'] === undefined) return false;
    if (!('vegetables' in value) || value['vegetables'] === undefined) return false;
    if (!('herbsAndFlowers' in value) || value['herbsAndFlowers'] === undefined) return false;
    if (!('syrupsAndSauces' in value) || value['syrupsAndSauces'] === undefined) return false;
    if (!('bitters' in value) || value['bitters'] === undefined) return false;
    if (!('proteins' in value) || value['proteins'] === undefined) return false;
    if (!('juices' in value) || value['juices'] === undefined) return false;
    if (!('dilutions' in value) || value['dilutions'] === undefined) return false;
    if (!('beerWineChampagne' in value) || value['beerWineChampagne'] === undefined) return false;
    if (!('eras' in value) || value['eras'] === undefined) return false;
    return true;
}

export function CocktailIngredientFiltersRsFromJSON(json: any): CocktailIngredientFiltersRs {
    return CocktailIngredientFiltersRsFromJSONTyped(json, false);
}

export function CocktailIngredientFiltersRsFromJSONTyped(json: any, ignoreDiscriminator: boolean): CocktailIngredientFiltersRs {
    if (json == null) {
        return json;
    }
    return {
        
        'glassware': ((json['glassware'] as Array<any>).map(IngredientFilterModelFromJSON)),
        'spirits': json['spirits'],
        'liqueurs': json['liqueurs'],
        'fruits': json['fruits'],
        'vegetables': json['vegetables'],
        'herbsAndFlowers': json['herbsAndFlowers'],
        'syrupsAndSauces': json['syrupsAndSauces'],
        'bitters': json['bitters'],
        'proteins': json['proteins'],
        'juices': json['juices'],
        'dilutions': json['dilutions'],
        'beerWineChampagne': json['beerWineChampagne'],
        'eras': json['eras'],
    };
}

export function CocktailIngredientFiltersRsToJSON(json: any): CocktailIngredientFiltersRs {
    return CocktailIngredientFiltersRsToJSONTyped(json, false);
}

export function CocktailIngredientFiltersRsToJSONTyped(value?: CocktailIngredientFiltersRs | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'glassware': ((value['glassware'] as Array<any>).map(IngredientFilterModelToJSON)),
        'spirits': value['spirits'],
        'liqueurs': value['liqueurs'],
        'fruits': value['fruits'],
        'vegetables': value['vegetables'],
        'herbsAndFlowers': value['herbsAndFlowers'],
        'syrupsAndSauces': value['syrupsAndSauces'],
        'bitters': value['bitters'],
        'proteins': value['proteins'],
        'juices': value['juices'],
        'dilutions': value['dilutions'],
        'beerWineChampagne': value['beerWineChampagne'],
        'eras': value['eras'],
    };
}

