/* tslint:disable */
/* eslint-disable */
/**
 * Cocktails Api
 * Cocktails Api
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { GlasswareTypeModel } from './glasswareTypeModel';
import {
    GlasswareTypeModelFromJSON,
    GlasswareTypeModelFromJSONTyped,
    GlasswareTypeModelToJSON,
    GlasswareTypeModelToJSONTyped,
} from './glasswareTypeModel';
import type { CocktailImageModel } from './cocktailImageModel';
import {
    CocktailImageModelFromJSON,
    CocktailImageModelFromJSONTyped,
    CocktailImageModelToJSON,
    CocktailImageModelToJSONTyped,
} from './cocktailImageModel';
import type { CocktailRatingModel } from './cocktailRatingModel';
import {
    CocktailRatingModelFromJSON,
    CocktailRatingModelFromJSONTyped,
    CocktailRatingModelToJSON,
    CocktailRatingModelToJSONTyped,
} from './cocktailRatingModel';
import type { CocktailKeywordsModel } from './cocktailKeywordsModel';
import {
    CocktailKeywordsModelFromJSON,
    CocktailKeywordsModelFromJSONTyped,
    CocktailKeywordsModelToJSON,
    CocktailKeywordsModelToJSONTyped,
} from './cocktailKeywordsModel';
import type { IngredientModel } from './ingredientModel';
import {
    IngredientModelFromJSON,
    IngredientModelFromJSONTyped,
    IngredientModelToJSON,
    IngredientModelToJSONTyped,
} from './ingredientModel';
import type { InstructionStepModel } from './instructionStepModel';
import {
    InstructionStepModelFromJSON,
    InstructionStepModelFromJSONTyped,
    InstructionStepModelToJSON,
    InstructionStepModelToJSONTyped,
} from './instructionStepModel';

/**
 * The cocktail recipe model
 * @export
 * @interface CocktailModel
 */
export interface CocktailModel {
    /**
     * The cocktail recipe unique identifier
     * @type {string}
     * @memberof CocktailModel
     */
    id: string;
    /**
     * The name of the cocktail recipe
     * @type {string}
     * @memberof CocktailModel
     */
    title: string;
    /**
     * A more descriptive title for the cocktail recipe, generally used as an editorial title
     * @type {string}
     * @memberof CocktailModel
     */
    descriptiveTitle: string;
    /**
     * A brief editorial description for the cocktail recipe
     * @type {string}
     * @memberof CocktailModel
     */
    description: string;
    /**
     * The complete descriptive cocktail recipe including ingredients, directions and historical information in markdown format
     * @type {string}
     * @memberof CocktailModel
     */
    content: string;
    /**
     * The date this cocktail recipe was published on Cezzis.Com
     * @type {Date}
     * @memberof CocktailModel
     */
    publishedOn: Date;
    /**
     * The date this cocktail recipe was last modified on Cezzis.Com
     * @type {Date}
     * @memberof CocktailModel
     */
    modifiedOn: Date;
    /**
     * The number of people the cocktail recipe serves
     * @type {number}
     * @memberof CocktailModel
     */
    serves: number;
    /**
     * The average number of minutes to build the cocktail using this recipe
     * @type {number}
     * @memberof CocktailModel
     */
    prepTimeMinutes: number;
    /**
     * Whether or not the cocktail represented by this recipe is recognized by the International Bartenders Association
     * @type {boolean}
     * @memberof CocktailModel
     */
    isIba: boolean;
    /**
     * A list of primary images for the cocktail recipe
     * @type {Array<CocktailImageModel>}
     * @memberof CocktailModel
     */
    mainImages: Array<CocktailImageModel>;
    /**
     * A list of secondary, smaller sized images for the cocktail recipe
     * @type {Array<any>}
     * @memberof CocktailModel
     */
    searchTiles: Array<any>;
    /**
     * The recommended glassware to use when serving the cocktail
     * @type {Array<GlasswareTypeModel>}
     * @memberof CocktailModel
     */
    glassware: Array<GlasswareTypeModel>;
    /**
     * 
     * @type {CocktailRatingModel}
     * @memberof CocktailModel
     */
    rating: CocktailRatingModel;
    /**
     * A list of titles that are queried against when issuing cocktail recipe search queries
     * @type {Array<string>}
     * @memberof CocktailModel
     */
    searchableTitles: Array<string>;
    /**
     * A list of taxonomy tags defining the cocktail recipe
     * @type {Array<string>}
     * @memberof CocktailModel
     */
    tags: Array<string>;
    /**
     * The list of ingredients that make up the cocktail recipe
     * @type {Array<IngredientModel>}
     * @memberof CocktailModel
     */
    ingredients: Array<IngredientModel>;
    /**
     * The list of instructions to make the cocktail recipe
     * @type {Array<InstructionStepModel>}
     * @memberof CocktailModel
     */
    instructions: Array<InstructionStepModel>;
    /**
     * 
     * @type {CocktailKeywordsModel}
     * @memberof CocktailModel
     */
    keywords: CocktailKeywordsModel;
}

/**
 * Check if a given object implements the CocktailModel interface.
 */
export function instanceOfCocktailModel(value: object): value is CocktailModel {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('title' in value) || value['title'] === undefined) return false;
    if (!('descriptiveTitle' in value) || value['descriptiveTitle'] === undefined) return false;
    if (!('description' in value) || value['description'] === undefined) return false;
    if (!('content' in value) || value['content'] === undefined) return false;
    if (!('publishedOn' in value) || value['publishedOn'] === undefined) return false;
    if (!('modifiedOn' in value) || value['modifiedOn'] === undefined) return false;
    if (!('serves' in value) || value['serves'] === undefined) return false;
    if (!('prepTimeMinutes' in value) || value['prepTimeMinutes'] === undefined) return false;
    if (!('isIba' in value) || value['isIba'] === undefined) return false;
    if (!('mainImages' in value) || value['mainImages'] === undefined) return false;
    if (!('searchTiles' in value) || value['searchTiles'] === undefined) return false;
    if (!('glassware' in value) || value['glassware'] === undefined) return false;
    if (!('rating' in value) || value['rating'] === undefined) return false;
    if (!('searchableTitles' in value) || value['searchableTitles'] === undefined) return false;
    if (!('tags' in value) || value['tags'] === undefined) return false;
    if (!('ingredients' in value) || value['ingredients'] === undefined) return false;
    if (!('instructions' in value) || value['instructions'] === undefined) return false;
    if (!('keywords' in value) || value['keywords'] === undefined) return false;
    return true;
}

export function CocktailModelFromJSON(json: any): CocktailModel {
    return CocktailModelFromJSONTyped(json, false);
}

export function CocktailModelFromJSONTyped(json: any, ignoreDiscriminator: boolean): CocktailModel {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'title': json['title'],
        'descriptiveTitle': json['descriptiveTitle'],
        'description': json['description'],
        'content': json['content'],
        'publishedOn': (new Date(json['publishedOn'])),
        'modifiedOn': (new Date(json['modifiedOn'])),
        'serves': json['serves'],
        'prepTimeMinutes': json['prepTimeMinutes'],
        'isIba': json['isIba'],
        'mainImages': ((json['mainImages'] as Array<any>).map(CocktailImageModelFromJSON)),
        'searchTiles': json['searchTiles'],
        'glassware': ((json['glassware'] as Array<any>).map(GlasswareTypeModelFromJSON)),
        'rating': CocktailRatingModelFromJSON(json['rating']),
        'searchableTitles': json['searchableTitles'],
        'tags': json['tags'],
        'ingredients': ((json['ingredients'] as Array<any>).map(IngredientModelFromJSON)),
        'instructions': ((json['instructions'] as Array<any>).map(InstructionStepModelFromJSON)),
        'keywords': CocktailKeywordsModelFromJSON(json['keywords']),
    };
}

export function CocktailModelToJSON(json: any): CocktailModel {
    return CocktailModelToJSONTyped(json, false);
}

export function CocktailModelToJSONTyped(value?: CocktailModel | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'title': value['title'],
        'descriptiveTitle': value['descriptiveTitle'],
        'description': value['description'],
        'content': value['content'],
        'publishedOn': value['publishedOn'].toISOString(),
        'modifiedOn': value['modifiedOn'].toISOString(),
        'serves': value['serves'],
        'prepTimeMinutes': value['prepTimeMinutes'],
        'isIba': value['isIba'],
        'mainImages': ((value['mainImages'] as Array<any>).map(CocktailImageModelToJSON)),
        'searchTiles': value['searchTiles'],
        'glassware': ((value['glassware'] as Array<any>).map(GlasswareTypeModelToJSON)),
        'rating': CocktailRatingModelToJSON(value['rating']),
        'searchableTitles': value['searchableTitles'],
        'tags': value['tags'],
        'ingredients': ((value['ingredients'] as Array<any>).map(IngredientModelToJSON)),
        'instructions': ((value['instructions'] as Array<any>).map(InstructionStepModelToJSON)),
        'keywords': CocktailKeywordsModelToJSON(value['keywords']),
    };
}

