/* tslint:disable */
/* eslint-disable */
/**
 * Cocktails Api
 * Cocktails Api
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CocktailImageModel
 */
export interface CocktailImageModel {
    /**
     * The uri of the image
     * @type {string}
     * @memberof CocktailImageModel
     */
    uri: string;
    /**
     * The width of the image
     * @type {number}
     * @memberof CocktailImageModel
     */
    width: number;
    /**
     * The height of the image
     * @type {number}
     * @memberof CocktailImageModel
     */
    height: number;
}

/**
 * Check if a given object implements the CocktailImageModel interface.
 */
export function instanceOfCocktailImageModel(value: object): value is CocktailImageModel {
    if (!('uri' in value) || value['uri'] === undefined) return false;
    if (!('width' in value) || value['width'] === undefined) return false;
    if (!('height' in value) || value['height'] === undefined) return false;
    return true;
}

export function CocktailImageModelFromJSON(json: any): CocktailImageModel {
    return CocktailImageModelFromJSONTyped(json, false);
}

export function CocktailImageModelFromJSONTyped(json: any, ignoreDiscriminator: boolean): CocktailImageModel {
    if (json == null) {
        return json;
    }
    return {
        
        'uri': json['uri'],
        'width': json['width'],
        'height': json['height'],
    };
}

export function CocktailImageModelToJSON(json: any): CocktailImageModel {
    return CocktailImageModelToJSONTyped(json, false);
}

export function CocktailImageModelToJSONTyped(value?: CocktailImageModel | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'uri': value['uri'],
        'width': value['width'],
        'height': value['height'],
    };
}

