/* tslint:disable */
/* eslint-disable */
/**
 * Cocktails Api
 * Cocktails Api
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * The format that the document content is in
 * @export
 * @enum {string}
 */
export enum DocumentFormat {
    Markdown = 'markdown'
}


export function instanceOfDocumentFormat(value: any): boolean {
    for (const key in DocumentFormat) {
        if (Object.prototype.hasOwnProperty.call(DocumentFormat, key)) {
            if (DocumentFormat[key as keyof typeof DocumentFormat] === value) {
                return true;
            }
        }
    }
    return false;
}

export function DocumentFormatFromJSON(json: any): DocumentFormat {
    return DocumentFormatFromJSONTyped(json, false);
}

export function DocumentFormatFromJSONTyped(json: any, ignoreDiscriminator: boolean): DocumentFormat {
    return json as DocumentFormat;
}

export function DocumentFormatToJSON(value?: DocumentFormat | null): any {
    return value as any;
}

export function DocumentFormatToJSONTyped(value: any, ignoreDiscriminator: boolean): DocumentFormat {
    return value as DocumentFormat;
}

