/* tslint:disable */
/* eslint-disable */
/**
 * Cocktails Api
 * Cocktails Api
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { IngredientTypeModel } from './ingredientTypeModel';
import {
    IngredientTypeModelFromJSON,
    IngredientTypeModelFromJSONTyped,
    IngredientTypeModelToJSON,
    IngredientTypeModelToJSONTyped,
} from './ingredientTypeModel';
import type { IngredientRequirementTypeModel } from './ingredientRequirementTypeModel';
import {
    IngredientRequirementTypeModelFromJSON,
    IngredientRequirementTypeModelFromJSONTyped,
    IngredientRequirementTypeModelToJSON,
    IngredientRequirementTypeModelToJSONTyped,
} from './ingredientRequirementTypeModel';
import type { PreparationTypeModel } from './preparationTypeModel';
import {
    PreparationTypeModelFromJSON,
    PreparationTypeModelFromJSONTyped,
    PreparationTypeModelToJSON,
    PreparationTypeModelToJSONTyped,
} from './preparationTypeModel';
import type { UofMTypeModel } from './uofMTypeModel';
import {
    UofMTypeModelFromJSON,
    UofMTypeModelFromJSONTyped,
    UofMTypeModelToJSON,
    UofMTypeModelToJSONTyped,
} from './uofMTypeModel';
import type { IngredientApplicationModel } from './ingredientApplicationModel';
import {
    IngredientApplicationModelFromJSON,
    IngredientApplicationModelFromJSONTyped,
    IngredientApplicationModelToJSON,
    IngredientApplicationModelToJSONTyped,
} from './ingredientApplicationModel';

/**
 * 
 * @export
 * @interface IngredientModel
 */
export interface IngredientModel {
    /**
     * The name of the ingredient
     * @type {string}
     * @memberof IngredientModel
     */
    name: string;
    /**
     * 
     * @type {UofMTypeModel}
     * @memberof IngredientModel
     */
    uoM: UofMTypeModel;
    /**
     * 
     * @type {IngredientRequirementTypeModel}
     * @memberof IngredientModel
     */
    requirement: IngredientRequirementTypeModel;
    /**
     * Gets the complete display value for the ingredient including units and measurments
     * @type {string}
     * @memberof IngredientModel
     */
    display: string;
    /**
     * The number of units to use in relation to the UoM (unit of measure) in the cocktail recipe
     * @type {number}
     * @memberof IngredientModel
     */
    units: number;
    /**
     * 
     * @type {PreparationTypeModel}
     * @memberof IngredientModel
     */
    preparation: PreparationTypeModel;
    /**
     * Suggestion when using this ingredient
     * @type {string}
     * @memberof IngredientModel
     */
    suggestions: string;
    /**
     * The ingredient types that this ingredient is in relation to the cocktail recipe
     * @type {Array<IngredientTypeModel>}
     * @memberof IngredientModel
     */
    types: Array<IngredientTypeModel>;
    /**
     * The ingredient applications that this ingredient is in relation to the cocktail recipe
     * @type {Array<IngredientApplicationModel>}
     * @memberof IngredientModel
     */
    applications: Array<IngredientApplicationModel>;
}



/**
 * Check if a given object implements the IngredientModel interface.
 */
export function instanceOfIngredientModel(value: object): value is IngredientModel {
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('uoM' in value) || value['uoM'] === undefined) return false;
    if (!('requirement' in value) || value['requirement'] === undefined) return false;
    if (!('display' in value) || value['display'] === undefined) return false;
    if (!('units' in value) || value['units'] === undefined) return false;
    if (!('preparation' in value) || value['preparation'] === undefined) return false;
    if (!('suggestions' in value) || value['suggestions'] === undefined) return false;
    if (!('types' in value) || value['types'] === undefined) return false;
    if (!('applications' in value) || value['applications'] === undefined) return false;
    return true;
}

export function IngredientModelFromJSON(json: any): IngredientModel {
    return IngredientModelFromJSONTyped(json, false);
}

export function IngredientModelFromJSONTyped(json: any, ignoreDiscriminator: boolean): IngredientModel {
    if (json == null) {
        return json;
    }
    return {
        
        'name': json['name'],
        'uoM': UofMTypeModelFromJSON(json['uoM']),
        'requirement': IngredientRequirementTypeModelFromJSON(json['requirement']),
        'display': json['display'],
        'units': json['units'],
        'preparation': PreparationTypeModelFromJSON(json['preparation']),
        'suggestions': json['suggestions'],
        'types': ((json['types'] as Array<any>).map(IngredientTypeModelFromJSON)),
        'applications': ((json['applications'] as Array<any>).map(IngredientApplicationModelFromJSON)),
    };
}

export function IngredientModelToJSON(json: any): IngredientModel {
    return IngredientModelToJSONTyped(json, false);
}

export function IngredientModelToJSONTyped(value?: IngredientModel | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'name': value['name'],
        'uoM': UofMTypeModelToJSON(value['uoM']),
        'requirement': IngredientRequirementTypeModelToJSON(value['requirement']),
        'display': value['display'],
        'units': value['units'],
        'preparation': PreparationTypeModelToJSON(value['preparation']),
        'suggestions': value['suggestions'],
        'types': ((value['types'] as Array<any>).map(IngredientTypeModelToJSON)),
        'applications': ((value['applications'] as Array<any>).map(IngredientApplicationModelToJSON)),
    };
}

