/* tslint:disable */
/* eslint-disable */
/**
 * Cocktails Api
 * Cocktails Api
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface InstructionStepModel
 */
export interface InstructionStepModel {
    /**
     * The displayable value for the instruction step
     * @type {string}
     * @memberof InstructionStepModel
     */
    display: string;
    /**
     * The order of the instruction step in which it should be performed
     * @type {number}
     * @memberof InstructionStepModel
     */
    order: number;
}

/**
 * Check if a given object implements the InstructionStepModel interface.
 */
export function instanceOfInstructionStepModel(value: object): value is InstructionStepModel {
    if (!('display' in value) || value['display'] === undefined) return false;
    if (!('order' in value) || value['order'] === undefined) return false;
    return true;
}

export function InstructionStepModelFromJSON(json: any): InstructionStepModel {
    return InstructionStepModelFromJSONTyped(json, false);
}

export function InstructionStepModelFromJSONTyped(json: any, ignoreDiscriminator: boolean): InstructionStepModel {
    if (json == null) {
        return json;
    }
    return {
        
        'display': json['display'],
        'order': json['order'],
    };
}

export function InstructionStepModelToJSON(json: any): InstructionStepModel {
    return InstructionStepModelToJSONTyped(json, false);
}

export function InstructionStepModelToJSONTyped(value?: InstructionStepModel | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'display': value['display'],
        'order': value['order'],
    };
}

