/* tslint:disable */
/* eslint-disable */
/**
 * Cocktails Api
 * Cocktails Api
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { DocumentFormat } from './documentFormat';
import {
    DocumentFormatFromJSON,
    DocumentFormatFromJSONTyped,
    DocumentFormatToJSON,
    DocumentFormatToJSONTyped,
} from './documentFormat';

/**
 * 
 * @export
 * @interface LegalDocumentRs
 */
export interface LegalDocumentRs {
    /**
     * The document content
     * @type {string}
     * @memberof LegalDocumentRs
     */
    document: string;
    /**
     * 
     * @type {DocumentFormat}
     * @memberof LegalDocumentRs
     */
    format: DocumentFormat;
}



/**
 * Check if a given object implements the LegalDocumentRs interface.
 */
export function instanceOfLegalDocumentRs(value: object): value is LegalDocumentRs {
    if (!('document' in value) || value['document'] === undefined) return false;
    if (!('format' in value) || value['format'] === undefined) return false;
    return true;
}

export function LegalDocumentRsFromJSON(json: any): LegalDocumentRs {
    return LegalDocumentRsFromJSONTyped(json, false);
}

export function LegalDocumentRsFromJSONTyped(json: any, ignoreDiscriminator: boolean): LegalDocumentRs {
    if (json == null) {
        return json;
    }
    return {
        
        'document': json['document'],
        'format': DocumentFormatFromJSON(json['format']),
    };
}

export function LegalDocumentRsToJSON(json: any): LegalDocumentRs {
    return LegalDocumentRsToJSONTyped(json, false);
}

export function LegalDocumentRsToJSONTyped(value?: LegalDocumentRs | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'document': value['document'],
        'format': DocumentFormatToJSON(value['format']),
    };
}

