/* tslint:disable */
/* eslint-disable */
/**
 * Cocktails Api
 * Cocktails Api
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface PublishCocktailsRq
 */
export interface PublishCocktailsRq {
    /**
     * A list of cocktail IDs to publish
     * @type {Array<string>}
     * @memberof PublishCocktailsRq
     */
    cocktailIds: Array<string>;
}

/**
 * Check if a given object implements the PublishCocktailsRq interface.
 */
export function instanceOfPublishCocktailsRq(value: object): value is PublishCocktailsRq {
    if (!('cocktailIds' in value) || value['cocktailIds'] === undefined) return false;
    return true;
}

export function PublishCocktailsRqFromJSON(json: any): PublishCocktailsRq {
    return PublishCocktailsRqFromJSONTyped(json, false);
}

export function PublishCocktailsRqFromJSONTyped(json: any, ignoreDiscriminator: boolean): PublishCocktailsRq {
    if (json == null) {
        return json;
    }
    return {
        
        'cocktailIds': json['cocktailIds'],
    };
}

export function PublishCocktailsRqToJSON(json: any): PublishCocktailsRq {
    return PublishCocktailsRqToJSONTyped(json, false);
}

export function PublishCocktailsRqToJSONTyped(value?: PublishCocktailsRq | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'cocktailIds': value['cocktailIds'],
    };
}

