FROM nginx:1.27.3-alpine

# Copy nginx configuration
COPY ./nginx-default.conf /etc/nginx/conf.d/default.conf

# Ensure proper MIME types for JavaScript modules
RUN echo 'application/javascript js mjs;' >> /etc/nginx/mime.types

COPY ./dist /usr/share/nginx/html
RUN mkdir -p /usr/share/nginx/html/public

EXPOSE 80
EXPOSE 443

# Copy .env file and shell script to container
WORKDIR /usr/share/nginx/html
COPY ./env.sh .
COPY .env .

# Add bash
RUN apk add --no-cache bash

# Make our shell script executable
RUN chmod +x env.sh

# Start Nginx server
CMD ["/bin/bash", "-c", "/usr/share/nginx/html/env.sh .env && nginx -g \"daemon off;\""]