variables:
  serviceConnectionName: 'sc-vec-eus-default-svc-principal-001'

trigger: none

name: $(Build.DefinitionName)_$(Date:yyyyMMdd)$(Rev:.r)

pool:
  vmImage: ubuntu-latest

stages:
  - stage: IntegrationTests
    displayName: 'Run Cypress Tests'

    variables:
      keyVaultName: 'kv-vec-eus-prd-cockti-1'

    jobs:
    - job: e2e
      displayName: 'E2e test ui'
      steps:
        - task: AzureKeyVault@2
          displayName: 'KeyVault Get Cypress User Password'
          inputs:
            azureSubscription: ${{ variables.serviceConnectionName }}
            keyVaultName: ${{ variables.keyVaultName}}
            secretsFilter: 'e2e-cypress-user-password'

        - template: ui-cypress.yml
          parameters:
            env: prd
            branchType: 'main'
            workingDirectory: '$(System.DefaultWorkingDirectory)/cocktails.frontend/cocktails.web.e2e'
            baseUrl: 'https://www.cezzis.com'
            b2cUrl: 'https://cezzis.b2clogin.com/'
            b2cTenantId: 'fb512a9c-5b44-41ab-8042-6465769f16c9'
            b2cClientId: '84744194-da27-410f-ae0e-74f5589d4c96'
            b2cUserObjectId: '41598664-1466-4e3e-b28c-dfe9837e462e'
            b2cUserEmail: 'rvecchi+cypress@gmail.com'
            b2cUserPassword: '$(e2e-cypress-user-password)'

          