parameters:
  - name: name
    type: string
  - name: display
    type: string
  - name: rootDirectory
    type: string

jobs:
- job: ${{ parameters.name }}
  displayName: '${{ parameters.display }}'
  steps:
  - checkout: self
    displayName: 'Checkout repository'
    submodules: 'true'
    fetchDepth: 0
    persistCredentials: true

  - script: |
      echo '=============diff=============='
      git diff --name-only HEAD^ HEAD
      git diff --name-only HEAD^ HEAD > ${{ parameters.rootDirectory }}_changed_files.txt
      echo ""
      echo ""

      echo "================================================================"
      echo "========== check ${{ parameters.rootDirectory }} modified files "
      echo "================================================================"
      while IFS= read -r file
      do
        if [[ $file == ${{ parameters.rootDirectory }}/* ]]; then
          echo "- $file"
        fi
      done < ${{ parameters.rootDirectory }}_changed_files.txt

      echo "================================================================"
      echo ""
      echo ""

    name: ListFiles
    displayName: 'Listing files'
