/* tslint:disable */
/* eslint-disable */
/**
 * Cocktails Api
 * Cocktails Api
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  ProblemDetails,
  PublishCocktailsRq,
} from '../models/index';
import {
    ProblemDetailsFromJSON,
    ProblemDetailsToJSON,
    PublishCocktailsRqFromJSON,
    PublishCocktailsRqToJSON,
} from '../models/index';

export interface PublishCocktailsRequest {
    PublishCocktailsRq: PublishCocktailsRq;
    X_Key?: string;
}

/**
 * CocktailsAdminApi - interface
 * 
 * @export
 * @interface CocktailsAdminApiInterface
 */
export interface CocktailsAdminApiInterface {
    /**
     * Publishes the cocktails to an event stream
     * @param {PublishCocktailsRq} PublishCocktailsRq The request to publish cocktails to external systems
     * @param {string} [X_Key] Subscription key
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof CocktailsAdminApiInterface
     */
    publishCocktailsRaw(requestParameters: PublishCocktailsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>>;

    /**
     * Publishes the cocktails to an event stream
     */
    publishCocktails(requestParameters: PublishCocktailsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void>;

}

/**
 * 
 */
export class CocktailsAdminApi extends runtime.BaseAPI implements CocktailsAdminApiInterface {

    /**
     * Publishes the cocktails to an event stream
     */
    async publishCocktailsRaw(requestParameters: PublishCocktailsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        if (requestParameters['PublishCocktailsRq'] == null) {
            throw new runtime.RequiredError(
                'PublishCocktailsRq',
                'Required parameter "PublishCocktailsRq" was null or undefined when calling publishCocktails().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json; x-api-version=1.0';

        if (requestParameters['X_Key'] != null) {
            headerParameters['X-Key'] = String(requestParameters['X_Key']);
        }

        if (this.configuration && this.configuration.accessToken) {
            // oauth required
            headerParameters["Authorization"] = await this.configuration.accessToken("oauth2", ["admin:cezzi-cocktails"]);
        }


        let urlPath = `/api/v1/cocktails/admin/pub`;

        const response = await this.request({
            path: urlPath,
            method: 'PUT',
            headers: headerParameters,
            query: queryParameters,
            body: PublishCocktailsRqToJSON(requestParameters['PublishCocktailsRq']),
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Publishes the cocktails to an event stream
     */
    async publishCocktails(requestParameters: PublishCocktailsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.publishCocktailsRaw(requestParameters, initOverrides);
    }

}
