/* tslint:disable */
/* eslint-disable */
/**
 * Cocktails Api
 * Cocktails Api
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  CocktailIngredientFiltersRs,
  CocktailRs,
  ProblemDetails,
} from '../models/index';
import {
    CocktailIngredientFiltersRsFromJSON,
    CocktailIngredientFiltersRsToJSON,
    CocktailRsFromJSON,
    CocktailRsToJSON,
    ProblemDetailsFromJSON,
    ProblemDetailsToJSON,
} from '../models/index';

export interface GetCocktailRequest {
    id: string;
    X_Key?: string;
}

export interface GetCocktailIngredientFiltersRequest {
    X_Key?: string;
}

export interface SeedCocktailsRequest {
    X_Key?: string;
}

export interface SeedIngredientsRequest {
    X_Key?: string;
}

/**
 * CocktailsApi - interface
 * 
 * @export
 * @interface CocktailsApiInterface
 */
export interface CocktailsApiInterface {
    /**
     * Get a specific cocktail recipe
     * @param {string} id The cocktail recipe unique identifier
     * @param {string} [X_Key] Subscription key
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof CocktailsApiInterface
     */
    getCocktailRaw(requestParameters: GetCocktailRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<CocktailRs>>;

    /**
     * Get a specific cocktail recipe
     */
    getCocktail(requestParameters: GetCocktailRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<CocktailRs>;

    /**
     * Get the available cocktails filters to be used while performing a search
     * @param {string} [X_Key] Subscription key
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof CocktailsApiInterface
     */
    getCocktailIngredientFiltersRaw(requestParameters: GetCocktailIngredientFiltersRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<CocktailIngredientFiltersRs>>;

    /**
     * Get the available cocktails filters to be used while performing a search
     */
    getCocktailIngredientFilters(requestParameters: GetCocktailIngredientFiltersRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<CocktailIngredientFiltersRs>;

    /**
     * Seeds the cocktails in the database
     * @param {string} [X_Key] Subscription key
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof CocktailsApiInterface
     */
    seedCocktailsRaw(requestParameters: SeedCocktailsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>>;

    /**
     * Seeds the cocktails in the database
     */
    seedCocktails(requestParameters: SeedCocktailsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void>;

    /**
     * Seeds the ingredients in the database
     * @param {string} [X_Key] Subscription key
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof CocktailsApiInterface
     */
    seedIngredientsRaw(requestParameters: SeedIngredientsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>>;

    /**
     * Seeds the ingredients in the database
     */
    seedIngredients(requestParameters: SeedIngredientsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void>;

}

/**
 * 
 */
export class CocktailsApi extends runtime.BaseAPI implements CocktailsApiInterface {

    /**
     * Get a specific cocktail recipe
     */
    async getCocktailRaw(requestParameters: GetCocktailRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<CocktailRs>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling getCocktail().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (requestParameters['X_Key'] != null) {
            headerParameters['X-Key'] = String(requestParameters['X_Key']);
        }


        let urlPath = `/api/v1/cocktails/{id}`;
        urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id'])));

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => CocktailRsFromJSON(jsonValue));
    }

    /**
     * Get a specific cocktail recipe
     */
    async getCocktail(requestParameters: GetCocktailRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<CocktailRs> {
        const response = await this.getCocktailRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Get the available cocktails filters to be used while performing a search
     */
    async getCocktailIngredientFiltersRaw(requestParameters: GetCocktailIngredientFiltersRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<CocktailIngredientFiltersRs>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (requestParameters['X_Key'] != null) {
            headerParameters['X-Key'] = String(requestParameters['X_Key']);
        }


        let urlPath = `/api/v1/cocktails/ingredients/filters`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => CocktailIngredientFiltersRsFromJSON(jsonValue));
    }

    /**
     * Get the available cocktails filters to be used while performing a search
     */
    async getCocktailIngredientFilters(requestParameters: GetCocktailIngredientFiltersRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<CocktailIngredientFiltersRs> {
        const response = await this.getCocktailIngredientFiltersRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Seeds the cocktails in the database
     */
    async seedCocktailsRaw(requestParameters: SeedCocktailsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (requestParameters['X_Key'] != null) {
            headerParameters['X-Key'] = String(requestParameters['X_Key']);
        }


        let urlPath = `/api/v1/cocktails`;

        const response = await this.request({
            path: urlPath,
            method: 'PUT',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Seeds the cocktails in the database
     */
    async seedCocktails(requestParameters: SeedCocktailsRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.seedCocktailsRaw(requestParameters, initOverrides);
    }

    /**
     * Seeds the ingredients in the database
     */
    async seedIngredientsRaw(requestParameters: SeedIngredientsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (requestParameters['X_Key'] != null) {
            headerParameters['X-Key'] = String(requestParameters['X_Key']);
        }


        let urlPath = `/api/v1/cocktails/ingredients`;

        const response = await this.request({
            path: urlPath,
            method: 'PUT',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Seeds the ingredients in the database
     */
    async seedIngredients(requestParameters: SeedIngredientsRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.seedIngredientsRaw(requestParameters, initOverrides);
    }

}
