/* tslint:disable */
/* eslint-disable */
/**
 * Cocktails Api
 * Cocktails Api
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  LegalDocumentRs,
  ProblemDetails,
} from '../models/index';
import {
    LegalDocumentRsFromJSON,
    LegalDocumentRsToJSON,
    ProblemDetailsFromJSON,
    ProblemDetailsToJSON,
} from '../models/index';

export interface GetPrivacyPolicyRequest {
    X_Key?: string;
}

export interface GetTermsOfServiceRequest {
    X_Key?: string;
}

/**
 * LegalApi - interface
 * 
 * @export
 * @interface LegalApiInterface
 */
export interface LegalApiInterface {
    /**
     * Gets the Cezzi\'s.com privacy policy
     * @param {string} [X_Key] Subscription key
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof LegalApiInterface
     */
    getPrivacyPolicyRaw(requestParameters: GetPrivacyPolicyRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<LegalDocumentRs>>;

    /**
     * Gets the Cezzi\'s.com privacy policy
     */
    getPrivacyPolicy(requestParameters: GetPrivacyPolicyRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<LegalDocumentRs>;

    /**
     * Gets the Cezzi\'s.com terms of service
     * @param {string} [X_Key] Subscription key
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof LegalApiInterface
     */
    getTermsOfServiceRaw(requestParameters: GetTermsOfServiceRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<LegalDocumentRs>>;

    /**
     * Gets the Cezzi\'s.com terms of service
     */
    getTermsOfService(requestParameters: GetTermsOfServiceRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<LegalDocumentRs>;

}

/**
 * 
 */
export class LegalApi extends runtime.BaseAPI implements LegalApiInterface {

    /**
     * Gets the Cezzi\'s.com privacy policy
     */
    async getPrivacyPolicyRaw(requestParameters: GetPrivacyPolicyRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<LegalDocumentRs>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (requestParameters['X_Key'] != null) {
            headerParameters['X-Key'] = String(requestParameters['X_Key']);
        }


        let urlPath = `/api/v1/legal/documents/privacy-policy`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => LegalDocumentRsFromJSON(jsonValue));
    }

    /**
     * Gets the Cezzi\'s.com privacy policy
     */
    async getPrivacyPolicy(requestParameters: GetPrivacyPolicyRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<LegalDocumentRs> {
        const response = await this.getPrivacyPolicyRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Gets the Cezzi\'s.com terms of service
     */
    async getTermsOfServiceRaw(requestParameters: GetTermsOfServiceRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<LegalDocumentRs>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (requestParameters['X_Key'] != null) {
            headerParameters['X-Key'] = String(requestParameters['X_Key']);
        }


        let urlPath = `/api/v1/legal/documents/terms-of-service`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => LegalDocumentRsFromJSON(jsonValue));
    }

    /**
     * Gets the Cezzi\'s.com terms of service
     */
    async getTermsOfService(requestParameters: GetTermsOfServiceRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<LegalDocumentRs> {
        const response = await this.getTermsOfServiceRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
